package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	testSchemaIntegerType = "integer"
	testSchemaObjectType  = "object"
)

func TestAnonymousJSONObjectIsRejected(t *testing.T) {
	t.Parallel()

	source := []byte(`package sample
func request() {
	var raw struct {
		RangeValue *struct { Value *float64 ` + "`json:\"value\"`" + ` } ` + "`json:\"rangeValue\"`" + `
	}
}
`)

	_, problems, _ := scanHandwrittenSource("pkg/request.go", source, token.NewFileSet(), false, nil)
	if !containsProblem(problems, "anonymous handwritten JSON object") {
		t.Fatalf("scanHandwrittenSource() problems = %v; want anonymous JSON object rejection", problems)
	}
}

func TestValidateEvidenceAcceptsExactReceiverSignatureReference(t *testing.T) {
	t.Parallel()

	path := writeEvidenceSource(t, `package sample
type SDKRequest struct{}
type Client struct{}
type Session struct{}
func (*Client) Convert(req SDKRequest) error { return consume(req) }
func (*Session) Convert(req string) error { return consume(req) }
`)

	err := validateEvidence(path+"#Client.Convert", "SDKRequest")
	if err != nil {
		t.Fatalf("validateEvidence() rejected production signature evidence: %v", err)
	}

	err = validateEvidence(path+"#Session.Convert", "SDKRequest")
	if err == nil {
		t.Fatal("validateEvidence() accepted a same-named method on the wrong receiver")
	}
}

func TestValidateEvidenceRejectsUnreferencedModel(t *testing.T) {
	t.Parallel()

	path := writeEvidenceSource(t, `package sample
type SDKRequest struct{}
type Client struct{}
func (*Client) Convert(value string) error { return consume(value) }
`)

	err := validateEvidence(path+"#Client.Convert", "SDKRequest")
	if err == nil {
		t.Fatal("validateEvidence() accepted a function unrelated to the listed model")
	}
}

func writeEvidenceSource(t *testing.T, source string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "evidence.go")

	err := os.WriteFile(path, []byte(source), 0o600)
	if err != nil {
		t.Fatalf("write evidence source: %v", err)
	}

	return path
}

func TestCopiedGeneratedMarkerDoesNotRegisterWireModel(t *testing.T) {
	t.Parallel()

	source := []byte(`// Code generated by an unregistered tool. DO NOT EDIT.
package sample
type Unregistered struct { Value string ` + "`json:\"value\"`" + ` }
`)

	_, problems, _ := scanHandwrittenSource("pkg/unregistered.gen.go", source, token.NewFileSet(), true, nil)
	if !containsProblem(problems, "unregistered generated Go file") {
		t.Fatalf("scanHandwrittenSource() problems = %v; want unregistered generated model rejection", problems)
	}
}

func TestCopiedSemanticMarkerDoesNotBypassExactManifest(t *testing.T) {
	t.Parallel()

	source := []byte(`package sample
//modelinventory:semantic Public SDK projection, generated on the wire.
type PublicValue struct { Value string ` + "`json:\"value\"`" + ` }
`)

	_, problems, _ := scanHandwrittenSource("pkg/public.go", source, token.NewFileSet(), false, map[string]handwrittenAllowance{})
	if !containsProblem(problems, "is not listed in") {
		t.Fatalf("scanHandwrittenSource() problems = %v; want unlisted marked model rejection", problems)
	}
}

func TestImplicitJSONFieldsAreInventoried(t *testing.T) {
	t.Parallel()

	source := []byte(`package sample
import "encoding/json"
type Implicit struct { Value string }
func encode(value Implicit) ([]byte, error) { return json.Marshal(value) }
`)

	_, problems, seen := scanHandwrittenSource("pkg/implicit.go", source, token.NewFileSet(), false, map[string]handwrittenAllowance{})
	if !containsProblem(problems, "is not listed in") || !seen["pkg/implicit.go::Implicit"] {
		t.Fatalf("scanHandwrittenSource() = problems %v, seen %v; want implicit JSON model inventoried and rejected", problems, seen)
	}
}

func TestGeneratedAllOfEmbeddingFieldsAreCompared(t *testing.T) {
	t.Parallel()

	file, err := parser.ParseFile(token.NewFileSet(), "generated.go", `package models
type BaseFeatureRequest struct {
	EndpointID string `+"`json:\"endpointId\"`"+`
	EntityID string `+"`json:\"entityId,omitempty\"`"+`
}
type BrightnessControlRequest struct {
	BaseFeatureRequest
	Brightness *int `+"`json:\"brightness,omitempty\"`"+`
}
`, 0)
	if err != nil {
		t.Fatal(err)
	}

	models := make(map[string]generatedModel)

	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range group.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			models[typeSpec.Name.Name] = generatedModel{
				Name: typeSpec.Name.Name, File: "", Schema: "", Generator: "",
				Fields: nil, Type: typeSpec.Type, Alias: false, Generated: true,
			}
		}
	}

	components := controlSchemaTestComponents()

	err = compareSchemaType(components["BrightnessControlRequest"], models["BrightnessControlRequest"].Type,
		"BrightnessControlRequest", "controls.yaml", models, components, make(map[string]bool))
	if err != nil {
		t.Fatalf("allOf-generated embedding failed schema comparison: %v", err)
	}

	missingFieldFile, err := parser.ParseFile(token.NewFileSet(), "generated_missing_field.go", `package models
type BrightnessControlRequest struct {
	BaseFeatureRequest
}
`, 0)
	if err != nil {
		t.Fatal(err)
	}

	missingField := parsedTestType(t, missingFieldFile, "BrightnessControlRequest")

	err = compareSchemaType(components["BrightnessControlRequest"], missingField.Type,
		"BrightnessControlRequest", "controls.yaml", models, components, make(map[string]bool))
	if err == nil {
		t.Fatal("schema comparison accepted a generated model with a missing field")
	}
}

func TestUnreferencedGeneratedModelIsRejected(t *testing.T) {
	t.Parallel()

	file, err := parser.ParseFile(token.NewFileSet(), "generated.go", `package models
type UnlistedWireValue struct { Value string `+"`json:\"value\"`"+` }
`, 0)
	if err != nil {
		t.Fatal(err)
	}

	typeSpec := parsedTestType(t, file, "UnlistedWireValue")

	models := map[string]generatedModel{
		"UnlistedWireValue": {
			Name: "UnlistedWireValue", File: "pkg/dependencymodels/endpoints.gen.go",
			Schema: "api/openapi.yaml", Generator: "oapi-codegen v2.8.0",
			Fields: nil, Type: typeSpec.Type, Alias: false, Generated: true,
		},
	}

	_, err = generatedModelRows(models, map[string]bool{}, map[string]bool{})
	if err == nil || !strings.Contains(err.Error(), "not a schema component") {
		t.Fatalf("generatedModelRows() error = %v; want unreachable schema model rejection", err)
	}
}

func TestParameterSchemaRejectsGeneratedPrimitiveDrift(t *testing.T) {
	t.Parallel()

	var primitive schemaNode

	primitive.Type = testSchemaIntegerType

	var incorrectType ast.Ident

	incorrectType.Name = schemaStringType

	err := compareParameterSchema(primitive, &incorrectType, "MaxResults", "api/openapi.yaml", nil, nil, nil)
	if err == nil {
		t.Fatal("compareParameterSchema() accepted a string for an integer parameter")
	}
}

func TestAnonymousImplicitJSONFieldsAreRejected(t *testing.T) {
	t.Parallel()

	source := []byte(`package sample
import "encoding/json"
func encode(value interface{}) ([]byte, error) {
	request := struct { Value string }{Value: "synthetic"}
	return json.Marshal(request)
}
`)

	_, problems, _ := scanHandwrittenSource("pkg/implicit.go", source, token.NewFileSet(), false, nil)
	if !containsProblem(problems, "anonymous handwritten JSON object") {
		t.Fatalf("scanHandwrittenSource() problems = %v; want anonymous implicit JSON rejection", problems)
	}
}

func containsProblem(problems []string, substring string) bool {
	for _, problem := range problems {
		if strings.Contains(problem, substring) {
			return true
		}
	}

	return false
}

func controlSchemaTestComponents() map[string]schemaNode {
	var stringSchema, integerSchema, parentReference, parent, child schemaNode

	stringSchema.Type = schemaStringType
	integerSchema.Type = testSchemaIntegerType
	parentReference.Ref = "#/components/schemas/BaseFeatureRequest"
	parent.Type = testSchemaObjectType
	parent.Properties = map[string]schemaNode{"endpointId": stringSchema, "entityId": stringSchema}
	child.Type = testSchemaObjectType
	child.AllOf = []schemaNode{parentReference}
	child.Properties = map[string]schemaNode{"brightness": integerSchema}

	return map[string]schemaNode{"BaseFeatureRequest": parent, "BrightnessControlRequest": child}
}

func parsedTestType(t *testing.T, file *ast.File, name string) *ast.TypeSpec {
	t.Helper()

	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, specification := range group.Specs {
			typeSpec, ok := specification.(*ast.TypeSpec)
			if ok && typeSpec.Name.Name == name {
				return typeSpec
			}
		}
	}

	t.Fatalf("parsed test source is missing type %s", name)

	return nil
}
