// Command modelinventory checks that checked-in provider schemas still match
// generated Go models and inventories every generated and handwritten model.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v2"
)

const (
	inventoryPath           = "docs/model-inventory.md"
	handwrittenManifestPath = "tools/modelinventory/handwritten.yaml"
	openAPISchemaPath       = "api/openapi.yaml"
	asyncAPISchemaPath      = "api/asyncapi.yaml"
	openAPIGenerator        = "oapi-codegen v2.8.0"
	asyncAPIGenerator       = "Modelina via make generate-api"
	graphQLSchemaPath       = "pkg/schemas/graphql/endpoints-schema.graphql plus operation documents in pkg/schemas/graphql/*.graphql"
	graphQLOutputPath       = "pkg/dependencymodels/graphql_models.gen.go"
	graphQLConfigPath       = "genqlient.yaml and tools/graphqlmodels/main.go"
	graphQLGenerator        = "make generate-graphql (go tool genqlient; tools/graphqlops; tools/graphqlmodels)"
	inventoryFileMode       = 0o600
	evidenceParts           = 2
	generatedHeaderLimit    = 2048
	minimumCompactValues    = 2
	schemaStringType        = "string"
	goIntType               = "int"
	goInt32Type             = "int32"
	goInt64Type             = "int64"
	generatedInventoryIntro = "Generated by `go run ./tools/modelinventory -write`. " +
		"The gate checks every named schema component against a generated declaration and compares each object component's " +
		"JSON field set to the generated Go shape, including inline nested objects. " +
		"Source-derived API contracts remain implementation-derived unless separately verified.\n\n"
	handwrittenInventoryIntro = "These exact type-level exceptions are handwritten because they are public SDK projections, caller inputs, " +
		"local state, or library error types. Each declaration carries a matching `modelinventory` marker naming the type and reason. " +
		"Provider wire fields remain generated from the schemas above. The gate rejects unlisted handwritten serialized structs, " +
		"and it rejects anonymous nested JSON objects even when a marker is present.\n\n"
)

type schemaDocument struct {
	Paths      map[string]pathItem `yaml:"paths"`
	Components struct {
		Schemas    map[string]schemaNode    `yaml:"schemas"`
		Parameters map[string]parameterNode `yaml:"parameters"`
	} `yaml:"components"`
}

type pathItem struct {
	Parameters []parameterNode `yaml:"parameters"`
	Get        *operationNode  `yaml:"get"`
	Post       *operationNode  `yaml:"post"`
	Put        *operationNode  `yaml:"put"`
	Patch      *operationNode  `yaml:"patch"`
	Delete     *operationNode  `yaml:"delete"`
	Head       *operationNode  `yaml:"head"`
	Options    *operationNode  `yaml:"options"`
	Trace      *operationNode  `yaml:"trace"`
}

type operationNode struct {
	OperationID string          `yaml:"operationId"`
	Parameters  []parameterNode `yaml:"parameters"`
}

type parameterNode struct {
	Ref           string     `yaml:"$ref"`
	ComponentName string     `yaml:"-"`
	Name          string     `yaml:"name"`
	In            string     `yaml:"in"`
	Required      bool       `yaml:"required"`
	Schema        schemaNode `yaml:"schema"`
}

type schemaNode struct {
	Ref                    string                `yaml:"$ref"`
	Type                   string                `yaml:"type"`
	Format                 string                `yaml:"format"`
	GoName                 string                `yaml:"x-go-name"`      //nolint:tagliatelle // OpenAPI extension spelling is fixed by the schema.
	GoTypeName             string                `yaml:"x-go-type-name"` //nolint:tagliatelle // OpenAPI extension spelling is fixed by the schema.
	GoType                 string                `yaml:"x-go-type"`      //nolint:tagliatelle // OpenAPI extension spelling is fixed by the schema.
	Properties             map[string]schemaNode `yaml:"properties"`
	Items                  *schemaNode           `yaml:"items"`
	AdditionalProperties   any                   `yaml:"additionalProperties"`
	AllOf                  []schemaNode          `yaml:"allOf"`
	Enum                   []any                 `yaml:"enum"`
	OneOf                  []schemaNode          `yaml:"oneOf"`
	AnyOf                  []schemaNode          `yaml:"anyOf"`
	GraphQLEnum            string                `yaml:"x-go-graphql-enum"`       //nolint:tagliatelle // Fixed schema metadata key.
	GraphQLJSONField       string                `yaml:"x-go-graphql-json-field"` //nolint:tagliatelle // Fixed schema metadata key.
	ExtensibleEnum         []string              `yaml:"x-extensible-enum"`       //nolint:tagliatelle // Fixed schema metadata key.
	Default                string                `yaml:"default"`
	CompatibilityNames     []string              `yaml:"x-go-compat-constant-names"`  //nolint:tagliatelle // Fixed schema metadata key.
	CompatibilityName      string                `yaml:"x-go-compat-constant-name"`   //nolint:tagliatelle // Fixed schema metadata key.
	CompatibilityType      string                `yaml:"x-go-compat-constant-type"`   //nolint:tagliatelle // Fixed schema metadata key.
	WireKeyName            string                `yaml:"x-go-wire-key-constant-name"` //nolint:tagliatelle // Fixed schema metadata key.
	CompatibilityConstants map[string]string     `yaml:"x-go-compat-constant-values"` //nolint:tagliatelle // Schema extension spelling is fixed.
	SDKGraphQLValues       map[string]string     `yaml:"x-go-sdk-graphql-values"`     //nolint:tagliatelle // Preserve the checked-in schema extension name.
	SDKType                string                `yaml:"x-go-sdk-constant-type"`      //nolint:tagliatelle // Schema extension spelling is fixed.
}

type generatedSet struct {
	Schema  string
	Output  string
	Config  string
	Command string
	Kind    string
}

type generatedModel struct {
	Name      string
	File      string
	Schema    string
	Generator string
	Fields    map[string]ast.Expr
	Type      ast.Expr
	Alias     bool
	Generated bool
}

type handwrittenModel struct {
	Path           string
	Name           string
	Classification string
	Reason         string
	Fields         []string
	Evidence       []string
}

type handwrittenManifest struct {
	Types []handwrittenAllowance `yaml:"types"`
}

type handwrittenAllowance struct {
	File           string   `yaml:"file"`
	Name           string   `yaml:"name"`
	Classification string   `yaml:"classification"`
	Reason         string   `yaml:"reason"`
	Evidence       []string `yaml:"evidence"`
}

type inventoryRow struct {
	Schema     string
	Component  string
	GoType     string
	Definition string
	Generator  string
	CallSites  []string
}

type inventoryDiagnosticError struct{}

func (inventoryDiagnosticError) Error() string {
	return "model inventory diagnostic"
}

func generatedSets() []generatedSet {
	return append(openAPIGeneratedSets(), asyncAPIGeneratedSets()...)
}

func openAPIGeneratedSets() []generatedSet {
	return []generatedSet{
		openAPISet("pkg/dependencymodels/account_linking.gen.go", "pkg/dependencymodels/account-linking.config.yaml"),
		openAPISet("pkg/dependencymodels/endpoints.gen.go", "pkg/dependencymodels/endpoints.config.yaml"),
		openAPISet("pkg/dependencymodels/devices_v2.gen.go", "pkg/dependencymodels/devices-v2.config.yaml"),
		openAPISet("pkg/dependencymodels/user_info.gen.go", "pkg/dependencymodels/user-info.config.yaml"),
		openAPISet("pkg/dependencymodels/behaviors_api.gen.go", "pkg/dependencymodels/behaviors.config.yaml"),
		openAPISet("pkg/dependencymodels/graphql_transport.gen.go", "pkg/dependencymodels/graphql-transport.config.yaml"),
		openAPISet("pkg/dependencymodels/media.gen.go", "pkg/dependencymodels/media.config.yaml"),
		compatibilitySet("api/compat/auth.yaml", "pkg/dependencymodels/auth_compat.gen.go", "pkg/dependencymodels/auth-compat.config.yaml", false),
		compatibilitySet("api/compat/endpoints.yaml", "pkg/dependencymodels/endpoints_compat.gen.go", "pkg/dependencymodels/endpoints-compat.config.yaml", false),
		compatibilitySet("api/compat/devices.yaml", "pkg/dependencymodels/devices_compat.gen.go", "pkg/dependencymodels/devices-compat.config.yaml", false),
		compatibilitySet("api/compat/user-info.yaml", "pkg/dependencymodels/user_info_compat.gen.go", "pkg/dependencymodels/user-info-compat.config.yaml", false),
		compatibilitySet("api/compat/behaviors.yaml", "pkg/dependencymodels/behaviors_compat.gen.go", "pkg/dependencymodels/behaviors-compat.config.yaml", false),
		compatibilitySet("api/compat/controls.yaml", "pkg/dependencymodels/controls_compat.gen.go", "pkg/dependencymodels/controls-compat.config.yaml", true),
		compatibilitySet("api/compat/media.yaml", "pkg/dependencymodels/media_compat.gen.go", "pkg/dependencymodels/media-compat.config.yaml", false),
		compatibilitySet("api/compat/events.yaml", "pkg/dependencymodels/events_compat.gen.go", "pkg/dependencymodels/events-compat.config.yaml", false),
		payloadSet("api/behaviors.yaml", "pkg/dependencymodels/behavior_sequence.gen.go", "pkg/dependencymodels/behavior-sequence.config.yaml"),
		payloadSet("api/feature-events.yaml", "pkg/dependencymodels/feature_events.gen.go", "pkg/dependencymodels/feature-events.config.yaml"),
		payloadSet("api/feature-controls.yaml", "pkg/dependencymodels/feature_controls.gen.go", "pkg/dependencymodels/feature-controls.config.yaml"),
	}
}

func asyncAPIGeneratedSets() []generatedSet {
	return []generatedSet{
		asyncAPISet("pkg/dependencymodels/asyncapi_directive.gen.go"),
		asyncAPISet("pkg/dependencymodels/asyncapi_directive_header.gen.go"),
		asyncAPISet("pkg/dependencymodels/asyncapi_directive_message.gen.go"),
		asyncAPISet("pkg/dependencymodels/asyncapi_directive_payload.gen.go"),
		asyncAPISet("pkg/dependencymodels/asyncapi_rendering_update.gen.go"),
	}
}

func openAPISet(output, config string) generatedSet {
	return generatedSet{Schema: openAPISchemaPath, Output: output, Config: config, Command: openAPIGenerator, Kind: "OpenAPI"}
}

func compatibilitySet(schema, output, config string, fixesAllOf bool) generatedSet {
	command := openAPIGenerator
	if fixesAllOf {
		command += "; go run ./tools/oapiallOfix"
	}

	return generatedSet{Schema: schema, Output: output, Config: config, Command: command, Kind: "compatibility projection"}
}

func payloadSet(schema, output, config string) generatedSet {
	return generatedSet{Schema: schema, Output: output, Config: config, Command: openAPIGenerator, Kind: "OpenAPI payload schema"}
}

func asyncAPISet(output string) generatedSet {
	return generatedSet{Schema: asyncAPISchemaPath, Output: output, Config: "tools/protocols/package.json", Command: asyncAPIGenerator, Kind: "AsyncAPI"}
}

func graphQLGeneratedSet() generatedSet {
	return generatedSet{Schema: graphQLSchemaPath, Output: graphQLOutputPath, Config: graphQLConfigPath, Command: graphQLGenerator, Kind: "GraphQL"}
}

func diagnosticf(format string, values ...any) error {
	message := fmt.Sprintf(format, values...)

	return fmt.Errorf("%w: %s", inventoryDiagnosticError{}, message)
}

func main() {
	write := flag.Bool("write", false, "write the generated inventory document")
	check := flag.Bool("check", false, "verify inventory document is current (default)")
	list := flag.Bool("list-handwritten", false, "print handwritten serialized structs for manifest review")
	flag.Parse()

	if *list {
		err := listHandwrittenModels()
		if err != nil {
			fatalf("%v", err)
		}

		return
	}

	if *write && *check {
		fatalf("choose either -write or -check")
	}

	err := run(*write)
	if err != nil {
		fatalf("%v", err)
	}
}

func run(write bool) error {
	models, err := readGeneratedModels()
	if err != nil {
		return err
	}

	err = checkGeneratedWireConstructions(models)
	if err != nil {
		return err
	}

	rows, err := checkSchemas(models)
	if err != nil {
		return err
	}

	err = checkBehaviorPayloadInventory()
	if err != nil {
		return err
	}

	primitiveRows, err := checkSDKPrimitiveInventory()
	if err != nil {
		return err
	}

	rows = append(rows, primitiveRows...)

	wireRows, err := checkWirePrimitiveInventory()
	if err != nil {
		return err
	}

	rows = append(rows, wireRows...)

	handwritten, err := scanHandwrittenModels()
	if err != nil {
		return err
	}

	rows = dedupeRows(rows)
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].Schema != rows[j].Schema {
			return rows[i].Schema < rows[j].Schema
		}

		return rows[i].GoType < rows[j].GoType
	})

	content := renderInventory(rows, handwritten)
	if write {
		err := os.WriteFile(inventoryPath, content, inventoryFileMode)
		if err != nil {
			return fmt.Errorf("write %s: %w", inventoryPath, err)
		}

		return nil
	}

	actual, err := os.ReadFile(inventoryPath)
	if err != nil {
		return fmt.Errorf("read %s: %w (run go run ./tools/modelinventory -write)", inventoryPath, err)
	}

	if !bytes.Equal(actual, content) {
		return diagnosticf("%s is stale; run go run ./tools/modelinventory -write", inventoryPath)
	}

	return nil
}

func listHandwrittenModels() error {
	err := filepath.WalkDir("pkg", listHandwrittenModelsAtPath)
	if err != nil {
		return fmt.Errorf("walk package sources while listing handwritten models: %w", err)
	}

	return nil
}

func listHandwrittenModelsAtPath(path string, entry os.DirEntry, walkErr error) error {
	if walkErr != nil {
		return fmt.Errorf("walk package source while listing handwritten models: %w", walkErr)
	}

	path = filepath.ToSlash(path)
	if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || isGeneratedFile(path) {
		return nil
	}

	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, path, mustRead(path), parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse %s: %w", path, err)
	}

	return listHandwrittenTypeDeclarations(path, file, customJSONMethods(file))
}

func listHandwrittenTypeDeclarations(path string, file *ast.File, methods map[string]bool) error {
	for _, declaration := range file.Decls {
		group, isTypeGroup := declaration.(*ast.GenDecl)
		if !isTypeGroup || group.Tok != token.TYPE {
			continue
		}

		err := listHandwrittenTypeGroup(path, group, methods)
		if err != nil {
			return err
		}
	}

	return nil
}

func listHandwrittenTypeGroup(path string, group *ast.GenDecl, methods map[string]bool) error {
	for _, spec := range group.Specs {
		typeSpec, isTypeSpec := spec.(*ast.TypeSpec)
		if !isTypeSpec {
			continue
		}

		structType, isStruct := typeSpec.Type.(*ast.StructType)
		if !isStruct || !hasHandwrittenJSONModel(structType, typeSpec.Name.Name, methods) {
			continue
		}

		classification, reason := modelMarker(group.Doc, typeSpec.Doc)

		_, err := fmt.Fprintf(
			os.Stdout,
			"%s|%s|%s|%s|%s\n",
			path,
			typeSpec.Name.Name,
			classification,
			reason,
			strings.Join(jsonTaggedFields(structType), ","),
		)
		if err != nil {
			return fmt.Errorf("write handwritten model listing: %w", err)
		}
	}

	return nil
}

func hasHandwrittenJSONModel(structType *ast.StructType, name string, methods map[string]bool) bool {
	return len(jsonTaggedFields(structType)) > 0 || methods[name] || hasAnonymousNestedJSON(structType)
}

func readGeneratedModels() (map[string]generatedModel, error) {
	models := make(map[string]generatedModel)

	sets := generatedSets()

	sets = append(sets, graphQLGeneratedSet())
	for _, set := range sets {
		file, err := parser.ParseFile(token.NewFileSet(), set.Output, mustRead(set.Output), parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse generated models %s: %w", set.Output, err)
		}

		if !isGeneratedFile(set.Output) {
			return nil, diagnosticf("%s lacks a generated-file marker", set.Output)
		}

		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				model := generatedModel{
					Name: typeSpec.Name.Name, File: set.Output, Schema: set.Schema,
					Generator: generatorDescription(set), Fields: nil, Type: typeSpec.Type,
					Alias: typeSpec.Assign.IsValid(), Generated: true,
				}
				if structType, ok := typeSpec.Type.(*ast.StructType); ok {
					model.Fields = structFields(structType)
				}

				if previous, exists := models[model.Name]; exists && previous.File != model.File {
					return nil, diagnosticf("generated Go model %s is declared in both %s and %s", model.Name, previous.File, model.File)
				}

				models[model.Name] = model
			}
		}
	}

	return models, nil
}

func registeredGeneratedFiles() map[string]bool {
	files := make(map[string]bool)
	for _, set := range generatedSets() {
		files[filepath.ToSlash(set.Output)] = true
	}

	files[filepath.ToSlash(graphQLGeneratedSet().Output)] = true
	files[sdkPrimitiveOutput] = true

	return files
}

type schemaInventory struct {
	models         map[string]generatedModel
	componentModel map[string]bool
	usedModels     map[string]bool
	rows           []inventoryRow
}

func checkSchemas(models map[string]generatedModel) ([]inventoryRow, error) {
	inventory := schemaInventory{
		models:         models,
		componentModel: make(map[string]bool),
		usedModels:     make(map[string]bool),
		rows:           make([]inventoryRow, 0),
	}

	err := inventory.checkDocuments(generatedSets())
	if err != nil {
		return nil, err
	}

	generatedRows, err := generatedModelRows(models, inventory.usedModels, inventory.componentModel)
	if err != nil {
		return nil, err
	}

	inventory.rows = append(inventory.rows, generatedRows...)

	return inventory.rows, nil
}

func (inventory *schemaInventory) checkDocuments(sets []generatedSet) error {
	seenDocuments := make(map[string]bool)

	for _, set := range sets {
		if seenDocuments[set.Schema] || strings.Contains(set.Schema, " plus operation documents ") {
			continue
		}

		seenDocuments[set.Schema] = true

		document, err := readSchemaDocument(set.Schema)
		if err != nil {
			return err
		}

		err = inventory.checkDocument(set, document)
		if err != nil {
			return err
		}
	}

	return nil
}

func readSchemaDocument(path string) (schemaDocument, error) {
	data, err := fs.ReadFile(os.DirFS("."), filepath.ToSlash(path))
	if err != nil {
		return schemaDocument{}, fmt.Errorf("read schema %s: %w", path, err)
	}

	var document schemaDocument

	err = yaml.Unmarshal(data, &document)
	if err != nil {
		return schemaDocument{}, fmt.Errorf("parse schema %s: %w", path, err)
	}

	return document, nil
}

func (inventory *schemaInventory) checkDocument(set generatedSet, document schemaDocument) error {
	err := inventory.checkSchemaComponents(set, document)
	if err != nil {
		return err
	}

	err = inventory.checkParameterComponents(set, document)
	if err != nil {
		return err
	}

	return inventory.checkOperations(set, document)
}

func (inventory *schemaInventory) checkSchemaComponents(set generatedSet, document schemaDocument) error {
	for componentName, schema := range document.Components.Schemas {
		goName := schema.GoTypeName
		if goName == "" {
			goName = componentName
		}

		model, exists := inventory.models[goName]
		if !exists {
			return diagnosticf("schema %s component %s has no generated Go definition for %s", set.Schema, componentName, goName)
		}

		inventory.componentModel[goName] = true

		inventory.usedModels[goName] = true

		if len(schema.Properties) > 0 {
			err := compareSchemaTypeTracked(
				schema, model.Type, model.Name, set.Schema, inventory.models,
				document.Components.Schemas, map[string]bool{}, inventory.usedModels,
			)
			if err != nil {
				return err
			}
		}

		inventory.rows = append(inventory.rows, inventoryRow{
			Schema: set.Schema, Component: componentName, GoType: goName, Definition: model.File,
			Generator: generatorDescription(set), CallSites: findCallSites(goName, model.File),
		})
	}

	return nil
}

func (inventory *schemaInventory) checkParameterComponents(set generatedSet, document schemaDocument) error {
	for parameterName, parameter := range document.Components.Parameters {
		goName := exportParameterField(parameter.Name)

		model, exists := inventory.models[goName]

		if !exists {
			return diagnosticf("schema %s parameter component %s has no generated Go definition for %s", set.Schema, parameterName, goName)
		}

		if !model.Alias {
			return diagnosticf("schema %s parameter component %s generated %s is not a type alias", set.Schema, parameterName, goName)
		}

		err := compareParameterSchema(parameter.Schema, model.Type, model.Name, set.Schema, inventory.models, document.Components.Schemas, inventory.usedModels)
		if err != nil {
			return fmt.Errorf("schema %s parameter component %s: %w", set.Schema, parameterName, err)
		}

		inventory.componentModel[goName] = true
		inventory.usedModels[goName] = true
		inventory.rows = append(inventory.rows, inventoryRow{
			Schema: set.Schema, Component: fmt.Sprintf("parameter component %s (%s)", parameterName, parameter.In),
			GoType: goName, Definition: model.File, Generator: model.Generator,
			CallSites: findCallSites(goName, model.File),
		})
	}

	return nil
}

func (inventory *schemaInventory) checkOperations(set generatedSet, document schemaDocument) error {
	for path, item := range document.Paths {
		for _, current := range operationsForPath(item) {
			if current.operation == nil || current.operation.OperationID == "" {
				continue
			}

			err := inventory.checkOperation(set, document, path, current, item.Parameters)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

func (inventory *schemaInventory) checkOperation(
	set generatedSet,
	document schemaDocument,
	path string,
	current operationMethod,
	pathParameters []parameterNode,
) error {
	parameters, err := resolveOperationParameters(pathParameters, current.operation.Parameters, document.Components.Parameters)
	if err != nil {
		return fmt.Errorf("schema %s operation %s %s: %w", set.Schema, current.method, path, err)
	}

	if len(parameters) == 0 {
		return nil
	}

	parameterFields, err := inventory.addOperationParameterRows(set, current, parameters)
	if err != nil || len(parameterFields) == 0 {
		return err
	}

	return inventory.checkOperationParameterModel(set, document, path, current, parameterFields)
}

func (inventory *schemaInventory) addOperationParameterRows(set generatedSet, current operationMethod, parameters []parameterNode) ([]parameterNode, error) {
	parameterFields := make([]parameterNode, 0, len(parameters))

	for _, parameter := range parameters {
		if parameter.ComponentName != "" {
			parameterType, exists := inventory.models[parameter.ComponentName]
			if !exists {
				return nil, diagnosticf(
					"schema %s operation %s references parameter %s without generated model %s",
					set.Schema, current.operation.OperationID, parameter.ComponentName, parameter.ComponentName,
				)
			}

			inventory.usedModels[parameter.ComponentName] = true
			inventory.rows = append(inventory.rows, inventoryRow{
				Schema:    set.Schema,
				Component: fmt.Sprintf("%s parameter %s (%s)", current.operation.OperationID, parameter.Name, parameter.In),
				GoType:    parameter.ComponentName, Definition: parameterType.File, Generator: parameterType.Generator,
				CallSites: findCallSites(parameter.ComponentName, parameterType.File),
			})
		}

		if parameter.In != "path" {
			parameterFields = append(parameterFields, parameter)

			continue
		}

		if parameter.ComponentName == "" {
			inventory.addInlinePathParameterRow(set, current, parameter)
		}
	}

	return parameterFields, nil
}

func (inventory *schemaInventory) addInlinePathParameterRow(set generatedSet, current operationMethod, parameter parameterNode) {
	inventory.rows = append(inventory.rows, inventoryRow{
		Schema:    set.Schema,
		Component: fmt.Sprintf("%s inline %s parameter %s (%s)", current.operation.OperationID, parameter.In, parameter.Name, strings.ToUpper(current.method)),
		GoType:    "schema-defined primitive parameter", Definition: set.Schema, Generator: generatorDescription(set),
		CallSites: nil,
	})
}

func (inventory *schemaInventory) checkOperationParameterModel(
	set generatedSet,
	document schemaDocument,
	path string,
	current operationMethod,
	parameters []parameterNode,
) error {
	goName := upperInitial(current.operation.OperationID) + "Params"

	model, exists := inventory.models[goName]

	if !exists {
		return diagnosticf("schema %s operation %s non-path parameters lack generated parameter model %s", set.Schema, current.operation.OperationID, goName)
	}

	structType, isStruct := unwrapGoType(model.Type).(*ast.StructType)
	if !isStruct {
		return diagnosticf("schema %s operation %s parameter model %s is not a struct", set.Schema, current.operation.OperationID, goName)
	}

	actualFields := structFields(structType)

	err := compareOperationParameterFields(set, current, goName, parameters, actualFields)
	if err != nil {
		return err
	}

	inventory.componentModel[goName] = true
	inventory.usedModels[goName] = true

	for _, parameter := range parameters {
		fieldType := actualFields[parameter.Name]
		fieldName := goName + "." + exportParameterField(parameter.Name)

		err := compareParameterSchema(parameter.Schema, fieldType, fieldName, set.Schema, inventory.models, document.Components.Schemas, inventory.usedModels)
		if err != nil {
			return fmt.Errorf("schema %s operation %s parameter %s: %w", set.Schema, current.operation.OperationID, parameter.Name, err)
		}

		markGeneratedTypeReferences(fieldType, inventory.models, inventory.usedModels)
		inventory.addOperationParameterFieldRow(set, current, model, goName, parameter)
	}

	inventory.rows = append(inventory.rows, inventoryRow{
		Schema:    set.Schema,
		Component: fmt.Sprintf("operation parameter model %s (%s %s)", current.operation.OperationID, strings.ToUpper(current.method), path),
		GoType:    goName, Definition: model.File, Generator: model.Generator,
		CallSites: findCallSites(goName, model.File),
	})

	return nil
}

func compareOperationParameterFields(
	set generatedSet,
	current operationMethod,
	goName string,
	parameters []parameterNode,
	actualFields map[string]ast.Expr,
) error {
	expectedFields := make([]string, 0, len(parameters))
	for _, parameter := range parameters {
		expectedFields = append(expectedFields, parameter.Name)
	}

	actual := make([]string, 0, len(actualFields))
	for name := range actualFields {
		actual = append(actual, name)
	}

	sort.Strings(expectedFields)
	sort.Strings(actual)

	if strings.Join(expectedFields, "\x00") != strings.Join(actual, "\x00") {
		return diagnosticf(
			"schema %s operation %s parameter fields differ from generated %s: schema=%v generated=%v",
			set.Schema, current.operation.OperationID, goName, expectedFields, actual,
		)
	}

	return nil
}

func (inventory *schemaInventory) addOperationParameterFieldRow(
	set generatedSet,
	current operationMethod,
	model generatedModel,
	goName string,
	parameter parameterNode,
) {
	inventory.rows = append(inventory.rows, inventoryRow{
		Schema:    set.Schema,
		Component: fmt.Sprintf("%s %s parameter %s (%s)", current.operation.OperationID, parameter.In, parameter.Name, current.method),
		GoType:    goName + "." + exportParameterField(parameter.Name), Definition: model.File,
		Generator: model.Generator, CallSites: findCallSites(goName, model.File),
	})
}

type operationMethod struct {
	method    string
	operation *operationNode
}

func operationsForPath(item pathItem) []operationMethod {
	return []operationMethod{
		{method: "get", operation: item.Get},
		{method: "post", operation: item.Post},
		{method: "put", operation: item.Put},
		{method: "patch", operation: item.Patch},
		{method: "delete", operation: item.Delete},
		{method: "head", operation: item.Head},
		{method: "options", operation: item.Options},
		{method: "trace", operation: item.Trace},
	}
}

func resolveOperationParameters(pathParameters, operationParameters []parameterNode, components map[string]parameterNode) ([]parameterNode, error) {
	var result []parameterNode

	seen := make(map[string]bool)

	for _, source := range [][]parameterNode{pathParameters, operationParameters} {
		for _, parameter := range source {
			if parameter.Ref != "" {
				name := strings.TrimPrefix(parameter.Ref, "#/components/parameters/")

				resolved, ok := components[name]
				if !ok {
					return nil, diagnosticf("parameter reference %s is not defined in components", parameter.Ref)
				}

				parameter.ComponentName = name
				parameter = resolved
				parameter.ComponentName = name
			}

			if parameter.Name == "" || parameter.In == "" {
				return nil, diagnosticf("parameter has no name or location")
			}

			key := parameter.In + "\x00" + parameter.Name
			if seen[key] {
				continue
			}

			seen[key] = true

			result = append(result, parameter)
		}
	}

	return result, nil
}

func markGeneratedTypeReferences(expression ast.Expr, models map[string]generatedModel, used map[string]bool) {
	ast.Inspect(expression, func(node ast.Node) bool {
		identifier, ok := node.(*ast.Ident)
		if ok {
			if _, exists := models[identifier.Name]; exists {
				used[identifier.Name] = true
			}
		}

		return true
	})
}

func exportParameterField(name string) string {
	parts := strings.FieldsFunc(name, func(character rune) bool {
		return character == '-' || character == '_' || character == '.'
	})
	if len(parts) == 0 {
		return upperInitial(name)
	}

	for index := range parts {
		parts[index] = upperInitial(parts[index])
	}

	return strings.Join(parts, "")
}

func compareParameterSchema(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	usedModels map[string]bool,
) error {
	if schema.GoType != "" {
		return compareExplicitGoType(schema.GoType, goType, typeName)
	}

	if parameterSchemaIsEmpty(schema) {
		return nil
	}

	actual := resolveParameterType(goType, typeName, models, usedModels)

	if schema.Ref != "" {
		return markReferencedParameterModel(schema.Ref, models, usedModels)
	}

	if schema.Type == "array" {
		return compareArrayParameter(schema, actual, typeName, schemaPath, models, schemas, usedModels)
	}

	if schema.Type == "object" {
		return compareObjectParameter(schema, goType, actual, typeName, schemaPath, models, schemas, usedModels)
	}

	return comparePrimitiveParameter(schema, actual, typeName)
}

func compareExplicitGoType(expectedType string, goType ast.Expr, typeName string) error {
	expected, err := parser.ParseExpr(expectedType)
	if err != nil {
		return diagnosticf("schema x-go-type %q is not a Go expression", expectedType)
	}

	var expectedText, actualText bytes.Buffer

	err = format.Node(&expectedText, token.NewFileSet(), expected)
	if err != nil {
		return fmt.Errorf("format schema x-go-type %q: %w", expectedType, err)
	}

	err = format.Node(&actualText, token.NewFileSet(), unwrapGoType(goType))
	if err != nil {
		return fmt.Errorf("format generated type for %s: %w", typeName, err)
	}

	if expectedText.String() != actualText.String() {
		return diagnosticf("schema x-go-type %s does not match generated %s (%s)", expectedText.String(), typeName, actualText.String())
	}

	return nil
}

func parameterSchemaIsEmpty(schema schemaNode) bool {
	return schema.Type == "" && schema.Ref == "" && schema.Items == nil && len(schema.Properties) == 0 && len(schema.AllOf) == 0
}

func resolveParameterType(goType ast.Expr, typeName string, models map[string]generatedModel, usedModels map[string]bool) ast.Expr {
	actual := unwrapGoType(goType)

	identifier, isIdentifier := actual.(*ast.Ident)

	if !isIdentifier || identifier.Name == typeName {
		return actual
	}

	model, exists := models[identifier.Name]
	if !exists {
		return actual
	}

	if usedModels != nil {
		usedModels[identifier.Name] = true
	}

	return unwrapGoType(model.Type)
}

func markReferencedParameterModel(reference string, models map[string]generatedModel, usedModels map[string]bool) error {
	name := strings.TrimPrefix(reference, "#/components/schemas/")

	_, exists := models[name]

	if !exists {
		name = strings.TrimPrefix(reference, "#/components/parameters/")
		_, exists = models[name]
	}

	if !exists {
		return diagnosticf("reference %s has no generated model", reference)
	}

	if usedModels != nil {
		usedModels[name] = true
	}

	return nil
}

func compareArrayParameter(
	schema schemaNode,
	actual ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	usedModels map[string]bool,
) error {
	array, isArray := actual.(*ast.ArrayType)
	if !isArray || schema.Items == nil {
		return diagnosticf("schema array does not match generated %s", typeName)
	}

	return compareParameterSchema(*schema.Items, array.Elt, typeName+"[]", schemaPath, models, schemas, usedModels)
}

func compareObjectParameter(
	schema schemaNode,
	goType, actual ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	usedModels map[string]bool,
) error {
	if len(schema.Properties) > 0 || len(schema.AllOf) > 0 {
		return compareSchemaTypeTracked(schema, goType, typeName, schemaPath, models, schemas, map[string]bool{}, usedModels)
	}

	if !schemaAllowsAdditionalProperties(schema.AdditionalProperties) {
		return nil
	}

	if _, isMap := actual.(*ast.MapType); !isMap {
		return diagnosticf("schema object allows additional properties but generated %s is not a map", typeName)
	}

	return nil
}

func comparePrimitiveParameter(schema schemaNode, actual ast.Expr, typeName string) error {
	if schema.Type == schemaStringType && isTimeFormat(schema.Format) {
		if isTimeType(actual) {
			return nil
		}

		return diagnosticf("schema string format %s does not match generated %s", schema.Format, typeName)
	}

	identifier, isIdentifier := actual.(*ast.Ident)
	if !isIdentifier {
		return diagnosticf("schema type %s does not match generated %s (%T)", schema.Type, typeName, actual)
	}

	valid, supported := primitiveGoTypeMatches(schema.Type, schema.Format, identifier.Name)
	if !supported {
		return diagnosticf("unsupported parameter schema type %q for %s", schema.Type, typeName)
	}

	if !valid {
		return diagnosticf("schema type %s does not match generated %s (%s)", schema.Type, typeName, identifier.Name)
	}

	return nil
}

func isTimeFormat(format string) bool {
	return format == "date" || format == "date-time"
}

func isTimeType(actual ast.Expr) bool {
	selector, isSelector := actual.(*ast.SelectorExpr)
	if !isSelector || selector.Sel.Name != "Time" {
		return false
	}

	packageName, isIdentifier := selector.X.(*ast.Ident)

	return isIdentifier && packageName.Name == "time"
}

func primitiveGoTypeMatches(schemaType, format, goType string) (bool, bool) {
	switch schemaType {
	case "string":
		return goType == "string", true
	case "boolean":
		return goType == "bool", true
	case "integer":
		return integerGoTypeMatches(format, goType), true
	case "number":
		return goType == "float32" || goType == "float64", true
	case "":
		return true, true
	default:
		return false, false
	}
}

func integerGoTypeMatches(format, goType string) bool {
	if format == goInt32Type {
		return goType == goInt32Type || goType == goIntType
	}

	if format == goInt64Type {
		return goType == goInt64Type || goType == goIntType
	}

	switch goType {
	case "int", "int8", "int16", "int32", "int64":
		return true
	default:
		return false
	}
}

func upperInitial(value string) string {
	if value == "" {
		return value
	}

	return strings.ToUpper(value[:1]) + value[1:]
}

func generatedModelRows(models map[string]generatedModel, usedModels, componentModels map[string]bool) ([]inventoryRow, error) {
	var rows []inventoryRow

	for name, model := range models {
		if model.File == graphQLGeneratedSet().Output {
			rows = append(rows, inventoryRow{
				Schema: model.Schema, Component: "operation-derived GraphQL model", GoType: name,
				Definition: model.File, Generator: model.Generator, CallSites: findCallSites(name, model.File),
			})

			continue
		}

		if componentModels[name] {
			continue
		}

		if usedModels[name] {
			rows = append(rows, inventoryRow{
				Schema: model.Schema, Component: "schema-referenced inline child", GoType: name,
				Definition: model.File, Generator: model.Generator, CallSites: findCallSites(name, model.File),
			})

			continue
		}

		if model.Alias && generatedAliasTargetIsRegistered(model, models, usedModels) {
			rows = append(rows, inventoryRow{
				Schema: model.Schema, Component: "generated operation alias to a schema model", GoType: name,
				Definition: model.File, Generator: model.Generator, CallSites: findCallSites(name, model.File),
			})

			continue
		}

		return nil, diagnosticf(
			"generated model %s in %s is not a schema component, schema-referenced inline child, or alias to a registered schema model",
			name, model.File,
		)
	}

	return rows, nil
}

func compareSchemaType(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting map[string]bool,
) error {
	return compareSchemaTypeTracked(schema, goType, typeName, schemaPath, models, schemas, visiting, nil)
}

func compareSchemaTypeTracked(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	if schema.Ref != "" {
		return compareSchemaReference(schema.Ref, schemaPath, models, schemas, visiting, usedModels)
	}

	if schema.Items != nil {
		return compareSchemaArray(*schema.Items, goType, typeName, schemaPath, models, schemas, visiting, usedModels)
	}

	if model, isAlias := generatedAliasFor(goType, typeName, models, usedModels); isAlias {
		return compareSchemaTypeTracked(schema, model.Type, typeName, schemaPath, models, schemas, visiting, usedModels)
	}

	properties, err := flattenedProperties(schema, schemas, make(map[string]bool))
	if err != nil {
		return fmt.Errorf("schema %s component %s: %w", schemaPath, typeName, err)
	}

	return compareSchemaProperties(schema, goType, typeName, schemaPath, properties, models, schemas, visiting, usedModels)
}

func compareSchemaReference(
	reference, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	refName := strings.TrimPrefix(reference, "#/components/schemas/")

	refSchema, exists := schemas[refName]
	if !exists {
		return nil // External references are declared in another checked-in schema.
	}

	refTypeName := refSchema.GoTypeName
	if refTypeName == "" {
		refTypeName = refName
	}

	if visiting[refTypeName] {
		return nil
	}

	model, exists := models[refTypeName]
	if !exists {
		return diagnosticf("schema %s reference %s has no generated Go model", schemaPath, refName)
	}

	if usedModels != nil {
		usedModels[refTypeName] = true
	}

	visiting[refTypeName] = true
	defer delete(visiting, refTypeName)

	return compareSchemaTypeTracked(refSchema, model.Type, refTypeName, schemaPath, models, schemas, visiting, usedModels)
}

func compareSchemaArray(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	arrayType, isArray := unwrapGoType(goType).(*ast.ArrayType)
	if !isArray {
		return nil
	}

	return compareSchemaTypeTracked(schema, arrayType.Elt, typeName+"[]", schemaPath, models, schemas, visiting, usedModels)
}

func generatedAliasFor(goType ast.Expr, typeName string, models map[string]generatedModel, usedModels map[string]bool) (generatedModel, bool) {
	identifier, isIdentifier := unwrapGoType(goType).(*ast.Ident)
	if !isIdentifier || identifier.Name == typeName {
		return emptyGeneratedModel(), false
	}

	model, exists := models[identifier.Name]
	if !exists {
		return emptyGeneratedModel(), false
	}

	if usedModels != nil {
		usedModels[identifier.Name] = true
	}

	return model, true
}

func emptyGeneratedModel() generatedModel {
	return generatedModel{
		Name: "", File: "", Schema: "", Generator: "", Fields: nil, Type: nil,
		Alias: false, Generated: false,
	}
}

func compareSchemaProperties(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	properties map[string]schemaNode,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	if len(properties) == 0 {
		return compareSchemaAdditionalProperties(schema, goType, typeName, schemaPath, models, schemas, visiting, usedModels)
	}

	structType, isStruct := unwrapGoType(goType).(*ast.StructType)
	if !isStruct {
		return diagnosticf("schema %s component %s has properties but generated type %s is not a struct", schemaPath, typeName, typeName)
	}

	return compareGeneratedSchemaFields(properties, structType, typeName, schemaPath, models, schemas, visiting, usedModels)
}

func compareSchemaAdditionalProperties(
	schema schemaNode,
	goType ast.Expr,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	if schema.Type != "object" || !schemaAllowsAdditionalProperties(schema.AdditionalProperties) {
		return nil
	}

	mapType, isMap := unwrapGoType(goType).(*ast.MapType)
	if !isMap {
		return diagnosticf("schema %s component %s allows additional properties but generated %s is not a map", schemaPath, typeName, typeName)
	}

	additionalSchema, hasSchema := additionalPropertiesSchema(schema.AdditionalProperties)
	if !hasSchema {
		return nil
	}

	return compareSchemaTypeTracked(additionalSchema, mapType.Value, typeName+"[*]", schemaPath, models, schemas, visiting, usedModels)
}

func compareGeneratedSchemaFields(
	properties map[string]schemaNode,
	structType *ast.StructType,
	typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	actualFields, err := structFieldsWithEmbedded(structType, models, make(map[string]bool))
	if err != nil {
		return fmt.Errorf("generated %s fields: %w", typeName, err)
	}

	expectedFields := schemaPropertyNames(properties)

	actualNames := expressionMapKeys(actualFields)

	if !equalStringSlices(expectedFields, actualNames) {
		return diagnosticf(
			"schema %s component %s fields differ from generated %s: schema=%v generated=%v",
			schemaPath, typeName, typeName, expectedFields, actualNames,
		)
	}

	for propertyName, propertySchema := range properties {
		fieldType := actualFields[propertyName]
		if fieldType == nil {
			continue
		}

		markGeneratedTypeReferences(fieldType, models, usedModels)

		err := compareSchemaProperty(propertySchema, fieldType, propertyName, typeName, schemaPath, models, schemas, visiting, usedModels)
		if err != nil {
			return err
		}
	}

	return nil
}

func schemaPropertyNames(properties map[string]schemaNode) []string {
	names := make([]string, 0, len(properties))

	for name := range properties {
		if name != "-" {
			names = append(names, name)
		}
	}

	sort.Strings(names)

	return names
}

func expressionMapKeys(expressions map[string]ast.Expr) []string {
	keys := make([]string, 0, len(expressions))
	for key := range expressions {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	return keys
}

func equalStringSlices(left, right []string) bool {
	return strings.Join(left, "\x00") == strings.Join(right, "\x00")
}

func compareSchemaProperty(
	propertySchema schemaNode,
	fieldType ast.Expr,
	propertyName, typeName, schemaPath string,
	models map[string]generatedModel,
	schemas map[string]schemaNode,
	visiting, usedModels map[string]bool,
) error {
	fieldName := typeName + "." + propertyName

	switch {
	case propertySchema.Ref != "":
		refName := strings.TrimPrefix(propertySchema.Ref, "#/components/schemas/")

		refSchema, exists := schemas[refName]
		if !exists || len(refSchema.Properties) == 0 && refSchema.Ref == "" {
			return nil
		}

		return compareSchemaTypeTracked(propertySchema, fieldType, fieldName, schemaPath, models, schemas, visiting, usedModels)
	case len(propertySchema.Properties) > 0:
		return compareSchemaTypeTracked(propertySchema, fieldType, fieldName, schemaPath, models, schemas, visiting, usedModels)
	case propertySchema.Type != "" || propertySchema.Items != nil:
		return compareParameterSchema(propertySchema, fieldType, fieldName, schemaPath, models, schemas, usedModels)
	default:
		return nil
	}
}

func flattenedProperties(schema schemaNode, schemas map[string]schemaNode, visiting map[string]bool) (map[string]schemaNode, error) {
	properties := make(map[string]schemaNode, len(schema.Properties))

	for name, property := range schema.Properties {
		if name != "-" {
			properties[name] = property
		}
	}

	for _, part := range schema.AllOf {
		partProperties, err := flattenedAllOfPart(part, schemas, visiting)
		if err != nil {
			return nil, err
		}

		err = mergeAllOfProperties(properties, partProperties)
		if err != nil {
			return nil, err
		}
	}

	return properties, nil
}

func flattenedAllOfPart(part schemaNode, schemas map[string]schemaNode, visiting map[string]bool) (map[string]schemaNode, error) {
	if part.Ref == "" {
		return flattenedProperties(part, schemas, visiting)
	}

	refName := strings.TrimPrefix(part.Ref, "#/components/schemas/")
	if visiting[refName] {
		return map[string]schemaNode{}, nil
	}

	refSchema, exists := schemas[refName]
	if !exists {
		return nil, diagnosticf("allOf reference %s is not in the checked-in schema document", refName)
	}

	visiting[refName] = true
	defer delete(visiting, refName)

	return flattenedProperties(refSchema, schemas, visiting)
}

func mergeAllOfProperties(properties, added map[string]schemaNode) error {
	for name, property := range added {
		if _, exists := properties[name]; exists {
			return diagnosticf("allOf defines duplicate property %q", name)
		}

		properties[name] = property
	}

	return nil
}

func schemaAllowsAdditionalProperties(value any) bool {
	switch typed := value.(type) {
	case nil:
		return false
	case bool:
		return typed
	case map[interface{}]interface{}, map[string]interface{}, schemaNode:
		return true
	default:
		return false
	}
}

func additionalPropertiesSchema(value any) (schemaNode, bool) {
	switch typed := value.(type) {
	case schemaNode:
		return typed, true
	case map[interface{}]interface{}:
		data, err := yaml.Marshal(typed)
		if err != nil {
			return emptySchemaNode(), false
		}

		var schema schemaNode
		if yaml.Unmarshal(data, &schema) != nil {
			return emptySchemaNode(), false
		}

		return schema, true
	case map[string]interface{}:
		data, err := yaml.Marshal(typed)
		if err != nil {
			return emptySchemaNode(), false
		}

		var schema schemaNode
		if yaml.Unmarshal(data, &schema) != nil {
			return emptySchemaNode(), false
		}

		return schema, true
	default:
		return emptySchemaNode(), false
	}
}

func emptySchemaNode() schemaNode {
	return schemaNode{
		GraphQLEnum: "", GraphQLJSONField: "", ExtensibleEnum: nil,
		Default: "", CompatibilityNames: nil, CompatibilityName: "", CompatibilityType: "", WireKeyName: "",
		CompatibilityConstants: nil, SDKGraphQLValues: nil, SDKType: "",
		Ref: "", Type: "", Format: "", GoName: "", GoTypeName: "", GoType: "",
		Properties: nil, Items: nil, AdditionalProperties: nil, AllOf: nil, Enum: nil, OneOf: nil, AnyOf: nil,
	}
}

func structFields(structType *ast.StructType) map[string]ast.Expr {
	fields := make(map[string]ast.Expr)

	for _, field := range structType.Fields.List {
		jsonName := jsonFieldName(field)
		if jsonName == "-" {
			continue
		}

		if len(field.Names) == 0 {
			if jsonName != "" {
				fields[jsonName] = field.Type
			}

			continue
		}

		for _, name := range field.Names {
			key := jsonName
			if key == "" {
				key = lowerInitial(name.Name)
			}

			fields[key] = field.Type
		}
	}

	return fields
}

func jsonFieldName(field *ast.Field) string {
	if field.Tag == nil {
		return ""
	}

	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return ""
	}

	jsonName := ""

	for _, item := range strings.Split(tag, " ") {
		if !strings.HasPrefix(item, "json:") {
			continue
		}

		jsonTag, err := strconv.Unquote(strings.TrimPrefix(item, "json:"))
		if err == nil {
			jsonName = strings.Split(jsonTag, ",")[0]
		}
	}

	return jsonName
}

// structFieldsWithEmbedded resolves generated embedded parents after the
// allOf compatibility pass restores the public Go composition shape. OpenAPI
// still requires every promoted field to be compared with its schema property.
func structFieldsWithEmbedded(structType *ast.StructType, models map[string]generatedModel, visiting map[string]bool) (map[string]ast.Expr, error) {
	fields := make(map[string]ast.Expr)

	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			err := addEmbeddedStructFields(fields, field.Type, models, visiting)
			if err != nil {
				return nil, err
			}

			continue
		}

		err := addNamedStructFields(fields, field)
		if err != nil {
			return nil, err
		}
	}

	return fields, nil
}

func addEmbeddedStructFields(fields map[string]ast.Expr, embedded ast.Expr, models map[string]generatedModel, visiting map[string]bool) error {
	name := embeddedTypeName(embedded)
	if name == "" {
		return nil
	}

	model, exists := models[name]
	if !exists {
		return nil
	}

	if visiting[name] {
		return diagnosticf("embedded generated model cycle at %s", name)
	}

	parent, isStruct := unwrapGoType(model.Type).(*ast.StructType)
	if !isStruct {
		return diagnosticf("embedded generated model %s is not a struct", name)
	}

	visiting[name] = true
	parentFields, err := structFieldsWithEmbedded(parent, models, visiting)
	delete(visiting, name)

	if err != nil {
		return err
	}

	for property, fieldType := range parentFields {
		if _, exists := fields[property]; exists {
			return diagnosticf("embedded generated model %s duplicates field %q", name, property)
		}

		fields[property] = fieldType
	}

	return nil
}

func addNamedStructFields(fields map[string]ast.Expr, field *ast.Field) error {
	jsonName := jsonFieldName(field)
	if jsonName == "-" {
		return nil
	}

	for _, name := range field.Names {
		property := jsonName
		if property == "" {
			property = lowerInitial(name.Name)
		}

		if _, exists := fields[property]; exists {
			return diagnosticf("generated struct defines duplicate JSON field %q", property)
		}

		fields[property] = field.Type
	}

	return nil
}

func embeddedTypeName(expression ast.Expr) string {
	switch typed := unwrapGoType(expression).(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.SelectorExpr:
		return typed.Sel.Name
	default:
		return ""
	}
}

func unwrapGoType(expr ast.Expr) ast.Expr {
	for {
		switch value := expr.(type) {
		case *ast.StarExpr:
			expr = value.X
		case *ast.ParenExpr:
			expr = value.X
		default:
			return expr
		}
	}
}

func lowerInitial(value string) string {
	if value == "" {
		return value
	}

	return strings.ToLower(value[:1]) + value[1:]
}

func generatedAliasTargetIsRegistered(model generatedModel, models map[string]generatedModel, usedModels map[string]bool) bool {
	target, ok := model.Type.(*ast.Ident)
	if !ok || !usedModels[target.Name] {
		return false
	}

	_, exists := models[target.Name]

	return exists
}

func scanHandwrittenModels() ([]handwrittenModel, error) {
	manifestData, err := os.ReadFile(handwrittenManifestPath)
	if err != nil {
		return nil, fmt.Errorf("read handwritten model manifest: %w", err)
	}

	var manifest handwrittenManifest

	err = yaml.Unmarshal(manifestData, &manifest)
	if err != nil {
		return nil, fmt.Errorf("parse handwritten model manifest: %w", err)
	}

	allowances := make(map[string]handwrittenAllowance, len(manifest.Types))

	for _, allowance := range manifest.Types {
		key := allowance.File + "::" + allowance.Name
		if _, exists := allowances[key]; exists {
			return nil, diagnosticf("duplicate handwritten model manifest entry %s", key)
		}

		allowances[key] = allowance
	}

	files := []string{}

	err = filepath.WalkDir("pkg", func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("walk package sources: %w", err)
		}

		if entry.IsDir() {
			return nil
		}

		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			files = append(files, filepath.ToSlash(path))
		}

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk package sources: %w", err)
	}

	var (
		result   []handwrittenModel
		problems []string
	)

	seen := make(map[string]bool)

	registered := registeredGeneratedFiles()
	for _, path := range files {
		if registered[path] {
			continue
		}

		data, err := os.ReadFile(filepath.FromSlash(path))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}

		fset := token.NewFileSet()
		fileModels, fileProblems, fileSeen := scanHandwrittenSource(path, data, fset, isGeneratedFile(path), allowances)
		result = append(result, fileModels...)
		problems = append(problems, fileProblems...)

		for key := range fileSeen {
			seen[key] = true
		}
	}

	for key := range allowances {
		if !seen[key] {
			problems = append(problems, "stale handwritten model manifest entry "+key)
		}
	}

	if len(problems) > 0 {
		sort.Strings(problems)

		return nil, diagnosticf("handwritten model inventory gate failed:\n  %s", strings.Join(problems, "\n  "))
	}

	sort.Slice(result, func(i, j int) bool {
		if result[i].Path != result[j].Path {
			return result[i].Path < result[j].Path
		}

		return result[i].Name < result[j].Name
	})

	return result, nil
}

func scanHandwrittenSource(
	path string,
	data []byte,
	fset *token.FileSet,
	generated bool,
	allowances map[string]handwrittenAllowance,
) ([]handwrittenModel, []string, map[string]bool) {
	file, err := parser.ParseFile(fset, path, data, parser.ParseComments)
	if err != nil {
		return nil, []string{fmt.Sprintf("parse %s: %v", path, err)}, nil
	}

	scan := handwrittenSourceScan{
		path:          path,
		fset:          fset,
		file:          file,
		generated:     generated,
		allowances:    allowances,
		methods:       customJSONMethods(file),
		jsonTypes:     nil,
		jsonAnonymous: nil,
		declarations:  make(map[*ast.StructType]modelDeclaration),
		models:        make([]handwrittenModel, 0),
		problems:      make([]string, 0),
		seen:          make(map[string]bool),
	}
	scan.jsonTypes, scan.jsonAnonymous = jsonCodecStructs(file)
	scan.collectTypeDeclarations()
	scan.reportNestedAnonymousJSON()

	ast.Inspect(file, func(node ast.Node) bool {
		structType, isStruct := node.(*ast.StructType)
		if isStruct {
			scan.inspectStruct(structType)
		}

		return true
	})

	if scan.generated && scan.hasTaggedGeneratedTypes() {
		return nil, scan.problems, scan.seen
	}

	scan.includeCustomJSONTypes()

	return scan.models, scan.problems, scan.seen
}

type handwrittenSourceScan struct {
	path          string
	fset          *token.FileSet
	file          *ast.File
	generated     bool
	allowances    map[string]handwrittenAllowance
	methods       map[string]bool
	jsonTypes     map[string]bool
	jsonAnonymous map[*ast.StructType]bool
	declarations  map[*ast.StructType]modelDeclaration
	models        []handwrittenModel
	problems      []string
	seen          map[string]bool
}

func (scan *handwrittenSourceScan) collectTypeDeclarations() {
	for _, declaration := range scan.file.Decls {
		typeGroup, isTypeGroup := declaration.(*ast.GenDecl)
		if !isTypeGroup || typeGroup.Tok != token.TYPE {
			continue
		}

		for _, entry := range typeGroup.Specs {
			typeSpec, isTypeSpec := entry.(*ast.TypeSpec)
			if !isTypeSpec {
				continue
			}

			structType, isStruct := typeSpec.Type.(*ast.StructType)
			if isStruct {
				scan.declarations[structType] = modelDeclaration{spec: typeSpec, group: typeGroup, structType: structType}
			}
		}
	}
}

func (scan *handwrittenSourceScan) reportNestedAnonymousJSON() {
	for structType, declaration := range scan.declarations {
		name := declaration.spec.Name.Name
		if (hasTaggedJSONField(structType) || scan.jsonTypes[name]) && hasAnonymousNestedJSON(structType) {
			line := scan.fset.Position(declaration.spec.Pos()).Line
			problem := fmt.Sprintf(
				"%s:%d %s contains a handwritten anonymous nested JSON object; promote it to a generated schema component",
				scan.path, line, name,
			)
			scan.problems = append(scan.problems, problem)
		}
	}
}

func (scan *handwrittenSourceScan) inspectStruct(structType *ast.StructType) {
	declaration, isNamed := scan.declarations[structType]
	if !isNamed {
		scan.inspectAnonymousStruct(structType)

		return
	}

	scan.inspectNamedStruct(structType, declaration)
}

func (scan *handwrittenSourceScan) inspectAnonymousStruct(structType *ast.StructType) {
	if !hasTaggedJSONField(structType) && !scan.jsonAnonymous[structType] {
		return
	}

	line := scan.fset.Position(structType.Pos()).Line
	problem := fmt.Sprintf("%s:%d contains an anonymous handwritten JSON object; promote it to a named schema-generated type", scan.path, line)
	scan.problems = append(scan.problems, problem)
}

func (scan *handwrittenSourceScan) inspectNamedStruct(structType *ast.StructType, declaration modelDeclaration) {
	name := declaration.spec.Name.Name
	if !hasTaggedJSONField(structType) && !scan.jsonTypes[name] {
		return
	}

	key := scan.path + "::" + name

	scan.seen[key] = true
	if scan.generated {
		line := scan.fset.Position(declaration.spec.Pos()).Line
		problem := fmt.Sprintf(
			"%s:%d %s is in an unregistered generated Go file; add its exact schema/generator output to tools/modelinventory/main.go",
			scan.path, line, name,
		)
		scan.problems = append(scan.problems, problem)

		return
	}

	scan.recordManifestModel(key, structType, declaration)
}

func (scan *handwrittenSourceScan) recordManifestModel(key string, structType *ast.StructType, declaration modelDeclaration) {
	name := declaration.spec.Name.Name
	allowance, isListed := scan.allowances[key]

	classification, reason := modelMarker(declaration.group.Doc, declaration.spec.Doc)

	if !isListed {
		line := scan.fset.Position(declaration.spec.Pos()).Line
		scan.problems = append(scan.problems, fmt.Sprintf("%s:%d %s is not listed in %s", scan.path, line, name, handwrittenManifestPath))

		return
	}

	scan.validateModelMarker(name, classification, reason, allowance, declaration)
	scan.validateModelClassification(key, allowance)
	scan.validateModelEvidence(key, name, allowance)

	scan.models = append(scan.models, handwrittenModel{
		Path: scan.path, Name: name, Classification: classification, Reason: reason,
		Fields: jsonTaggedFields(structType), Evidence: allowance.Evidence,
	})
}

func (scan *handwrittenSourceScan) validateModelMarker(name, classification, reason string, allowance handwrittenAllowance, declaration modelDeclaration) {
	validReason := strings.HasPrefix(reason, name+":") && strings.TrimSpace(strings.TrimPrefix(reason, name+":")) != ""
	if classification == allowance.Classification && reason == allowance.Reason && validReason {
		return
	}

	line := scan.fset.Position(declaration.spec.Pos()).Line
	problem := fmt.Sprintf("%s:%d %s marker must exactly name the type and match its reviewed manifest reason", scan.path, line, name)
	scan.problems = append(scan.problems, problem)
}

func (scan *handwrittenSourceScan) validateModelClassification(key string, allowance handwrittenAllowance) {
	if allowance.Classification != "semantic" && allowance.Classification != "client-input" && allowance.Classification != "domain" {
		scan.problems = append(scan.problems, fmt.Sprintf("%s manifest entry has unsupported classification %q", key, allowance.Classification))
	}

	if allowance.Reason == "" || len(allowance.Evidence) == 0 {
		scan.problems = append(scan.problems, key+" must record a type-specific reason and concrete boundary evidence")
	}
}

func (scan *handwrittenSourceScan) validateModelEvidence(key, name string, allowance handwrittenAllowance) {
	for _, evidence := range allowance.Evidence {
		err := validateEvidence(evidence, name)
		if err != nil {
			scan.problems = append(scan.problems, fmt.Sprintf("%s evidence %q: %v", key, evidence, err))
		}
	}
}

func (scan *handwrittenSourceScan) hasTaggedGeneratedTypes() bool {
	for _, declaration := range scan.declarations {
		if hasTaggedJSONField(declaration.structType) {
			return true
		}
	}

	return false
}

func (scan *handwrittenSourceScan) includeCustomJSONTypes() {
	for name := range scan.methods {
		if scan.hasHandwrittenModel(name) {
			continue
		}

		scan.includeCustomJSONType(name)
	}
}

func (scan *handwrittenSourceScan) hasHandwrittenModel(name string) bool {
	for _, model := range scan.models {
		if model.Name == name && model.Path == scan.path {
			return true
		}
	}

	return false
}

func (scan *handwrittenSourceScan) includeCustomJSONType(name string) {
	key := scan.path + "::" + name
	scan.seen[key] = true
	allowance, isListed := scan.allowances[key]

	spec, group := findTypeDeclaration(scan.file, name)

	if !isListed || spec == nil {
		scan.problems = append(scan.problems, fmt.Sprintf("%s custom JSON type %s must have an exact handwritten manifest entry", scan.path, name))

		return
	}

	classification, reason := modelMarker(group.Doc, spec.Doc)
	if classification != allowance.Classification || reason != allowance.Reason || !strings.HasPrefix(reason, name+":") {
		scan.problems = append(scan.problems, fmt.Sprintf("%s %s marker must exactly name the type and match its reviewed manifest reason", scan.path, name))
	}

	scan.validateModelEvidence(key, name, allowance)
	scan.models = append(scan.models, handwrittenModel{
		Path: scan.path, Name: name, Classification: classification, Reason: reason,
		Fields: nil, Evidence: allowance.Evidence,
	})
}

func findTypeDeclaration(file *ast.File, name string) (*ast.TypeSpec, *ast.GenDecl) {
	for _, declaration := range file.Decls {
		typeGroup, isTypeGroup := declaration.(*ast.GenDecl)
		if !isTypeGroup || typeGroup.Tok != token.TYPE {
			continue
		}

		for _, entry := range typeGroup.Specs {
			candidate, isTypeSpec := entry.(*ast.TypeSpec)
			if isTypeSpec && candidate.Name.Name == name {
				return candidate, typeGroup
			}
		}
	}

	return nil, nil
}
func jsonCodecStructs(file *ast.File) (map[string]bool, map[*ast.StructType]bool) {
	named := make(map[string]bool)
	anonymous := make(map[*ast.StructType]bool)

	jsonImport := encodingJSONImportName(file)

	if jsonImport == "" {
		return named, anonymous
	}

	scan := jsonCodecScan{
		jsonImport: jsonImport, environment: nil, named: named, anonymous: anonymous,
	}

	for _, declaration := range file.Decls {
		function, isFunction := declaration.(*ast.FuncDecl)
		if isFunction && function.Body != nil {
			scan.inspectFunction(function)
		}
	}

	return named, anonymous
}

func encodingJSONImportName(file *ast.File) string {
	for _, imported := range file.Imports {
		importPath, err := strconv.Unquote(imported.Path.Value)
		if err != nil || importPath != "encoding/json" {
			continue
		}

		if imported.Name != nil {
			return imported.Name.Name
		}

		return "json"
	}

	return ""
}

type jsonCodecScan struct {
	jsonImport  string
	environment map[string]ast.Expr
	named       map[string]bool
	anonymous   map[*ast.StructType]bool
}

func (scan *jsonCodecScan) inspectFunction(function *ast.FuncDecl) {
	scan.environment = functionTypeEnvironment(function)
	ast.Inspect(function.Body, scan.inspectNode)
}

func functionTypeEnvironment(function *ast.FuncDecl) map[string]ast.Expr {
	environment := make(map[string]ast.Expr)
	if function.Recv != nil {
		addFieldTypes(environment, function.Recv.List)
	}

	if function.Type.Params != nil {
		addFieldTypes(environment, function.Type.Params.List)
	}

	return environment
}

func addFieldTypes(environment map[string]ast.Expr, fields []*ast.Field) {
	for _, field := range fields {
		for _, name := range field.Names {
			environment[name.Name] = field.Type
		}
	}
}

func (scan *jsonCodecScan) inspectNode(node ast.Node) bool {
	switch statement := node.(type) {
	case *ast.DeclStmt:
		scan.recordVariableDeclaration(statement)
	case *ast.AssignStmt:
		scan.recordShortDeclaration(statement)
	case *ast.CallExpr:
		scan.recordCodecArgument(statement)
	}

	return true
}

func (scan *jsonCodecScan) recordVariableDeclaration(statement *ast.DeclStmt) {
	group, isGroup := statement.Decl.(*ast.GenDecl)
	if !isGroup || group.Tok != token.VAR {
		return
	}

	for _, spec := range group.Specs {
		values, isValues := spec.(*ast.ValueSpec)
		if isValues {
			scan.recordValueSpec(values)
		}
	}
}

func (scan *jsonCodecScan) recordValueSpec(values *ast.ValueSpec) {
	for index, name := range values.Names {
		typeExpr := values.Type
		if typeExpr == nil && index < len(values.Values) {
			typeExpr = inferredTypeExpression(values.Values[index])
		}

		if typeExpr != nil {
			scan.environment[name.Name] = typeExpr
		}
	}
}

func (scan *jsonCodecScan) recordShortDeclaration(statement *ast.AssignStmt) {
	if statement.Tok != token.DEFINE {
		return
	}

	for index, lhs := range statement.Lhs {
		identifier, isIdentifier := lhs.(*ast.Ident)
		if !isIdentifier || index >= len(statement.Rhs) {
			continue
		}

		typeExpr := inferredTypeExpression(statement.Rhs[index])
		if typeExpr != nil {
			scan.environment[identifier.Name] = typeExpr
		}
	}
}

func (scan *jsonCodecScan) recordCodecArgument(call *ast.CallExpr) {
	_, index, isCodecCall := jsonCodecArgument(call, scan.jsonImport)
	if !isCodecCall || index >= len(call.Args) {
		return
	}

	expression := codecArgumentValue(call.Args[index])

	typeExpr := inferredTypeExpression(expression)

	if typeExpr == nil {
		typeExpr = scan.environmentType(expression)
	}

	scan.recordCodecType(typeExpr)
}

func codecArgumentValue(expression ast.Expr) ast.Expr {
	unary, isUnary := expression.(*ast.UnaryExpr)
	if isUnary && unary.Op == token.AND {
		return unary.X
	}

	return expression
}

func (scan *jsonCodecScan) environmentType(expression ast.Expr) ast.Expr {
	identifier, isIdentifier := expression.(*ast.Ident)
	if !isIdentifier {
		return nil
	}

	return scan.environment[identifier.Name]
}

func (scan *jsonCodecScan) recordCodecType(typeExpr ast.Expr) {
	if typeExpr == nil {
		return
	}

	switch typed := unwrapGoType(typeExpr).(type) {
	case *ast.StructType:
		scan.anonymous[typed] = true
	case *ast.Ident:
		scan.named[typed.Name] = true
	case *ast.SelectorExpr:
		scan.named[typed.Sel.Name] = true
	}
}

func inferredTypeExpression(expression ast.Expr) ast.Expr {
	switch typed := expression.(type) {
	case *ast.CompositeLit:
		return typed.Type
	case *ast.UnaryExpr:
		if typed.Op == token.AND {
			return inferredTypeExpression(typed.X)
		}
	case *ast.ParenExpr:
		return inferredTypeExpression(typed.X)
	}

	return nil
}

func jsonCodecArgument(call *ast.CallExpr, importedName string) (string, int, bool) {
	selector, isSelector := call.Fun.(*ast.SelectorExpr)
	if !isSelector {
		return "", 0, false
	}

	packageName, isIdentifier := selector.X.(*ast.Ident)
	if isIdentifier && packageName.Name == importedName {
		return directJSONCodecArgument(selector.Sel.Name)
	}

	return jsonEncoderMethodArgument(selector, importedName)
}

func directJSONCodecArgument(method string) (string, int, bool) {
	switch method {
	case "Marshal":
		return "marshal", 0, true
	case "Unmarshal":
		return "unmarshal", 1, true
	case "NewEncoder":
		return "encoder", -1, false
	case "NewDecoder":
		return "decoder", -1, false
	default:
		return "", 0, false
	}
}

func jsonEncoderMethodArgument(selector *ast.SelectorExpr, importedName string) (string, int, bool) {
	if selector.Sel.Name != "Encode" && selector.Sel.Name != "Decode" {
		return "", 0, false
	}

	constructor, isCall := selector.X.(*ast.CallExpr)
	if !isCall {
		return "", 0, false
	}

	constructorSelector, isSelector := constructor.Fun.(*ast.SelectorExpr)
	if !isSelector {
		return "", 0, false
	}

	packageName, isIdentifier := constructorSelector.X.(*ast.Ident)
	if !isIdentifier || packageName.Name != importedName {
		return "", 0, false
	}

	if selector.Sel.Name == "Encode" {
		return "encoder", 0, true
	}

	return "decoder", 0, true
}

type modelDeclaration struct {
	spec       *ast.TypeSpec
	group      *ast.GenDecl
	structType *ast.StructType
}

func hasTaggedJSONField(structType *ast.StructType) bool {
	for _, field := range structType.Fields.List {
		if field.Tag == nil {
			continue
		}

		tag, err := strconv.Unquote(field.Tag.Value)
		if err == nil && strings.Contains(tag, "json:") {
			return true
		}
	}

	return false
}

func validateEvidence(evidence, modelName string) error {
	parts := strings.SplitN(evidence, "#", evidenceParts)
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return diagnosticf("expected path#function form")
	}

	receiverName, functionName := evidenceFunctionNames(parts[1])

	source, err := os.ReadFile(filepath.FromSlash(parts[0]))
	if err != nil {
		return fmt.Errorf("read evidence source: %w", err)
	}

	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, parts[0], source, 0)
	if err != nil {
		return fmt.Errorf("parse evidence source: %w", err)
	}

	matchedFunction := false

	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != functionName || (receiverName != "" && evidenceReceiverName(function) != receiverName) {
			continue
		}

		matchedFunction = true

		if containsIdent(function.Type, modelName) || containsIdent(function.Body, modelName) {
			return nil
		}
	}

	if matchedFunction {
		return diagnosticf("function %s does not reference the listed model %s in its signature or body", parts[1], modelName)
	}

	return diagnosticf("function %s is not declared in %s", parts[1], parts[0])
}

func evidenceFunctionNames(value string) (string, string) {
	separator := strings.LastIndex(value, ".")
	if separator < 0 {
		return "", value
	}

	return value[:separator], value[separator+1:]
}

func evidenceReceiverName(function *ast.FuncDecl) string {
	if function.Recv == nil || len(function.Recv.List) != 1 {
		return ""
	}

	expression := function.Recv.List[0].Type
	if star, ok := expression.(*ast.StarExpr); ok {
		expression = star.X
	}

	switch receiver := expression.(type) {
	case *ast.Ident:
		return receiver.Name
	case *ast.SelectorExpr:
		return receiver.Sel.Name
	default:
		return ""
	}
}

func containsIdent(node ast.Node, name string) bool {
	found := false

	ast.Inspect(node, func(candidate ast.Node) bool {
		ident, ok := candidate.(*ast.Ident)
		if ok && ident.Name == name {
			found = true

			return false
		}

		return !found
	})

	return found
}

func jsonTaggedFields(structType *ast.StructType) []string {
	var fields []string

	for _, field := range structType.Fields.List {
		if field.Tag == nil {
			continue
		}

		tag, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			continue
		}

		for _, part := range strings.Split(tag, " ") {
			if !strings.HasPrefix(part, "json:") {
				continue
			}

			value, valueErr := strconv.Unquote(strings.TrimPrefix(part, "json:"))
			if valueErr != nil {
				continue
			}

			name := strings.Split(value, ",")[0]
			if name != "-" && name != "" {
				fields = append(fields, name)
			}
		}
	}

	sort.Strings(fields)

	return fields
}

func hasAnonymousNestedJSON(structType *ast.StructType) bool {
	found := false

	ast.Inspect(structType, func(node ast.Node) bool {
		if node == structType {
			return true
		}

		nested, ok := node.(*ast.StructType)
		if !ok {
			return true
		}

		if hasJSONEncodedFields(nested) {
			found = true

			return false
		}

		return !found
	})

	return found
}

func hasJSONEncodedFields(structType *ast.StructType) bool {
	for _, field := range structType.Fields.List {
		jsonName, hasJSONTag := jsonFieldTag(field)
		if jsonName == "-" {
			continue
		}

		if hasJSONTag {
			return true
		}

		for _, name := range field.Names {
			if ast.IsExported(name.Name) {
				return true
			}
		}
	}

	return false
}

func jsonFieldTag(field *ast.Field) (string, bool) {
	if field.Tag == nil {
		return "", false
	}

	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", false
	}

	for _, item := range strings.Split(tag, " ") {
		if !strings.HasPrefix(item, "json:") {
			continue
		}

		jsonTag, err := strconv.Unquote(strings.TrimPrefix(item, "json:"))
		if err != nil {
			return "", false
		}

		return strings.Split(jsonTag, ",")[0], true
	}

	return "", false
}

func customJSONMethods(file *ast.File) map[string]bool {
	methods := make(map[string]bool)

	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Recv == nil || function.Name.Name != "MarshalJSON" && function.Name.Name != "UnmarshalJSON" {
			continue
		}

		for _, receiver := range function.Recv.List {
			if star, ok := receiver.Type.(*ast.StarExpr); ok {
				receiver.Type = star.X
			}

			if ident, ok := receiver.Type.(*ast.Ident); ok {
				methods[ident.Name] = true
			}
		}
	}

	return methods
}

func modelMarker(groups ...*ast.CommentGroup) (string, string) {
	for _, group := range groups {
		if group == nil {
			continue
		}

		for _, comment := range group.List {
			for _, classification := range []string{"client-input", "semantic", "domain"} {
				prefix := "//modelinventory:" + classification + " "
				if strings.HasPrefix(comment.Text, prefix) {
					return classification, strings.TrimPrefix(comment.Text, prefix)
				}
			}
		}
	}

	return "", ""
}

func findCallSites(typeName, definition string) []string {
	files := []string{}

	walkErr := filepath.WalkDir("pkg", func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("walk package source while finding model call sites: %w", err)
		}

		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || filepath.ToSlash(path) == definition {
			return nil
		}

		files = append(files, filepath.ToSlash(path))

		return nil
	})
	if walkErr != nil {
		fatalf("walk package source while finding model call sites: %v", walkErr)
	}

	var usages []string

	for _, path := range files {
		fset := token.NewFileSet()

		file, err := parser.ParseFile(fset, path, mustRead(path), parser.ParseComments)
		if err != nil {
			continue
		}

		ast.Inspect(file, func(node ast.Node) bool {
			ident, ok := node.(*ast.Ident)
			if ok && ident.Name == typeName {
				usages = append(usages, fmt.Sprintf("%s:%d", path, fset.Position(ident.Pos()).Line))
			}

			return true
		})
	}

	sort.Strings(usages)

	return compact(usages)
}

func renderInventory(rows []inventoryRow, handwritten []handwrittenModel) []byte {
	var out strings.Builder

	out.WriteString("# Alexa wire-model inventory\n\n")
	out.WriteString(generatedInventoryIntro)
	out.WriteString("## Models and primitive projections\n\n")
	out.WriteString("| Schema / source | Component or model | Go definition | Generator | Call site or use |\n|---|---|---|---|---|\n")

	for _, row := range rows {
		callSites := strings.Join(row.CallSites, ", ")
		if callSites == "" {
			callSites = "exported model; no internal call site found"
		}

		fmt.Fprintf(&out, "| `%s` | `%s` | `%s` (`%s`) | %s | %s |\n", row.Schema, row.Component, row.GoType, row.Definition, row.Generator, callSites)
	}

	out.WriteString("\n## Handwritten semantic and input models\n\n")
	out.WriteString(handwrittenInventoryIntro)
	out.WriteString("| Type | Fields | Classification and reason |\n|---|---|---|\n")

	for _, model := range handwritten {
		fmt.Fprintf(
			&out,
			"| `%s.%s` | %s | `%s`: %s; evidence: %s |\n",
			model.Path,
			model.Name,
			strings.Join(model.Fields, ", "),
			model.Classification,
			escapeTable(model.Reason),
			strings.Join(model.Evidence, ", "),
		)
	}

	return []byte(out.String())
}

func generatorDescription(set generatedSet) string {
	return fmt.Sprintf("%s; config/source: `%s`; command: `%s`", set.Kind, set.Config, set.Command)
}

func dedupeRows(rows []inventoryRow) []inventoryRow {
	seen := make(map[string]bool)

	result := make([]inventoryRow, 0, len(rows))

	for _, row := range rows {
		key := row.Schema + "\x00" + row.GoType + "\x00" + row.Definition
		if seen[key] {
			continue
		}

		seen[key] = true

		result = append(result, row)
	}

	return result
}

func isGeneratedFile(path string) bool {
	data, err := os.ReadFile(filepath.FromSlash(path))
	if err != nil {
		return false
	}

	first := string(data)
	if len(first) > generatedHeaderLimit {
		first = first[:generatedHeaderLimit]
	}

	return strings.Contains(first, "Code generated")
}

func mustRead(path string) []byte {
	data, err := os.ReadFile(filepath.FromSlash(path))
	if err != nil {
		fatalf("read %s: %v", path, err)
	}

	return data
}

func compact(values []string) []string {
	if len(values) < minimumCompactValues {
		return values
	}

	result := values[:1]
	for _, value := range values[1:] {
		if value != result[len(result)-1] {
			result = append(result, value)
		}
	}

	return result
}

func escapeTable(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "|", "\\|"), "\n", " ")
}

func fatalf(format string, values ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", values...)
	os.Exit(1)
}
