package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"strings"
)

func inventorySDKPrimitiveTypes(primitives map[string]sdkPrimitive) ([]inventoryRow, error) {
	owners := make(map[string]sdkPrimitive)

	for _, primitive := range primitives {
		if primitive.Type != "" {
			owners[primitive.Type] = primitive
		}
	}

	definitions, err := findSDKPrimitiveTypeDefinitions(owners)
	if err != nil {
		return nil, err
	}

	usages, err := findPrimitiveCallSites(owners, primitivePackage{ImportPath: sdkImportPath, Name: "alexaapimodels", Directory: "pkg/alexaapimodels"})
	if err != nil {
		return nil, err
	}

	rows := make([]inventoryRow, 0, len(owners))

	for name, owner := range owners {
		definition := definitions[name]
		if definition == "" {
			return nil, diagnosticf("SDK schema constant type %s has no open string semantic definition", name)
		}

		rows = append(rows, inventoryRow{
			Schema: owner.Schema, Component: owner.Component,
			GoType: "alexaapimodels." + name + " (open semantic type)", Definition: definition,
			Generator: "handwritten semantic type; its known values are schema-generated by go run ./tools/wireconstants",
			CallSites: usages[name],
		})
	}

	return rows, nil
}

func findSDKPrimitiveTypeDefinitions(owners map[string]sdkPrimitive) (map[string]string, error) {
	definitions := make(map[string]string)

	err := filepath.WalkDir("pkg/alexaapimodels", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return fmt.Errorf("walk SDK primitive types: %w", walkErr)
		}

		path = filepath.ToSlash(path)
		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		file, parseErr := parser.ParseFile(token.NewFileSet(), path, mustRead(path), 0)
		if parseErr != nil {
			return fmt.Errorf("parse SDK primitive types %s: %w", path, parseErr)
		}

		ast.Inspect(file, func(node ast.Node) bool {
			typeSpec, isType := node.(*ast.TypeSpec)
			if !isType {
				return true
			}

			if _, owned := owners[typeSpec.Name.Name]; !owned {
				return true
			}

			underlying, isIdentifier := typeSpec.Type.(*ast.Ident)
			if isIdentifier && underlying.Name == schemaStringType {
				definitions[typeSpec.Name.Name] = path
			}

			return true
		})

		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("inventory SDK primitive types: %w", err)
	}

	return definitions, nil
}
