package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
	"testing"
)

func TestSDKProjectionRejectsMissingChangedAndInjectedDeclarations(t *testing.T) {
	t.Parallel()

	primitives := map[string]sdkPrimitive{
		"PowerStateOn": {Schema: "auth.yaml", Component: "PowerState", Value: "ON", Type: "PowerState"},
	}

	for name, declaration := range map[string]string{
		"missing":       "",
		"changed":       `const PowerStateOn PowerState = "OFF"`,
		"changed type":  `const PowerStateOn = "ON"`,
		"extra":         `const Unknown = "ON"`,
		"duplicate":     `const PowerStateOn PowerState = "ON"; const PowerStateOn PowerState = "ON"`,
		"computed":      `const PowerStateOn PowerState = "O" + "N"`,
		"injected type": `const PowerStateOn PowerState = "ON"; type Secret struct{ Value string }`,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			file := parseSDKPrimitiveTestSource(t, "package alexaapimodels\n"+declaration)

			err := verifySDKPrimitiveDeclarations(file, primitives)
			if err == nil {
				t.Fatal("invalid generated projection was accepted")
			}
		})
	}

	file := parseSDKPrimitiveTestSource(t, "package alexaapimodels\nconst PowerStateOn PowerState = \"ON\"")

	err := verifySDKPrimitiveDeclarations(file, primitives)
	if err != nil {
		t.Fatalf("valid projection rejected: %v", err)
	}
}

func TestHandwrittenSDKStringsRejectUnexportedAliasesAndConcatenation(t *testing.T) {
	t.Parallel()

	for _, declaration := range []string{
		`const State = "ON"`,
		`const private = "ON"; const State = private`,
		`const State = "O" + "N"`,
		`const State = string("ON")`,
	} {
		file := parseSDKPrimitiveTestSource(t, "package alexaapimodels\n"+declaration)

		err := rejectHandwrittenSDKConstants(file, "pkg/alexaapimodels/probe.go")
		if err == nil {
			t.Fatalf("handwritten primitive accepted: %s", declaration)
		}
	}
}

func TestSDKGraphQLBindingRejectsDriftAndMissingEnum(t *testing.T) {
	t.Parallel()

	graphql, err := readGraphQLSchema()
	if err != nil {
		t.Fatalf("read SDL: %v", err)
	}

	schema := emptySchemaNode()
	schema.SDKType = "PowerState"
	schema.CompatibilityConstants = map[string]string{"SDKPowerStateOn": "ON"}
	schema.SDKGraphQLValues = map[string]string{"PowerStateOn": "PowerStateValue.ON"}

	err = checkSDKGraphQLBindings(schema, graphql)
	if err != nil {
		t.Fatalf("valid shared enum binding: %v", err)
	}

	schema.CompatibilityConstants["SDKPowerStateOn"] = "FUTURE"

	err = checkSDKGraphQLBindings(schema, graphql)
	if err == nil {
		t.Fatal("SDK enum drift accepted")
	}

	schema.CompatibilityConstants["SDKPowerStateOn"] = "ON"
	schema.SDKGraphQLValues["PowerStateOn"] = "Missing.ON"

	err = checkSDKGraphQLBindings(schema, graphql)
	if err == nil {
		t.Fatal("missing SDL enum accepted")
	}

	delete(schema.SDKGraphQLValues, "PowerStateOn")

	err = checkSDKGraphQLBindings(schema, graphql)
	if err == nil {
		t.Fatal("missing overlap binding accepted")
	}
}

func TestSDKPrimitiveUsesDistinguishGraphQLAndShadowedImports(t *testing.T) {
	t.Parallel()

	set := token.NewFileSet()

	file, err := parser.ParseFile(set, "probe.go", `package probe
import sdk "github.com/portpowered/go-alexa/pkg/alexaapimodels"
import wire "github.com/portpowered/go-alexa/pkg/dependencymodels"
var sdkValue = sdk.PowerStateOn
var wireValue = wire.PowerStateOn
func shadow() { sdk := struct{ PowerStateOn string }{}; _ = sdk.PowerStateOn }
`, 0)
	if err != nil {
		t.Fatalf("parse use probe: %v", err)
	}

	usages := make(map[string][]string)
	names := map[string]sdkPrimitive{"PowerStateOn": {Schema: "schema", Component: "PowerState", Value: "ON", Type: "PowerState"}}
	owner := primitivePackage{ImportPath: sdkImportPath, Name: "alexaapimodels", Directory: "pkg/alexaapimodels"}
	collectPrimitiveUses(file, "pkg/probe.go", set, names, usages, owner)

	if len(usages["PowerStateOn"]) != 1 || !strings.HasSuffix(usages["PowerStateOn"][0], ":4") {
		t.Fatalf("SDK usages include another projection or shadow: %v", usages)
	}
}

func parseSDKPrimitiveTestSource(t *testing.T, source string) *ast.File {
	t.Helper()

	file, err := parser.ParseFile(token.NewFileSet(), "probe.go", source, 0)
	if err != nil {
		t.Fatalf("parse primitive probe: %v", err)
	}

	return file
}

func TestRawWirePrimitiveGateRejectsKnownValuesAtWireSinksAndForgedHeaders(t *testing.T) {
	t.Parallel()

	for _, source := range []string{
		`package probe; var payload = map[string]any{"powerState": "ON"}`,
		"// Code generated by a fake generator; DO NOT EDIT.\npackage probe; const State = \"ON\"; var payload = map[string]any{\"powerState\": State}",
	} {
		path := writeEvidenceSource(t, source)

		models := wireConstructionTestModels()
		models["Payload"] = generatedModel{
			Name: "Payload", File: "pkg/dependencymodels/payload.gen.go", Schema: "", Generator: "",
			Fields: map[string]ast.Expr{"powerState": nil}, Type: nil, Alias: false, Generated: true,
		}

		err := rejectRawWirePrimitiveValues(filepath.Dir(path), map[string]bool{"ON": true, "powerState": true}, nil, models)
		if err == nil || !strings.Contains(err.Error(), "raw schema-known wire value") {
			t.Fatalf("raw wire value or forged generated marker accepted: %v", err)
		}
	}
}

func TestRawWirePrimitiveGateAllowsNonWireErrorText(t *testing.T) {
	t.Parallel()

	path := writeEvidenceSource(t, `package probe
type HTTPClientCookieJarError struct { Edge string }
func (err *HTTPClientCookieJarError) Error() string { return err.Edge + " HTTP client" }
var err = &HTTPClientCookieJarError{Edge: "GraphQL"}
func diagnostic() string { return "ON" }
`)

	err := rejectRawWirePrimitiveValues(filepath.Dir(path), map[string]bool{"ON": true, "GraphQL": true}, nil)
	if err != nil {
		t.Fatalf("non-wire diagnostic text was treated as a wire value: %v", err)
	}
}

func TestRawWirePrimitiveGateRejectsSameDiagnosticLabelAtGeneratedWireSink(t *testing.T) {
	t.Parallel()

	path := writeEvidenceSource(t, `package probe
import wire "github.com/portpowered/go-alexa/pkg/dependencymodels"
func request() { _ = wire.Payload{Value: "GraphQL"} }
`)

	err := rejectRawWirePrimitiveValues(filepath.Dir(path), map[string]bool{"GraphQL": true}, nil, wireConstructionTestModels())
	if err == nil || !strings.Contains(err.Error(), "raw schema-known wire value") {
		t.Fatalf("generated wire sink accepted diagnostic label as raw wire value: %v", err)
	}
}

func TestRawWirePrimitiveGateAllowsCallerInputsAndRegisteredOutput(t *testing.T) {
	t.Parallel()

	path := writeEvidenceSource(t, `package probe
import wire "github.com/portpowered/go-alexa/pkg/dependencymodels"
func request(caller string) { _ = wire.Payload{Value: caller} }
`)

	err := rejectRawWirePrimitiveValues(filepath.Dir(path), map[string]bool{"ON": true}, nil, wireConstructionTestModels())
	if err != nil {
		t.Fatalf("caller-owned generated wire value rejected: %v", err)
	}

	generated := writeEvidenceSource(t, `package probe; const State = "ON"`)

	err = rejectRawWirePrimitiveValues(filepath.Dir(generated), map[string]bool{"ON": true}, map[string]bool{filepath.ToSlash(generated): true})
	if err != nil {
		t.Fatalf("registered generated constant rejected: %v", err)
	}
}
