// Code generated by tools/graphqlops; DO NOT EDIT.
package graphql

func schemaBackedGraphQLOperation(query string) bool {
	switch query {
	case Endpoints_Operation, GetEndpoint_Operation, ListEndpointsWithStates_Operation, ListEndpoints_Operation, RequestEndpointQualityOfService_Operation, SetEndpointFeatures_Operation, Subscribe_Operation:
		return true
	default:
		return false
	}
}
