// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// WireAuthData defines model for WireAuthData.
type WireAuthData struct {
	CodePair      *WireCodePairAuth      `json:"code_pair,omitempty"`
	EmailPassword *WireEmailPasswordAuth `json:"email_password,omitempty"`
}

// WireBearerTokens defines model for WireBearerTokens.
type WireBearerTokens struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// WireChallenge defines model for WireChallenge.
type WireChallenge struct {
	ChallengeReason              *string `json:"challenge_reason,omitempty"`
	RequiredAuthenticationMethod *string `json:"required_authentication_method,omitempty"`
}

// WireChallengeEnvelope defines model for WireChallengeEnvelope.
type WireChallengeEnvelope struct {
	Challenge *WireChallenge `json:"challenge,omitempty"`
}

// WireChallengeResponse defines model for WireChallengeResponse.
type WireChallengeResponse struct {
	Response *WireChallengeEnvelope `json:"response,omitempty"`
}

// WireCodeData defines model for WireCodeData.
type WireCodeData struct {
	AppName               string `json:"app_name"`
	AppVersion            string `json:"app_version"`
	DeviceModel           string `json:"device_model"`
	DeviceName            string `json:"device_name"`
	DeviceSerial          string `json:"device_serial"`
	DeviceType            string `json:"device_type"`
	Domain                string `json:"domain"`
	OsVersion             string `json:"os_version"`
	SecondaryRegistration string `json:"secondary_registration"`
}

// WireCodePairAuth defines model for WireCodePairAuth.
type WireCodePairAuth struct {
	PrivateCode string `json:"private_code"`
	PublicCode  string `json:"public_code"`
}

// WireCodePairRequest defines model for WireCodePairRequest.
type WireCodePairRequest struct {
	CodeData WireCodeData `json:"code_data"`
	Scopes   []string     `json:"scopes"`
}

// WireCodePairResponse defines model for WireCodePairResponse.
type WireCodePairResponse struct {
	PrivateCode *string `json:"private_code,omitempty"`
	PublicCode  *string `json:"public_code,omitempty"`
}

// WireCookieExchangeEnvelope defines model for WireCookieExchangeEnvelope.
type WireCookieExchangeEnvelope struct {
	Tokens *WireCookieTokens `json:"tokens,omitempty"`
}

// WireCookieExchangeRequest defines model for WireCookieExchangeRequest.
type WireCookieExchangeRequest struct {
	AppName            string `json:"app_name"`
	Domain             string `json:"domain"`
	RequestedTokenType string `json:"requested_token_type"`
	SourceToken        string `json:"source_token"`
	SourceTokenType    string `json:"source_token_type"`
}

// WireCookieExchangeResponse defines model for WireCookieExchangeResponse.
type WireCookieExchangeResponse struct {
	Response *WireCookieExchangeEnvelope `json:"response,omitempty"`
}

// WireCookieRecord defines model for WireCookieRecord.
type WireCookieRecord struct {
	Expires  *string `json:"Expires,omitempty"`
	HttpOnly *bool   `json:"HttpOnly,omitempty"`
	Name     *string `json:"Name,omitempty"`
	Path     *string `json:"Path,omitempty"`
	Secure   *bool   `json:"Secure,omitempty"`
	Value    *string `json:"Value,omitempty"`
}

// WireCookieTokens defines model for WireCookieTokens.
type WireCookieTokens struct {
	Cookies *map[string][]WireCookieRecord `json:"cookies,omitempty"`
}

// WireDeviceMetadata defines model for WireDeviceMetadata.
type WireDeviceMetadata struct {
	DeviceModel  string `json:"device_model"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Manufacturer string `json:"manufacturer"`
	OsVersion    string `json:"os_version"`
}

// WireEmailPasswordAuth defines model for WireEmailPasswordAuth.
type WireEmailPasswordAuth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// WireRegistrationData defines model for WireRegistrationData.
type WireRegistrationData struct {
	AppName      string `json:"app_name"`
	AppVersion   string `json:"app_version"`
	DeviceModel  string `json:"device_model"`
	DeviceName   string `json:"device_name"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Domain       string `json:"domain"`
	OsVersion    string `json:"os_version"`
}

// WireRegistrationRequest defines model for WireRegistrationRequest.
type WireRegistrationRequest struct {
	AuthData           WireAuthData         `json:"auth_data"`
	RegistrationData   WireRegistrationData `json:"registration_data"`
	RequestedTokenType []string             `json:"requested_token_type"`
}

// WireRegistrationResponse defines model for WireRegistrationResponse.
type WireRegistrationResponse struct {
	Response *WireRegistrationResponseEnvelope `json:"response,omitempty"`
}

// WireRegistrationResponseEnvelope defines model for WireRegistrationResponseEnvelope.
type WireRegistrationResponseEnvelope struct {
	Success *WireRegistrationSuccess `json:"success,omitempty"`
}

// WireRegistrationSuccess defines model for WireRegistrationSuccess.
type WireRegistrationSuccess struct {
	Tokens *WireRegistrationTokens `json:"tokens,omitempty"`
}

// WireRegistrationTokens defines model for WireRegistrationTokens.
type WireRegistrationTokens struct {
	Bearer *WireBearerTokens `json:"bearer,omitempty"`
}

// WireTokenRefreshRequest defines model for WireTokenRefreshRequest.
type WireTokenRefreshRequest struct {
	AppName            string             `json:"app_name"`
	AppVersion         string             `json:"app_version"`
	DeviceMetadata     WireDeviceMetadata `json:"device_metadata"`
	RequestedTokenType string             `json:"requested_token_type"`
	SourceToken        string             `json:"source_token"`
	SourceTokenType    string             `json:"source_token_type"`
}

// WireTokenRefreshResponse defines model for WireTokenRefreshResponse.
type WireTokenRefreshResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int    `json:"expires_in,omitempty"`
}

// ExchangeRefreshTokenForCookiesParams defines parameters for ExchangeRefreshTokenForCookies.
type ExchangeRefreshTokenForCookiesParams struct {
	// XAmznIdentityAuthDomain Set by the cookie exchange implementation to `api.{domain}`.
	XAmznIdentityAuthDomain string `json:"x-amzn-identity-auth-domain"`
}

// ExchangeRefreshTokenForCookiesJSONRequestBody defines body for ExchangeRefreshTokenForCookies for application/json ContentType.
type ExchangeRefreshTokenForCookiesJSONRequestBody = WireCookieExchangeRequest

// CreateCodePairJSONRequestBody defines body for CreateCodePair for application/json ContentType.
type CreateCodePairJSONRequestBody = WireCodePairRequest

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = WireRegistrationRequest

// RefreshAccessTokenJSONRequestBody defines body for RefreshAccessToken for application/json ContentType.
type RefreshAccessTokenJSONRequestBody = WireTokenRefreshRequest
