// Code generated by Modelina. DO NOT EDIT.

package alexamodels

type DirectivePayload struct {
	RenderingUpdates     []RenderingUpdate      `json:"renderingUpdates" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
