// Code generated by Modelina. DO NOT EDIT.

package alexamodels

type DirectiveMessage struct {
	Directive            *Directive             `json:"directive" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
