// Code generated by Modelina. DO NOT EDIT.

package alexamodels

type Directive struct {
	Header               *DirectiveHeader       `json:"header" binding:"required"`
	Payload              *DirectivePayload      `json:"payload" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
