// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"time"
)

// AuthData defines model for AuthData.
type AuthData struct {
	CodePairAuth      *CodePairAuth      `json:"code_pair,omitempty"`
	EmailPasswordAuth *EmailPasswordAuth `json:"email_password,omitempty"`
}

// BearerTokens defines model for BearerTokens.
type BearerTokens struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// Challenge defines model for Challenge.
type Challenge struct {
	ChallengeReason              string `json:"challenge_reason"`
	RequiredAuthenticationMethod string `json:"required_authentication_method,omitempty"`
}

// ChallengeEnvelope defines model for ChallengeEnvelope.
type ChallengeEnvelope struct {
	Challenge Challenge `json:"challenge"`
}

// ChallengeResponse defines model for ChallengeResponse.
type ChallengeResponse struct {
	Response ChallengeEnvelope `json:"response"`
}

// CodeData defines model for CodeData.
type CodeData struct {
	AppName               string `json:"app_name"`
	AppVersion            string `json:"app_version"`
	DeviceModel           string `json:"device_model"`
	DeviceName            string `json:"device_name"`
	DeviceSerial          string `json:"device_serial"`
	DeviceType            string `json:"device_type"`
	Domain                string `json:"domain"`
	OSVersion             string `json:"os_version"`
	SecondaryRegistration string `json:"secondary_registration"`
}

// CodePairAuth defines model for CodePairAuth.
type CodePairAuth struct {
	PrivateCode string `json:"private_code"`
	PublicCode  string `json:"public_code"`
}

// CodePairRequest defines model for CodePairRequest.
type CodePairRequest struct {
	CodeData CodeData `json:"code_data"`
	Scopes   []string `json:"scopes"`
}

// CodePairResponse defines model for CodePairResponse.
type CodePairResponse struct {
	PrivateCode string `json:"private_code"`
	PublicCode  string `json:"public_code"`
}

// DeviceAuthResponse defines model for DeviceAuthResponse.
type DeviceAuthResponse struct {
	DeviceCode              string `json:"device_code"`
	ExpiresIn               int    `json:"expires_in"`
	Interval                int    `json:"interval,omitempty"`
	UserCode                string `json:"user_code"`
	VerificationURI         string `json:"verification_uri"`
	VerificationURIComplete string `json:"verification_uri_complete,omitempty"`
}

// DeviceMetadata defines model for DeviceMetadata.
type DeviceMetadata struct {
	DeviceModel  string `json:"device_model"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Manufacturer string `json:"manufacturer"`
	OSVersion    string `json:"os_version"`
}

// EmailPasswordAuth defines model for EmailPasswordAuth.
type EmailPasswordAuth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// RegistrationData defines model for RegistrationData.
type RegistrationData struct {
	AppName      string `json:"app_name"`
	AppVersion   string `json:"app_version"`
	DeviceModel  string `json:"device_model"`
	DeviceName   string `json:"device_name"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Domain       string `json:"domain"`
	OSVersion    string `json:"os_version"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	AuthData           AuthData         `json:"auth_data"`
	RegistrationData   RegistrationData `json:"registration_data"`
	RequestedTokenType []string         `json:"requested_token_type"`
}

// RegistrationResponse defines model for RegistrationResponse.
type RegistrationResponse struct {
	Response RegistrationResponseEnvelope `json:"response"`
}

// RegistrationResponseEnvelope defines model for RegistrationResponseEnvelope.
type RegistrationResponseEnvelope struct {
	Success RegistrationSuccess `json:"success"`
}

// RegistrationSuccess defines model for RegistrationSuccess.
type RegistrationSuccess struct {
	Tokens RegistrationTokens `json:"tokens"`
}

// RegistrationTokens defines model for RegistrationTokens.
type RegistrationTokens struct {
	Bearer BearerTokens `json:"bearer"`
}

// Token Legacy caller-owned credential and expiration projection preserved for
// Go API compatibility. This is not a provider response model.
type Token struct {
	AccessToken  string    `json:"access_token,omitempty"`
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	ExpiresIn    int       `json:"expires_in,omitempty"`
	RefreshToken string    `json:"refresh_token,omitempty"`
	Scope        string    `json:"scope,omitempty"`
	TokenType    string    `json:"token_type,omitempty"`
}

// TokenRefreshRequest defines model for TokenRefreshRequest.
type TokenRefreshRequest struct {
	AppName            string         `json:"app_name"`
	AppVersion         string         `json:"app_version"`
	DeviceMetadata     DeviceMetadata `json:"device_metadata"`
	RequestedTokenType string         `json:"requested_token_type"`
	SourceToken        string         `json:"source_token"`
	SourceTokenType    string         `json:"source_token_type"`
}

// TokenRefreshResponse defines model for TokenRefreshResponse.
type TokenRefreshResponse struct {
	AccessToken      string `json:"access_token"`
	ExpiresInSeconds int    `json:"expires_in"`
}
