// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// WireBehaviorPreviewRequest defines model for WireBehaviorPreviewRequest.
type WireBehaviorPreviewRequest struct {
	BehaviorId string `json:"behaviorId"`

	// SequenceJson JSON-encoded sequence serialized as a string by the client; the embedded object is modeled in api/behaviors.yaml.
	SequenceJson string `json:"sequenceJson"`
	Status       string `json:"status"`
}

// SubmitBehaviorPreviewJSONRequestBody defines body for SubmitBehaviorPreview for application/json ContentType.
type SubmitBehaviorPreviewJSONRequestBody = WireBehaviorPreviewRequest
