// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// Defines values for AnnouncementMethod.
const (
	BehaviorAnnouncementMethodAll   AnnouncementMethod = "all"
	BehaviorAnnouncementMethodShow  AnnouncementMethod = "show"
	BehaviorAnnouncementMethodSpeak AnnouncementMethod = "speak"
)

// Valid indicates whether the value is a known member of the AnnouncementMethod enum.
func (e AnnouncementMethod) Valid() bool {
	switch e {
	case BehaviorAnnouncementMethodAll:
		return true
	case BehaviorAnnouncementMethodShow:
		return true
	case BehaviorAnnouncementMethodSpeak:
		return true
	default:
		return false
	}
}

// Defines values for AnnouncementOperationType.
const (
	AnnouncementOperationTypeAlexaAnnouncement AnnouncementOperationType = "AlexaAnnouncement"
)

// Valid indicates whether the value is a known member of the AnnouncementOperationType enum.
func (e AnnouncementOperationType) Valid() bool {
	switch e {
	case AnnouncementOperationTypeAlexaAnnouncement:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorAlexaURL.
const (
	BehaviorAlexaURLBehaviors BehaviorAlexaURL = "#v2/behaviors"
)

// Valid indicates whether the value is a known member of the BehaviorAlexaURL enum.
func (e BehaviorAlexaURL) Valid() bool {
	switch e {
	case BehaviorAlexaURLBehaviors:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorAnnouncementExpireAfter.
const (
	BehaviorAnnouncementExpireAfterFiveSeconds BehaviorAnnouncementExpireAfter = "PT5S"
)

// Valid indicates whether the value is a known member of the BehaviorAnnouncementExpireAfter enum.
func (e BehaviorAnnouncementExpireAfter) Valid() bool {
	switch e {
	case BehaviorAnnouncementExpireAfterFiveSeconds:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorAnnouncementSpeakType.
const (
	BehaviorAnnouncementSpeakTypeText BehaviorAnnouncementSpeakType = "text"
)

// Valid indicates whether the value is a known member of the BehaviorAnnouncementSpeakType enum.
func (e BehaviorAnnouncementSpeakType) Valid() bool {
	switch e {
	case BehaviorAnnouncementSpeakTypeText:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorDefaultID.
const (
	BehaviorDefaultIDPreview BehaviorDefaultID = "PREVIEW"
)

// Valid indicates whether the value is a known member of the BehaviorDefaultID enum.
func (e BehaviorDefaultID) Valid() bool {
	switch e {
	case BehaviorDefaultIDPreview:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorDefaultLocale.
const (
	BehaviorDefaultLocaleEnglishUS BehaviorDefaultLocale = "en-US"
)

// Valid indicates whether the value is a known member of the BehaviorDefaultLocale enum.
func (e BehaviorDefaultLocale) Valid() bool {
	switch e {
	case BehaviorDefaultLocaleEnglishUS:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorDefaultStatus.
const (
	BehaviorDefaultStatusEnabled BehaviorDefaultStatus = "ENABLED"
)

// Valid indicates whether the value is a known member of the BehaviorDefaultStatus enum.
func (e BehaviorDefaultStatus) Valid() bool {
	switch e {
	case BehaviorDefaultStatusEnabled:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorOperationType.
const (
	BehaviorOperationTypeAnnouncement                BehaviorOperationType = "AlexaAnnouncement"
	BehaviorOperationTypeCannedTtsSpeak              BehaviorOperationType = "Alexa.CannedTts.Speak"
	BehaviorOperationTypeDeviceControlsStop          BehaviorOperationType = "Alexa.DeviceControls.Stop"
	BehaviorOperationTypeDeviceControlsVolume        BehaviorOperationType = "Alexa.DeviceControls.Volume"
	BehaviorOperationTypeFireTVNavigateHome          BehaviorOperationType = "Alexa.Operation.FireTV.NavigateHome"
	BehaviorOperationTypeFireTVPauseVideo            BehaviorOperationType = "Alexa.Operation.FireTV.PauseVideo"
	BehaviorOperationTypeFireTVResumeVideo           BehaviorOperationType = "Alexa.Operation.FireTV.ResumeVideo"
	BehaviorOperationTypeFireTVTurnOff               BehaviorOperationType = "Alexa.Operation.FireTV.TurnOff"
	BehaviorOperationTypeFireTVTurnOn                BehaviorOperationType = "Alexa.Operation.FireTV.TurnOn"
	BehaviorOperationTypeMusicPlaySearchPhrase       BehaviorOperationType = "Alexa.Music.PlaySearchPhrase"
	BehaviorOperationTypeNotificationsSendMobilePush BehaviorOperationType = "Alexa.Notifications.SendMobilePush"
	BehaviorOperationTypeSound                       BehaviorOperationType = "Alexa.Sound"
	BehaviorOperationTypeSpeak                       BehaviorOperationType = "Alexa.Speak"
	BehaviorOperationTypeVideoPlaySearchPhrase       BehaviorOperationType = "Alexa.Operation.Video.PlaySearchPhrase"
)

// Valid indicates whether the value is a known member of the BehaviorOperationType enum.
func (e BehaviorOperationType) Valid() bool {
	switch e {
	case BehaviorOperationTypeAnnouncement:
		return true
	case BehaviorOperationTypeCannedTtsSpeak:
		return true
	case BehaviorOperationTypeDeviceControlsStop:
		return true
	case BehaviorOperationTypeDeviceControlsVolume:
		return true
	case BehaviorOperationTypeFireTVNavigateHome:
		return true
	case BehaviorOperationTypeFireTVPauseVideo:
		return true
	case BehaviorOperationTypeFireTVResumeVideo:
		return true
	case BehaviorOperationTypeFireTVTurnOff:
		return true
	case BehaviorOperationTypeFireTVTurnOn:
		return true
	case BehaviorOperationTypeMusicPlaySearchPhrase:
		return true
	case BehaviorOperationTypeNotificationsSendMobilePush:
		return true
	case BehaviorOperationTypeSound:
		return true
	case BehaviorOperationTypeSpeak:
		return true
	case BehaviorOperationTypeVideoPlaySearchPhrase:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorPayloadKey.
const (
	BehaviorPayloadKeyAlexaURL              BehaviorPayloadKey = "alexaUrl"
	BehaviorPayloadKeyBody                  BehaviorPayloadKey = "body"
	BehaviorPayloadKeyCannedTtsStringID     BehaviorPayloadKey = "cannedTtsStringId"
	BehaviorPayloadKeyContent               BehaviorPayloadKey = "content"
	BehaviorPayloadKeyCustomerID            BehaviorPayloadKey = "customerId"
	BehaviorPayloadKeyDeviceAccountID       BehaviorPayloadKey = "deviceAccountId"
	BehaviorPayloadKeyDeviceSerialNumber    BehaviorPayloadKey = "deviceSerialNumber"
	BehaviorPayloadKeyDeviceType            BehaviorPayloadKey = "deviceType"
	BehaviorPayloadKeyDevices               BehaviorPayloadKey = "devices"
	BehaviorPayloadKeyDisplay               BehaviorPayloadKey = "display"
	BehaviorPayloadKeyExpireAfter           BehaviorPayloadKey = "expireAfter"
	BehaviorPayloadKeyLocale                BehaviorPayloadKey = "locale"
	BehaviorPayloadKeyMusicProviderID       BehaviorPayloadKey = "musicProviderId"
	BehaviorPayloadKeyNotificationMessage   BehaviorPayloadKey = "notificationMessage"
	BehaviorPayloadKeySanitizedSearchPhrase BehaviorPayloadKey = "sanitizedSearchPhrase"
	BehaviorPayloadKeySearchPhrase          BehaviorPayloadKey = "searchPhrase"
	BehaviorPayloadKeySkillID               BehaviorPayloadKey = "skillId"
	BehaviorPayloadKeySoundStringID         BehaviorPayloadKey = "soundStringId"
	BehaviorPayloadKeySpeak                 BehaviorPayloadKey = "speak"
	BehaviorPayloadKeyTarget                BehaviorPayloadKey = "target"
	BehaviorPayloadKeyTextToSpeak           BehaviorPayloadKey = "textToSpeak"
	BehaviorPayloadKeyTitle                 BehaviorPayloadKey = "title"
	BehaviorPayloadKeyType                  BehaviorPayloadKey = "type"
	BehaviorPayloadKeyValue                 BehaviorPayloadKey = "value"
	BehaviorPayloadKeyWaitTimeInSeconds     BehaviorPayloadKey = "waitTimeInSeconds"
)

// Valid indicates whether the value is a known member of the BehaviorPayloadKey enum.
func (e BehaviorPayloadKey) Valid() bool {
	switch e {
	case BehaviorPayloadKeyAlexaURL:
		return true
	case BehaviorPayloadKeyBody:
		return true
	case BehaviorPayloadKeyCannedTtsStringID:
		return true
	case BehaviorPayloadKeyContent:
		return true
	case BehaviorPayloadKeyCustomerID:
		return true
	case BehaviorPayloadKeyDeviceAccountID:
		return true
	case BehaviorPayloadKeyDeviceSerialNumber:
		return true
	case BehaviorPayloadKeyDeviceType:
		return true
	case BehaviorPayloadKeyDevices:
		return true
	case BehaviorPayloadKeyDisplay:
		return true
	case BehaviorPayloadKeyExpireAfter:
		return true
	case BehaviorPayloadKeyLocale:
		return true
	case BehaviorPayloadKeyMusicProviderID:
		return true
	case BehaviorPayloadKeyNotificationMessage:
		return true
	case BehaviorPayloadKeySanitizedSearchPhrase:
		return true
	case BehaviorPayloadKeySearchPhrase:
		return true
	case BehaviorPayloadKeySkillID:
		return true
	case BehaviorPayloadKeySoundStringID:
		return true
	case BehaviorPayloadKeySpeak:
		return true
	case BehaviorPayloadKeyTarget:
		return true
	case BehaviorPayloadKeyTextToSpeak:
		return true
	case BehaviorPayloadKeyTitle:
		return true
	case BehaviorPayloadKeyType:
		return true
	case BehaviorPayloadKeyValue:
		return true
	case BehaviorPayloadKeyWaitTimeInSeconds:
		return true
	default:
		return false
	}
}

// Defines values for BehaviorSkillID.
const (
	BehaviorSkillIDAlexaDeviceControls BehaviorSkillID = "amzn1.ask.1p.alexadevicecontrols"
	BehaviorSkillIDAlexaNotifications  BehaviorSkillID = "amzn1.ask.1p.alexanotifications"
	BehaviorSkillIDRoutinesFireTV      BehaviorSkillID = "amzn1.ask.1p.routines.firetv"
	BehaviorSkillIDRoutinesMessaging   BehaviorSkillID = "amzn1.ask.1p.routines.messaging"
	BehaviorSkillIDSaySomething        BehaviorSkillID = "amzn1.ask.1p.saysomething"
)

// Valid indicates whether the value is a known member of the BehaviorSkillID enum.
func (e BehaviorSkillID) Valid() bool {
	switch e {
	case BehaviorSkillIDAlexaDeviceControls:
		return true
	case BehaviorSkillIDAlexaNotifications:
		return true
	case BehaviorSkillIDRoutinesFireTV:
		return true
	case BehaviorSkillIDRoutinesMessaging:
		return true
	case BehaviorSkillIDSaySomething:
		return true
	default:
		return false
	}
}

// Defines values for CannedTTSSpeakOperationType.
const (
	CannedTTSSpeakOperationTypeCannedTtsSpeak CannedTTSSpeakOperationType = "Alexa.CannedTts.Speak"
)

// Valid indicates whether the value is a known member of the CannedTTSSpeakOperationType enum.
func (e CannedTTSSpeakOperationType) Valid() bool {
	switch e {
	case CannedTTSSpeakOperationTypeCannedTtsSpeak:
		return true
	default:
		return false
	}
}

// Defines values for DeviceControlsStopOperationType.
const (
	DeviceControlsStopOperationTypeStop DeviceControlsStopOperationType = "Alexa.DeviceControls.Stop"
)

// Valid indicates whether the value is a known member of the DeviceControlsStopOperationType enum.
func (e DeviceControlsStopOperationType) Valid() bool {
	switch e {
	case DeviceControlsStopOperationTypeStop:
		return true
	default:
		return false
	}
}

// Defines values for DeviceControlsVolumeOperationType.
const (
	DeviceControlsVolumeOperationTypeVolume DeviceControlsVolumeOperationType = "Alexa.DeviceControls.Volume"
)

// Valid indicates whether the value is a known member of the DeviceControlsVolumeOperationType enum.
func (e DeviceControlsVolumeOperationType) Valid() bool {
	switch e {
	case DeviceControlsVolumeOperationTypeVolume:
		return true
	default:
		return false
	}
}

// Defines values for MusicPlaySearchPhraseOperationType.
const (
	MusicPlaySearchPhraseOperationTypePlaySearchPhrase MusicPlaySearchPhraseOperationType = "Alexa.Music.PlaySearchPhrase"
)

// Valid indicates whether the value is a known member of the MusicPlaySearchPhraseOperationType enum.
func (e MusicPlaySearchPhraseOperationType) Valid() bool {
	switch e {
	case MusicPlaySearchPhraseOperationTypePlaySearchPhrase:
		return true
	default:
		return false
	}
}

// Defines values for NotificationsSendMobilePushOperationType.
const (
	NotificationsSendMobilePushOperationTypeSendMobilePush NotificationsSendMobilePushOperationType = "Alexa.Notifications.SendMobilePush"
)

// Valid indicates whether the value is a known member of the NotificationsSendMobilePushOperationType enum.
func (e NotificationsSendMobilePushOperationType) Valid() bool {
	switch e {
	case NotificationsSendMobilePushOperationTypeSendMobilePush:
		return true
	default:
		return false
	}
}

// Defines values for OpaquePayloadOperationNodeType.
const (
	ComAmazonAlexaBehaviorsModelOpaquePayloadOperationNode OpaquePayloadOperationNodeType = "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode"
)

// Valid indicates whether the value is a known member of the OpaquePayloadOperationNodeType enum.
func (e OpaquePayloadOperationNodeType) Valid() bool {
	switch e {
	case ComAmazonAlexaBehaviorsModelOpaquePayloadOperationNode:
		return true
	default:
		return false
	}
}

// Defines values for ParallelNodeType.
const (
	ComAmazonAlexaBehaviorsModelParallelNode ParallelNodeType = "com.amazon.alexa.behaviors.model.ParallelNode"
)

// Valid indicates whether the value is a known member of the ParallelNodeType enum.
func (e ParallelNodeType) Valid() bool {
	switch e {
	case ComAmazonAlexaBehaviorsModelParallelNode:
		return true
	default:
		return false
	}
}

// Defines values for SequenceType.
const (
	ComAmazonAlexaBehaviorsModelSequence SequenceType = "com.amazon.alexa.behaviors.model.Sequence"
)

// Valid indicates whether the value is a known member of the SequenceType enum.
func (e SequenceType) Valid() bool {
	switch e {
	case ComAmazonAlexaBehaviorsModelSequence:
		return true
	default:
		return false
	}
}

// Defines values for SerialNodeType.
const (
	ComAmazonAlexaBehaviorsModelSerialNode SerialNodeType = "com.amazon.alexa.behaviors.model.SerialNode"
)

// Valid indicates whether the value is a known member of the SerialNodeType enum.
func (e SerialNodeType) Valid() bool {
	switch e {
	case ComAmazonAlexaBehaviorsModelSerialNode:
		return true
	default:
		return false
	}
}

// Defines values for SoundOperationType.
const (
	SoundOperationTypeAlexaSound SoundOperationType = "Alexa.Sound"
)

// Valid indicates whether the value is a known member of the SoundOperationType enum.
func (e SoundOperationType) Valid() bool {
	switch e {
	case SoundOperationTypeAlexaSound:
		return true
	default:
		return false
	}
}

// Defines values for SpeakOperationType.
const (
	SpeakOperationTypeAlexaSpeak SpeakOperationType = "Alexa.Speak"
)

// Valid indicates whether the value is a known member of the SpeakOperationType enum.
func (e SpeakOperationType) Valid() bool {
	switch e {
	case SpeakOperationTypeAlexaSpeak:
		return true
	default:
		return false
	}
}

// Defines values for VideoPlaySearchPhraseOperationType.
const (
	VideoPlaySearchPhraseOperationTypePlaySearchPhrase VideoPlaySearchPhraseOperationType = "Alexa.Operation.Video.PlaySearchPhrase"
)

// Valid indicates whether the value is a known member of the VideoPlaySearchPhraseOperationType enum.
func (e VideoPlaySearchPhraseOperationType) Valid() bool {
	switch e {
	case VideoPlaySearchPhraseOperationTypePlaySearchPhrase:
		return true
	default:
		return false
	}
}

// AnnouncementMethod Values accepted by the implementation's announcement method switch.
type AnnouncementMethod string

// AnnouncementOperationNode Implementation-derived node paired with the generated announcement payload; no sanitized live capture is available.
type AnnouncementOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload AnnouncementPayload       `json:"operationPayload"`
	OperationType    AnnouncementOperationType `json:"type"`
}

// AnnouncementOperationType defines model for AnnouncementOperationType.
type AnnouncementOperationType string

// AnnouncementPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type AnnouncementPayload struct {
	Content            []BehaviorAnnouncementContent   `json:"content"`
	CustomerID         string                          `json:"customerId"`
	DeviceSerialNumber string                          `json:"deviceSerialNumber"`
	DeviceType         string                          `json:"deviceType"`
	ExpireAfter        BehaviorAnnouncementExpireAfter `json:"expireAfter"`
	Locale             string                          `json:"locale"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
	Target  Target          `json:"target"`
}

// BehaviorAlexaURL defines model for BehaviorAlexaURL.
type BehaviorAlexaURL string

// BehaviorAnnouncementContent Implementation-derived nested behavior content shape; no sanitized live capture is available.
type BehaviorAnnouncementContent struct {
	Display BehaviorAnnouncementDisplay `json:"display"`
	Locale  string                      `json:"locale"`
	Speak   BehaviorAnnouncementSpeak   `json:"speak"`
}

// BehaviorAnnouncementDisplay defines model for BehaviorAnnouncementDisplay.
type BehaviorAnnouncementDisplay struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}

// BehaviorAnnouncementExpireAfter defines model for BehaviorAnnouncementExpireAfter.
type BehaviorAnnouncementExpireAfter string

// BehaviorAnnouncementSpeak defines model for BehaviorAnnouncementSpeak.
type BehaviorAnnouncementSpeak struct {
	Type  BehaviorAnnouncementSpeakType `json:"type"`
	Value string                        `json:"value"`
}

// BehaviorAnnouncementSpeakType defines model for BehaviorAnnouncementSpeakType.
type BehaviorAnnouncementSpeakType string

// BehaviorDefaultID defines model for BehaviorDefaultID.
type BehaviorDefaultID string

// BehaviorDefaultLocale defines model for BehaviorDefaultLocale.
type BehaviorDefaultLocale string

// BehaviorDefaultStatus defines model for BehaviorDefaultStatus.
type BehaviorDefaultStatus string

// BehaviorNodeDiscriminator Schema used by the implementation to read a behavior node discriminator before selecting its typed model.
type BehaviorNodeDiscriminator struct {
	Type string `json:"@type"`
}

// BehaviorOperationType Known operation names constructed by this implementation.
type BehaviorOperationType string

// BehaviorPayloadKey Known behavior payload property names, including compatibility keys.
type BehaviorPayloadKey string

// BehaviorPreviewRequest defines model for BehaviorPreviewRequest.
type BehaviorPreviewRequest struct {
	BehaviorID   string `json:"behaviorId"`
	SequenceJSON string `json:"sequenceJson"`
	Status       string `json:"status"`
}

// BehaviorSequenceNodeInspection Schema used by the implementation to inspect composite behavior nodes before recursively validating children.
type BehaviorSequenceNodeInspection struct {
	Type           string        `json:"@type"`
	NodesToExecute []interface{} `json:"nodesToExecute"`
}

// BehaviorSkillID Skill identifiers used by the implementation-built behavior operations.
type BehaviorSkillID string

// CannedTTSSpeakOperationNode Compatibility node and payload shape retained for an exported legacy payload key; not built by active REST methods.
type CannedTTSSpeakOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Compatibility payload shape retained for an exported legacy payload key; not built by active REST methods.
	OperationPayload CannedTTSSpeakPayload       `json:"operationPayload"`
	OperationType    CannedTTSSpeakOperationType `json:"type"`
}

// CannedTTSSpeakOperationType defines model for CannedTTSSpeakOperationType.
type CannedTTSSpeakOperationType string

// CannedTTSSpeakPayload Compatibility payload shape retained for an exported legacy payload key; not built by active REST methods.
type CannedTTSSpeakPayload struct {
	CannedTtsStringID  string `json:"cannedTtsStringId"`
	CustomerID         string `json:"customerId"`
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
	Locale             string `json:"locale"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
}

// DeviceControlsStopOperationNode Implementation-derived node paired with the generated device-controls stop payload; no sanitized live capture is available.
type DeviceControlsStopOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload DeviceControlsStopPayload       `json:"operationPayload"`
	OperationType    DeviceControlsStopOperationType `json:"type"`
}

// DeviceControlsStopOperationType defines model for DeviceControlsStopOperationType.
type DeviceControlsStopOperationType string

// DeviceControlsStopPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type DeviceControlsStopPayload struct {
	CustomerID         string `json:"customerId"`
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
	Locale             string `json:"locale"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
}

// DeviceControlsVolumeOperationNode Implementation-derived node paired with the generated device-controls volume payload; no sanitized live capture is available.
type DeviceControlsVolumeOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload DeviceControlsVolumePayload       `json:"operationPayload"`
	OperationType    DeviceControlsVolumeOperationType `json:"type"`
}

// DeviceControlsVolumeOperationType defines model for DeviceControlsVolumeOperationType.
type DeviceControlsVolumeOperationType string

// DeviceControlsVolumePayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type DeviceControlsVolumePayload struct {
	CustomerID         string `json:"customerId"`
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
	Locale             string `json:"locale"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
	Value   *int            `json:"value"`
}

// DeviceTarget defines model for DeviceTarget.
type DeviceTarget struct {
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
}

// FireTVOperationNode Implementation-derived node paired with the generated Fire TV payload; SendFireTVSequence preserves its caller-supplied operation type as an open string, with no sanitized live capture available.
type FireTVOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload FireTVOperationPayload `json:"operationPayload"`
	OperationType    string                 `json:"type"`
}

// FireTVOperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type FireTVOperationPayload struct {
	CustomerID      string `json:"customerId"`
	DeviceAccountID string `json:"deviceAccountId"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
}

// MusicPlaySearchPhraseOperationNode Implementation-derived node paired with the generated music search payload; no sanitized live capture is available.
type MusicPlaySearchPhraseOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload MusicPlaySearchPhrasePayload       `json:"operationPayload"`
	OperationType    MusicPlaySearchPhraseOperationType `json:"type"`
}

// MusicPlaySearchPhraseOperationType defines model for MusicPlaySearchPhraseOperationType.
type MusicPlaySearchPhraseOperationType string

// MusicPlaySearchPhrasePayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type MusicPlaySearchPhrasePayload struct {
	CustomerID            string `json:"customerId"`
	DeviceSerialNumber    string `json:"deviceSerialNumber"`
	DeviceType            string `json:"deviceType"`
	Locale                string `json:"locale"`
	MusicProviderID       string `json:"musicProviderId"`
	SanitizedSearchPhrase string `json:"sanitizedSearchPhrase"`
	SearchPhrase          string `json:"searchPhrase"`
	WaitTimeInSeconds     int    `json:"waitTimeInSeconds,omitempty"`
}

// NotificationsSendMobilePushOperationNode Implementation-derived node paired with the generated mobile notification payload; no sanitized live capture is available.
type NotificationsSendMobilePushOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload NotificationsSendMobilePushPayload       `json:"operationPayload"`
	OperationType    NotificationsSendMobilePushOperationType `json:"type"`
}

// NotificationsSendMobilePushOperationType defines model for NotificationsSendMobilePushOperationType.
type NotificationsSendMobilePushOperationType string

// NotificationsSendMobilePushPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type NotificationsSendMobilePushPayload struct {
	AlexaURL            BehaviorAlexaURL `json:"alexaUrl"`
	CustomerID          string           `json:"customerId"`
	DeviceSerialNumber  string           `json:"deviceSerialNumber"`
	DeviceType          string           `json:"deviceType"`
	Locale              string           `json:"locale"`
	NotificationMessage string           `json:"notificationMessage"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`
	Title   string          `json:"title"`
}

// OpaquePayloadOperationNode defines model for OpaquePayloadOperationNode.
type OpaquePayloadOperationNode struct {
	Type             OpaquePayloadOperationNodeType `json:"@type"`
	OperationPayload map[string]interface{}         `json:"operationPayload"`
	OperationType    string                         `json:"type"`
}

// OpaquePayloadOperationNodeType defines model for OpaquePayloadOperationNodeType.
type OpaquePayloadOperationNodeType string

// ParallelNode defines model for ParallelNode.
type ParallelNode struct {
	Type           ParallelNodeType `json:"@type"`
	NodesToExecute []interface{}    `json:"nodesToExecute"`
}

// ParallelNodeType defines model for ParallelNode.Type.
type ParallelNodeType string

// SDKKnownProviderID Known library ProviderID values. Caller-supplied extensions remain open.
type SDKKnownProviderID = string

// Sequence defines model for Sequence.
type Sequence struct {
	Type SequenceType `json:"@type"`

	// StartNode The implementation emits generated typed nodes for known operations, an open-payload node for generic SendSequence callers, or a serial or parallel composite node.
	StartNode interface{} `json:"startNode"`
}

// SequenceType defines model for SequenceType.
type SequenceType string

// SerialNode defines model for SerialNode.
type SerialNode struct {
	Type           SerialNodeType `json:"@type"`
	NodesToExecute []interface{}  `json:"nodesToExecute"`
}

// SerialNodeType defines model for SerialNode.Type.
type SerialNodeType string

// SoundOperationNode Implementation-derived node paired with the generated sound payload; no sanitized live capture is available.
type SoundOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload SoundPayload       `json:"operationPayload"`
	OperationType    SoundOperationType `json:"type"`
}

// SoundOperationType defines model for SoundOperationType.
type SoundOperationType string

// SoundPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type SoundPayload struct {
	CustomerID         string `json:"customerId"`
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
	Locale             string `json:"locale"`
	SoundStringID      string `json:"soundStringId"`
}

// SpeakOperationNode Implementation-derived node paired with the generated speech payload; no sanitized live capture is available.
type SpeakOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload SpeakPayload       `json:"operationPayload"`
	OperationType    SpeakOperationType `json:"type"`
}

// SpeakOperationType defines model for SpeakOperationType.
type SpeakOperationType string

// SpeakPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type SpeakPayload struct {
	CustomerID         string `json:"customerId"`
	DeviceSerialNumber string `json:"deviceSerialNumber"`
	DeviceType         string `json:"deviceType"`
	Locale             string `json:"locale"`

	// SkillID Skill identifiers used by the implementation-built behavior operations.
	SkillID BehaviorSkillID `json:"skillId"`

	// TextToSpeak Caller speech text, including the library audio-URI SSML wrapper. The URI is escaped before interpolation.
	TextToSpeak string `json:"textToSpeak"`
}

// Target defines model for Target.
type Target struct {
	CustomerID string         `json:"customerId,omitempty"`
	Devices    []DeviceTarget `json:"devices,omitempty"`
}

// VideoPlaySearchPhraseOperationNode Implementation-derived node paired with the generated video search payload; no sanitized live capture is available.
type VideoPlaySearchPhraseOperationNode struct {
	Type OpaquePayloadOperationNodeType `json:"@type"`

	// OperationPayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
	OperationPayload VideoPlaySearchPhrasePayload       `json:"operationPayload"`
	OperationType    VideoPlaySearchPhraseOperationType `json:"type"`
}

// VideoPlaySearchPhraseOperationType defines model for VideoPlaySearchPhraseOperationType.
type VideoPlaySearchPhraseOperationType string

// VideoPlaySearchPhrasePayload Implementation-derived nested behavior payload shape; no sanitized live capture is available.
type VideoPlaySearchPhrasePayload struct {
	CustomerID            string `json:"customerId"`
	DeviceSerialNumber    string `json:"deviceSerialNumber"`
	DeviceType            string `json:"deviceType"`
	Locale                string `json:"locale"`
	SanitizedSearchPhrase string `json:"sanitizedSearchPhrase"`
	SearchPhrase          string `json:"searchPhrase"`
	WaitTimeInSeconds     int    `json:"waitTimeInSeconds,omitempty"`
}
