// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// AnnouncementContent defines model for AnnouncementContent.
type AnnouncementContent struct {
	Display AnnouncementDisplay `json:"display"`
	Locale  string              `json:"locale"`
	Speak   AnnouncementSpeak   `json:"speak"`
}

// AnnouncementDisplay defines model for AnnouncementDisplay.
type AnnouncementDisplay struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}

// AnnouncementSpeak defines model for AnnouncementSpeak.
type AnnouncementSpeak struct {
	Type  string `json:"type"`
	Value string `json:"value"`
}
