// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// WireBehaviorPreviewRequest Example: {"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"Alexa.DeviceControls.Volume\",\"operationPayload\":{\"deviceType\":\"synthetic-device\",\"deviceSerialNumber\":\"synthetic-serial\",\"locale\":\"en-US\",\"customerId\":\"synthetic-customer\",\"value\":32,\"skillId\":\"amzn1.ask.1p.alexadevicecontrols\"}}}","status":"ENABLED"}
type WireBehaviorPreviewRequest struct {
	BehaviorId string `json:"behaviorId"`

	// SequenceJson JSON-encoded sequence serialized as a string by the client; the embedded object is modeled in api/behaviors.yaml.
	SequenceJson string `json:"sequenceJson"`
	Status       string `json:"status"`
}

// SubmitBehaviorPreviewJSONRequestBody defines body for SubmitBehaviorPreview for application/json ContentType.
type SubmitBehaviorPreviewJSONRequestBody = WireBehaviorPreviewRequest
