// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// ActionControlRequest defines model for ActionControlRequest.
type ActionControlRequest struct {
	BaseFeatureRequest
	Action string `json:"action"`

	Params map[string]interface{} `json:"params,omitempty"`
}

// BaseFeatureRequest defines model for BaseFeatureRequest.
type BaseFeatureRequest struct {
	EndpointID string `json:"endpointId"`
	EntityID   string `json:"entityId,omitempty"`
	Instance   string `json:"instance,omitempty"`
}

// BrightnessControlRequest defines model for BrightnessControlRequest.
type BrightnessControlRequest struct {
	BaseFeatureRequest
	Brightness *int `json:"brightness,omitempty"`
	Delta      *int `json:"delta,omitempty"`

	SetBrightness bool `json:"setBrightness,omitempty"`
}

// ColorControlRequest defines model for ColorControlRequest.
type ColorControlRequest struct {
	BaseFeatureRequest
	Brightness float64 `json:"brightness"`

	Hue float64 `json:"hue"`

	Saturation float64 `json:"saturation"`
}

// ColorTemperatureControlRequest defines model for ColorTemperatureControlRequest.
type ColorTemperatureControlRequest struct {
	BaseFeatureRequest
	ColorTemperature *int `json:"colorTemperature,omitempty"`

	Increase bool `json:"increase,omitempty"`

	SetTemperature bool `json:"setTemperature,omitempty"`
}

// LockControlRequest defines model for LockControlRequest.
type LockControlRequest struct {
	BaseFeatureRequest

	State string `json:"state"`
}

// ModeControlRequest defines model for ModeControlRequest.
type ModeControlRequest struct {
	BaseFeatureRequest
	Delta *string `json:"delta,omitempty"`

	Mode    *string `json:"mode,omitempty"`
	SetMode bool    `json:"setMode,omitempty"`
}

// PercentageControlRequest defines model for PercentageControlRequest.
type PercentageControlRequest struct {
	BaseFeatureRequest
	Delta *float64 `json:"delta,omitempty"`

	Percentage    *float64 `json:"percentage,omitempty"`
	SetPercentage bool     `json:"setPercentage,omitempty"`
}

// PowerLevelControlRequest defines model for PowerLevelControlRequest.
type PowerLevelControlRequest struct {
	BaseFeatureRequest
	Delta *int `json:"delta,omitempty"`

	PowerLevel    *int `json:"powerLevel,omitempty"`
	SetPowerLevel bool `json:"setPowerLevel,omitempty"`
}

// RangeControlRequest defines model for RangeControlRequest.
type RangeControlRequest struct {
	BaseFeatureRequest
	Delta *float64 `json:"delta,omitempty"`

	RangeValue *float64 `json:"rangeValue,omitempty"`
	SetValue   bool     `json:"setValue,omitempty"`
}

// SpeakerControlRequest defines model for SpeakerControlRequest.
type SpeakerControlRequest struct {
	BaseFeatureRequest
	Delta *int `json:"delta,omitempty"`

	SetVolume bool `json:"setVolume,omitempty"`
	Volume    *int `json:"volume,omitempty"`
}

// ThermostatControlRequest defines model for ThermostatControlRequest.
type ThermostatControlRequest struct {
	BaseFeatureRequest
	Delta *float64 `json:"delta,omitempty"`

	Scale       string   `json:"scale"`
	SetSetpoint bool     `json:"setSetpoint,omitempty"`
	Value       *float64 `json:"value,omitempty"`
}

// ThermostatModeControlRequest defines model for ThermostatModeControlRequest.
type ThermostatModeControlRequest struct {
	BaseFeatureRequest

	Mode string `json:"mode"`
}

// ToggleControlRequest defines model for ToggleControlRequest.
type ToggleControlRequest struct {
	BaseFeatureRequest

	State string `json:"state"`
}
