// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// Defines values for DeviceFamily.
const (
	EchoDeviceFamily      DeviceFamily = "ECHO"
	FireTVDeviceFamily    DeviceFamily = "FIRE_TV"
	KnightDeviceFamily    DeviceFamily = "KNIGHT"
	WholeHomeDeviceFamily DeviceFamily = "WHA"
)

// Valid indicates whether the value is a known member of the DeviceFamily enum.
func (e DeviceFamily) Valid() bool {
	switch e {
	case EchoDeviceFamily:
		return true
	case FireTVDeviceFamily:
		return true
	case KnightDeviceFamily:
		return true
	case WholeHomeDeviceFamily:
		return true
	default:
		return false
	}
}

// AppDevice defines model for AppDevice.
type AppDevice struct {
	DeviceAccountId string `json:"deviceAccountId"`
	DeviceType      string `json:"deviceType"`
	SerialNumber    string `json:"serialNumber"`
}

// CapabilityInterface Open capability-name alias; unknown names remain accepted.
type CapabilityInterface = string

// DeviceFamily defines model for DeviceFamily.
type DeviceFamily string

// DeviceV2 defines model for DeviceV2.
type DeviceV2 struct {
	AccountName            string                `json:"accountName"`
	AppDeviceList          []AppDevice           `json:"appDeviceList"`
	AssociatedUnitIds      interface{}           `json:"associatedUnitIds"`
	Capabilities           []CapabilityInterface `json:"capabilities"`
	Charging               *bool                 `json:"charging"`
	ClusterMembers         []string              `json:"clusterMembers"`
	DeviceAccountId        string                `json:"deviceAccountId"`
	DeviceFamily           string                `json:"deviceFamily"`
	DeviceOwnerCustomerId  string                `json:"deviceOwnerCustomerId"`
	DeviceType             string                `json:"deviceType"`
	DeviceTypeFriendlyName *string               `json:"deviceTypeFriendlyName"`
	Essid                  *string               `json:"essid"`
	Language               *string               `json:"language"`
	MacAddress             *string               `json:"macAddress"`
	Online                 bool                  `json:"online"`
	ParentClusters         []string              `json:"parentClusters"`
	PostalCode             *string               `json:"postalCode"`
	RegistrationId         *string               `json:"registrationId"`
	RemainingBatteryLevel  *int                  `json:"remainingBatteryLevel"`
	SerialNumber           string                `json:"serialNumber"`
	SoftwareVersion        string                `json:"softwareVersion"`
}

// DevicesV2Response defines model for DevicesV2Response.
type DevicesV2Response struct {
	Devices []DeviceV2 `json:"devices"`
}
