// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
	"fmt"
)

// WireAppDevice defines model for WireAppDevice.
type WireAppDevice struct {
	DeviceAccountId      *string                `json:"deviceAccountId,omitempty"`
	DeviceType           *string                `json:"deviceType,omitempty"`
	SerialNumber         *string                `json:"serialNumber,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireDeviceV2 defines model for WireDeviceV2.
type WireDeviceV2 struct {
	AccountName            *string                `json:"accountName,omitempty"`
	AppDeviceList          *[]WireAppDevice       `json:"appDeviceList,omitempty"`
	AssociatedUnitIds      *[]string              `json:"associatedUnitIds,omitempty"`
	Capabilities           *[]string              `json:"capabilities,omitempty"`
	Charging               *bool                  `json:"charging,omitempty"`
	ClusterMembers         *[]string              `json:"clusterMembers,omitempty"`
	DeviceAccountId        *string                `json:"deviceAccountId,omitempty"`
	DeviceFamily           *string                `json:"deviceFamily,omitempty"`
	DeviceOwnerCustomerId  *string                `json:"deviceOwnerCustomerId,omitempty"`
	DeviceType             *string                `json:"deviceType,omitempty"`
	DeviceTypeFriendlyName *string                `json:"deviceTypeFriendlyName,omitempty"`
	Essid                  *string                `json:"essid,omitempty"`
	Language               *string                `json:"language,omitempty"`
	MacAddress             *string                `json:"macAddress,omitempty"`
	Online                 *bool                  `json:"online,omitempty"`
	ParentClusters         *[]string              `json:"parentClusters,omitempty"`
	PostalCode             *string                `json:"postalCode,omitempty"`
	RegistrationId         *string                `json:"registrationId,omitempty"`
	RemainingBatteryLevel  *int                   `json:"remainingBatteryLevel,omitempty"`
	SerialNumber           *string                `json:"serialNumber,omitempty"`
	SoftwareVersion        *string                `json:"softwareVersion,omitempty"`
	AdditionalProperties   map[string]interface{} `json:"-"`
}

// WireDevicesV2Response defines model for WireDevicesV2Response.
type WireDevicesV2Response struct {
	Devices              []WireDeviceV2         `json:"devices"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ListFirstPartyDevicesParams defines parameters for ListFirstPartyDevices.
type ListFirstPartyDevicesParams struct {
	// Csrf The helper can send this value in its Cookie header.
	Csrf *string `json:"csrf,omitempty"`
}

// Getter for additional properties for WireAppDevice. Returns the specified
// element and whether it was found
func (a WireAppDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireAppDevice
func (a *WireAppDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireAppDevice to handle AdditionalProperties
func (a *WireAppDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["deviceAccountId"]; found {
		err = json.Unmarshal(raw, &a.DeviceAccountId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceAccountId': %w", err)
		}
		delete(object, "deviceAccountId")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireAppDevice to handle AdditionalProperties
func (a WireAppDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DeviceAccountId != nil {
		object["deviceAccountId"], err = json.Marshal(a.DeviceAccountId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceAccountId': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireDeviceV2. Returns the specified
// element and whether it was found
func (a WireDeviceV2) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireDeviceV2
func (a *WireDeviceV2) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireDeviceV2 to handle AdditionalProperties
func (a *WireDeviceV2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accountName"]; found {
		err = json.Unmarshal(raw, &a.AccountName)
		if err != nil {
			return fmt.Errorf("error reading 'accountName': %w", err)
		}
		delete(object, "accountName")
	}

	if raw, found := object["appDeviceList"]; found {
		err = json.Unmarshal(raw, &a.AppDeviceList)
		if err != nil {
			return fmt.Errorf("error reading 'appDeviceList': %w", err)
		}
		delete(object, "appDeviceList")
	}

	if raw, found := object["associatedUnitIds"]; found {
		err = json.Unmarshal(raw, &a.AssociatedUnitIds)
		if err != nil {
			return fmt.Errorf("error reading 'associatedUnitIds': %w", err)
		}
		delete(object, "associatedUnitIds")
	}

	if raw, found := object["capabilities"]; found {
		err = json.Unmarshal(raw, &a.Capabilities)
		if err != nil {
			return fmt.Errorf("error reading 'capabilities': %w", err)
		}
		delete(object, "capabilities")
	}

	if raw, found := object["charging"]; found {
		err = json.Unmarshal(raw, &a.Charging)
		if err != nil {
			return fmt.Errorf("error reading 'charging': %w", err)
		}
		delete(object, "charging")
	}

	if raw, found := object["clusterMembers"]; found {
		err = json.Unmarshal(raw, &a.ClusterMembers)
		if err != nil {
			return fmt.Errorf("error reading 'clusterMembers': %w", err)
		}
		delete(object, "clusterMembers")
	}

	if raw, found := object["deviceAccountId"]; found {
		err = json.Unmarshal(raw, &a.DeviceAccountId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceAccountId': %w", err)
		}
		delete(object, "deviceAccountId")
	}

	if raw, found := object["deviceFamily"]; found {
		err = json.Unmarshal(raw, &a.DeviceFamily)
		if err != nil {
			return fmt.Errorf("error reading 'deviceFamily': %w", err)
		}
		delete(object, "deviceFamily")
	}

	if raw, found := object["deviceOwnerCustomerId"]; found {
		err = json.Unmarshal(raw, &a.DeviceOwnerCustomerId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceOwnerCustomerId': %w", err)
		}
		delete(object, "deviceOwnerCustomerId")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["deviceTypeFriendlyName"]; found {
		err = json.Unmarshal(raw, &a.DeviceTypeFriendlyName)
		if err != nil {
			return fmt.Errorf("error reading 'deviceTypeFriendlyName': %w", err)
		}
		delete(object, "deviceTypeFriendlyName")
	}

	if raw, found := object["essid"]; found {
		err = json.Unmarshal(raw, &a.Essid)
		if err != nil {
			return fmt.Errorf("error reading 'essid': %w", err)
		}
		delete(object, "essid")
	}

	if raw, found := object["language"]; found {
		err = json.Unmarshal(raw, &a.Language)
		if err != nil {
			return fmt.Errorf("error reading 'language': %w", err)
		}
		delete(object, "language")
	}

	if raw, found := object["macAddress"]; found {
		err = json.Unmarshal(raw, &a.MacAddress)
		if err != nil {
			return fmt.Errorf("error reading 'macAddress': %w", err)
		}
		delete(object, "macAddress")
	}

	if raw, found := object["online"]; found {
		err = json.Unmarshal(raw, &a.Online)
		if err != nil {
			return fmt.Errorf("error reading 'online': %w", err)
		}
		delete(object, "online")
	}

	if raw, found := object["parentClusters"]; found {
		err = json.Unmarshal(raw, &a.ParentClusters)
		if err != nil {
			return fmt.Errorf("error reading 'parentClusters': %w", err)
		}
		delete(object, "parentClusters")
	}

	if raw, found := object["postalCode"]; found {
		err = json.Unmarshal(raw, &a.PostalCode)
		if err != nil {
			return fmt.Errorf("error reading 'postalCode': %w", err)
		}
		delete(object, "postalCode")
	}

	if raw, found := object["registrationId"]; found {
		err = json.Unmarshal(raw, &a.RegistrationId)
		if err != nil {
			return fmt.Errorf("error reading 'registrationId': %w", err)
		}
		delete(object, "registrationId")
	}

	if raw, found := object["remainingBatteryLevel"]; found {
		err = json.Unmarshal(raw, &a.RemainingBatteryLevel)
		if err != nil {
			return fmt.Errorf("error reading 'remainingBatteryLevel': %w", err)
		}
		delete(object, "remainingBatteryLevel")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if raw, found := object["softwareVersion"]; found {
		err = json.Unmarshal(raw, &a.SoftwareVersion)
		if err != nil {
			return fmt.Errorf("error reading 'softwareVersion': %w", err)
		}
		delete(object, "softwareVersion")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireDeviceV2 to handle AdditionalProperties
func (a WireDeviceV2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccountName != nil {
		object["accountName"], err = json.Marshal(a.AccountName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accountName': %w", err)
		}
	}

	if a.AppDeviceList != nil {
		object["appDeviceList"], err = json.Marshal(a.AppDeviceList)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appDeviceList': %w", err)
		}
	}

	if a.AssociatedUnitIds != nil {
		object["associatedUnitIds"], err = json.Marshal(a.AssociatedUnitIds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'associatedUnitIds': %w", err)
		}
	}

	if a.Capabilities != nil {
		object["capabilities"], err = json.Marshal(a.Capabilities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'capabilities': %w", err)
		}
	}

	if a.Charging != nil {
		object["charging"], err = json.Marshal(a.Charging)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'charging': %w", err)
		}
	}

	if a.ClusterMembers != nil {
		object["clusterMembers"], err = json.Marshal(a.ClusterMembers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clusterMembers': %w", err)
		}
	}

	if a.DeviceAccountId != nil {
		object["deviceAccountId"], err = json.Marshal(a.DeviceAccountId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceAccountId': %w", err)
		}
	}

	if a.DeviceFamily != nil {
		object["deviceFamily"], err = json.Marshal(a.DeviceFamily)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceFamily': %w", err)
		}
	}

	if a.DeviceOwnerCustomerId != nil {
		object["deviceOwnerCustomerId"], err = json.Marshal(a.DeviceOwnerCustomerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceOwnerCustomerId': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.DeviceTypeFriendlyName != nil {
		object["deviceTypeFriendlyName"], err = json.Marshal(a.DeviceTypeFriendlyName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceTypeFriendlyName': %w", err)
		}
	}

	if a.Essid != nil {
		object["essid"], err = json.Marshal(a.Essid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'essid': %w", err)
		}
	}

	if a.Language != nil {
		object["language"], err = json.Marshal(a.Language)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'language': %w", err)
		}
	}

	if a.MacAddress != nil {
		object["macAddress"], err = json.Marshal(a.MacAddress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'macAddress': %w", err)
		}
	}

	if a.Online != nil {
		object["online"], err = json.Marshal(a.Online)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'online': %w", err)
		}
	}

	if a.ParentClusters != nil {
		object["parentClusters"], err = json.Marshal(a.ParentClusters)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parentClusters': %w", err)
		}
	}

	if a.PostalCode != nil {
		object["postalCode"], err = json.Marshal(a.PostalCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'postalCode': %w", err)
		}
	}

	if a.RegistrationId != nil {
		object["registrationId"], err = json.Marshal(a.RegistrationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'registrationId': %w", err)
		}
	}

	if a.RemainingBatteryLevel != nil {
		object["remainingBatteryLevel"], err = json.Marshal(a.RemainingBatteryLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'remainingBatteryLevel': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	if a.SoftwareVersion != nil {
		object["softwareVersion"], err = json.Marshal(a.SoftwareVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'softwareVersion': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireDevicesV2Response. Returns the specified
// element and whether it was found
func (a WireDevicesV2Response) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireDevicesV2Response
func (a *WireDevicesV2Response) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireDevicesV2Response to handle AdditionalProperties
func (a *WireDevicesV2Response) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireDevicesV2Response to handle AdditionalProperties
func (a WireDevicesV2Response) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
