// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	alexaapimodels "github.com/portpowered/go-alexa/pkg/alexaapimodels"
)

// AssociatedUnitsFilter defines model for AssociatedUnitsFilter.
type AssociatedUnitsFilter struct {
	ID string `json:"id"`
}

// Capability defines model for Capability.
type Capability struct {
	Interface  string                 `json:"interface,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Type       string                 `json:"type"`
	Version    string                 `json:"version,omitempty"`
}

// Command defines model for Command.
type Command struct {
	DeviceID  string      `json:"device_id,omitempty"`
	Name      string      `json:"name,omitempty"`
	Namespace string      `json:"namespace,omitempty"`
	Payload   interface{} `json:"payload,omitempty"`
	Type      string      `json:"type"`
}

// Device defines model for Device.
type Device struct {
	Capabilities []string               `json:"capabilities,omitempty"`
	ID           string                 `json:"id"`
	Metadata     map[string]interface{} `json:"metadata,omitempty"`
	Name         string                 `json:"name"`
	State        map[string]interface{} `json:"state,omitempty"`
	Type         string                 `json:"type"`
}

// EndpointIncludeFields defines model for EndpointIncludeFields.
type EndpointIncludeFields struct {
	Capabilities bool `json:"capabilities,omitempty"`
	States       bool `json:"states,omitempty"`
}

// EndpointListResponse defines model for EndpointListResponse.
type EndpointListResponse struct {
	NextToken string   `json:"nextToken,omitempty"`
	Results   []Device `json:"results"`
}

// EndpointQuery defines model for EndpointQuery.
type EndpointQuery struct {
	AND               []EndpointQueryClause  `json:"and,omitempty"`
	IncludeFields     *EndpointIncludeFields `json:"includeFields,omitempty"`
	OR                []EndpointQueryClause  `json:"or,omitempty"`
	PaginationContext *PaginationContext     `json:"paginationContext,omitempty"`
}

// EndpointQueryClause defines model for EndpointQueryClause.
type EndpointQueryClause struct {
	AssociatedUnits *AssociatedUnitsFilter `json:"associatedUnits,omitempty"`
	Manufacturer    *StringFilter          `json:"manufacturer,omitempty"`
	Model           *StringFilter          `json:"model,omitempty"`
}

// EndpointQueryRequest defines model for EndpointQueryRequest.
type EndpointQueryRequest struct {
	Query EndpointQuery `json:"query"`
}

// FireTVOperationRequest defines model for FireTVOperationRequest.
type FireTVOperationRequest struct {
	Endpoint Endpoint `json:"-,omitempty"`
}

// FireTVRequest defines model for FireTVRequest.
type FireTVRequest struct {
	Endpoint Endpoint `json:"-,omitempty"`
}

// FriendlyNameRequest defines model for FriendlyNameRequest.
type FriendlyNameRequest struct {
	FriendlyName FriendlyNameValue `json:"friendlyName"`
}

// FriendlyNameText defines model for FriendlyNameText.
type FriendlyNameText struct {
	Text string `json:"text"`
}

// FriendlyNameValue defines model for FriendlyNameValue.
type FriendlyNameValue struct {
	Type  string           `json:"type"`
	Value FriendlyNameText `json:"value"`
}

// InterfaceMessageRequest defines model for InterfaceMessageRequest.
type InterfaceMessageRequest struct {
	Endpoint      Endpoint    `json:"-,omitempty"`
	FeatureName   string      `json:"featureName"`
	OperationName string      `json:"operationName"`
	Payload       interface{} `json:"payload,omitempty"`
}

// PaginationContext defines model for PaginationContext.
type PaginationContext struct {
	MaxResults        int    `json:"maxResults,omitempty"`
	NextToken         string `json:"nextToken,omitempty"`
	PerformPagination bool   `json:"performPagination,omitempty"`
}

// PlaybackControlRequest defines model for PlaybackControlRequest.
type PlaybackControlRequest struct {
	Endpoint   Endpoint `json:"-,omitempty"`
	CustomerID string   `json:"customerId,omitempty"`
	Operation  string   `json:"operation"`
}

// PowerControlRequest defines model for PowerControlRequest.
type PowerControlRequest struct {
	Endpoint Endpoint                  `json:"-,omitempty"`
	State    alexaapimodels.PowerState `json:"state"`
}

// SendAnnouncementRequest defines model for SendAnnouncementRequest.
type SendAnnouncementRequest struct {
	Endpoint      Endpoint       `json:"-,omitempty"`
	CustomerID    string         `json:"customerId,omitempty"`
	Locale        string         `json:"locale,omitempty"`
	Message       string         `json:"message"`
	Method        string         `json:"method"`
	TargetDevices []DeviceTarget `json:"targetDevices,omitempty"`
	Title         string         `json:"title,omitempty"`
}

// SendNotificationRequest defines model for SendNotificationRequest.
type SendNotificationRequest struct {
	Endpoint   Endpoint `json:"-,omitempty"`
	CustomerID string   `json:"customerId,omitempty"`
	Message    string   `json:"message"`
	Title      string   `json:"title"`
}

// SendTTSRequest defines model for SendTTSRequest.
type SendTTSRequest struct {
	Endpoint      Endpoint       `json:"-,omitempty"`
	CustomerID    string         `json:"customerId,omitempty"`
	Message       string         `json:"message"`
	TargetDevices []DeviceTarget `json:"targetDevices,omitempty"`
}

// StringFilter defines model for StringFilter.
type StringFilter struct {
	Value StringFilterValue `json:"value"`
}

// StringFilterValue defines model for StringFilterValue.
type StringFilterValue struct {
	Text string `json:"text"`
}
