// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"time"
)

// Event defines model for Event.
type Event struct {
	DeviceID  string                 `json:"device_id,omitempty"`
	ID        string                 `json:"id"`
	Payload   map[string]interface{} `json:"payload,omitempty"`
	Source    string                 `json:"source,omitempty"`
	Timestamp time.Time              `json:"timestamp"`
	Type      string                 `json:"type"`
}

// Message defines model for Message.
type Message struct {
	Data map[string]interface{} `json:"data,omitempty"`
}
