// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
	"fmt"
)

// ActionPayload The action name is caller- or device-defined. Additional top-level fields are caller-supplied action parameters and remain open by design.
//
// Example: {"action":"open","duration":12}
type ActionPayload struct {
	Action               string                 `json:"action"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// BrightnessAdjustPayload Example: {"brightnessDelta":-5}
type BrightnessAdjustPayload struct {
	BrightnessDelta int `json:"brightnessDelta"`
}

// BrightnessSetPayload Example: {"brightness":75}
type BrightnessSetPayload struct {
	Brightness int `json:"brightness"`
}

// ColorSetPayload Example: {"color":{"brightness":0.8,"hue":180,"saturation":0.5}}
type ColorSetPayload struct {
	// Color Example: {"brightness":0.8,"hue":180,"saturation":0.5}
	Color FeatureColorValue `json:"color"`
}

// ColorTemperatureSetPayload Example: {"colorTemperatureInKelvin":3200}
type ColorTemperatureSetPayload struct {
	ColorTemperatureInKelvin int `json:"colorTemperatureInKelvin"`
}

// ControlKnownLockStateValue Known LockStateValue values from the checked-in GraphQL schema. Future string values remain open.
//
// Example: LOCKED
type ControlKnownLockStateValue = string

// ControlKnownTemperatureScale Known TemperatureScale values from the checked-in GraphQL schema. Future string values remain open.
//
// Example: CELSIUS
type ControlKnownTemperatureScale = string

// ControlKnownThermostatModeValue Known ThermostatModeValue values from the checked-in GraphQL schema. Future string values remain open.
//
// Example: ECO
type ControlKnownThermostatModeValue = string

// ControlKnownToggleStateValue Known ToggleStateValue values from the checked-in GraphQL schema. Future string values remain open.
//
// Example: ON
type ControlKnownToggleStateValue = string

// FeatureColorValue Example: {"brightness":0.8,"hue":180,"saturation":0.5}
type FeatureColorValue struct {
	Brightness float64 `json:"brightness"`
	Hue        float64 `json:"hue"`
	Saturation float64 `json:"saturation"`
}

// FeatureEmptyPayload Empty object payload used by color-temperature adjustment.
//
// Example: {}
type FeatureEmptyPayload = struct{}

// LockPayload Example: {"lockState":"LOCKED"}
type LockPayload struct {
	// LockState Known LockStateValue values from the checked-in GraphQL schema. Future string values remain open.
	//
	// Example: LOCKED
	LockState ControlKnownLockStateValue `json:"lockState"`
}

// ModeAdjustPayload Example: {"modeDelta":"NEXT"}
type ModeAdjustPayload struct {
	// ModeDelta Device-specific adjustment supplied by the caller; no fixed provider-wide enum is assumed.
	ModeDelta string `json:"modeDelta"`
}

// ModeSetPayload Example: {"mode":"ECO"}
type ModeSetPayload struct {
	// Mode Device-specific mode supplied by the caller; no fixed provider-wide enum is assumed.
	Mode string `json:"mode"`
}

// PercentageAdjustPayload Example: {"percentageDelta":-5}
type PercentageAdjustPayload struct {
	PercentageDelta float64 `json:"percentageDelta"`
}

// PercentageSetPayload Example: {"percentage":25}
type PercentageSetPayload struct {
	Percentage float64 `json:"percentage"`
}

// PowerLevelAdjustPayload Example: {"powerLevelDelta":-8}
type PowerLevelAdjustPayload struct {
	PowerLevelDelta int `json:"powerLevelDelta"`
}

// PowerLevelSetPayload Example: {"powerLevel":68}
type PowerLevelSetPayload struct {
	PowerLevel int `json:"powerLevel"`
}

// RangeAdjustPayload Example: {"rangeValueDelta":-2.5}
type RangeAdjustPayload struct {
	RangeValueDelta float64 `json:"rangeValueDelta"`
}

// RangeSetPayload Example: {"rangeValue":12.5}
type RangeSetPayload struct {
	RangeValue float64 `json:"rangeValue"`
}

// SpeakerAdjustVolumePayload Example: {"volumeDelta":-4}
type SpeakerAdjustVolumePayload struct {
	VolumeDelta int `json:"volumeDelta"`
}

// SpeakerSetVolumePayload Example: {"volume":32}
type SpeakerSetVolumePayload struct {
	Volume int `json:"volume"`
}

// ThermostatModePayload Example: {"thermostatMode":"ECO"}
type ThermostatModePayload struct {
	// ThermostatMode Known ThermostatModeValue values from the checked-in GraphQL schema. Future string values remain open.
	//
	// Example: ECO
	ThermostatMode ControlKnownThermostatModeValue `json:"thermostatMode"`
}

// ThermostatSetpoint Example: {"scale":"CELSIUS","value":21.5}
type ThermostatSetpoint struct {
	// Scale Known TemperatureScale values from the checked-in GraphQL schema. Future string values remain open.
	//
	// Example: CELSIUS
	Scale ControlKnownTemperatureScale `json:"scale"`
	Value float64                      `json:"value"`
}

// ThermostatSetpointAdjustPayload Example: {"targetSetpointDelta":{"scale":"CELSIUS","value":-1}}
type ThermostatSetpointAdjustPayload struct {
	// TargetSetpointDelta Example: {"scale":"CELSIUS","value":21.5}
	TargetSetpointDelta ThermostatSetpoint `json:"targetSetpointDelta"`
}

// ThermostatSetpointSetPayload Example: {"targetSetpoint":{"scale":"CELSIUS","value":21.5}}
type ThermostatSetpointSetPayload struct {
	// TargetSetpoint Example: {"scale":"CELSIUS","value":21.5}
	TargetSetpoint ThermostatSetpoint `json:"targetSetpoint"`
}

// TogglePayload Example: {"toggleState":"ON"}
type TogglePayload struct {
	// ToggleState Known ToggleStateValue values from the checked-in GraphQL schema. Future string values remain open.
	//
	// Example: ON
	ToggleState ControlKnownToggleStateValue `json:"toggleState"`
}

// Getter for additional properties for ActionPayload. Returns the specified
// element and whether it was found
func (a ActionPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ActionPayload
func (a *ActionPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ActionPayload to handle AdditionalProperties
func (a *ActionPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ActionPayload to handle AdditionalProperties
func (a ActionPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["action"], err = json.Marshal(a.Action)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'action': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
