// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
)

// ActionStateProperty defines model for ActionStateProperty.
type ActionStateProperty struct {
	TypeName         string `json:"__typename"`
	Accuracy         string `json:"accuracy"`
	ActionStateValue *struct {
		ActionID     *string   `json:"actionId,omitempty"`
		Status       string    `json:"status"`
		TargetIDs    *[]string `json:"targetIds,omitempty"`
		TimeInterval *struct {
			Duration *string `json:"duration,omitempty"`
			End      *string `json:"end,omitempty"`
			Start    *string `json:"start,omitempty"`
		} `json:"timeInterval,omitempty"`
	} `json:"actionStateValue,omitempty"`
	Error            *EventPropertyError `json:"error,omitempty"`
	Name             string              `json:"name"`
	TimeOfLastChange string              `json:"timeOfLastChange"`
	TimeOfSample     string              `json:"timeOfSample"`
	Type             string              `json:"type"`
}

// ArmStateProperty defines model for ArmStateProperty.
type ArmStateProperty struct {
	TypeName         string              `json:"__typename"`
	Accuracy         string              `json:"accuracy"`
	ArmStateValue    string              `json:"armStateValue"`
	Error            *EventPropertyError `json:"error,omitempty"`
	Name             string              `json:"name"`
	TimeOfLastChange string              `json:"timeOfLastChange"`
	TimeOfSample     string              `json:"timeOfSample"`
	Type             string              `json:"type"`
}

// BatteryProperty defines model for BatteryProperty.
type BatteryProperty struct {
	TypeName     string `json:"__typename"`
	Accuracy     string `json:"accuracy"`
	BatteryValue *struct {
		ChargingHealth *struct {
			Reason *string `json:"reason,omitempty"`
			State  string  `json:"state"`
		} `json:"chargingHealth,omitempty"`
		Health *struct {
			Reasons []string `json:"reasons"`
			State   string   `json:"state"`
		} `json:"health,omitempty"`
		LevelPercentage *int `json:"levelPercentage,omitempty"`
	} `json:"batteryValue,omitempty"`
	Error            *EventPropertyError `json:"error,omitempty"`
	Name             string              `json:"name"`
	TimeOfLastChange string              `json:"timeOfLastChange"`
	TimeOfSample     string              `json:"timeOfSample"`
	Type             string              `json:"type"`
}

// BrightnessProperty defines model for BrightnessProperty.
type BrightnessProperty struct {
	TypeName             string              `json:"__typename"`
	Accuracy             string              `json:"accuracy"`
	BrightnessStateValue *int                `json:"brightnessStateValue,omitempty"`
	Error                *EventPropertyError `json:"error,omitempty"`
	Name                 string              `json:"name"`
	TimeOfSample         string              `json:"timeOfSample"`
	Type                 string              `json:"type"`
}

// ColorProperty defines model for ColorProperty.
type ColorProperty struct {
	TypeName        string `json:"__typename"`
	Accuracy        string `json:"accuracy"`
	ColorStateValue *struct {
		Brightness float64 `json:"brightness"`
		Hue        float64 `json:"hue"`
		Saturation float64 `json:"saturation"`
	} `json:"colorStateValue,omitempty"`
	Error        *EventPropertyError `json:"error,omitempty"`
	Name         string              `json:"name"`
	TimeOfSample string              `json:"timeOfSample"`
	Type         string              `json:"type"`
}

// ColorTemperatureProperty defines model for ColorTemperatureProperty.
type ColorTemperatureProperty struct {
	TypeName                           string              `json:"__typename"`
	Accuracy                           string              `json:"accuracy"`
	ColorTemperatureInKelvinStateValue *int                `json:"colorTemperatureInKelvinStateValue,omitempty"`
	Error                              *EventPropertyError `json:"error,omitempty"`
	Name                               string              `json:"name"`
	TimeOfSample                       string              `json:"timeOfSample"`
	Type                               string              `json:"type"`
}

// DetectionStateProperty defines model for DetectionStateProperty.
type DetectionStateProperty struct {
	TypeName            string              `json:"__typename"`
	Accuracy            string              `json:"accuracy"`
	DetectionStateValue string              `json:"detectionStateValue"`
	Error               *EventPropertyError `json:"error,omitempty"`
	Name                string              `json:"name"`
	TimeOfLastChange    string              `json:"timeOfLastChange"`
	TimeOfSample        string              `json:"timeOfSample"`
	Type                string              `json:"type"`
}

// EventPropertyError defines model for EventPropertyError.
type EventPropertyError struct {
	Type string `json:"type"`
}

// GeolocationProperty defines model for GeolocationProperty.
type GeolocationProperty struct {
	TypeName         string              `json:"__typename"`
	Accuracy         string              `json:"accuracy"`
	Error            *EventPropertyError `json:"error,omitempty"`
	GeolocationValue *struct {
		Altitude *struct {
			AccuracyInMeters *float64 `json:"accuracyInMeters,omitempty"`
			AltitudeInMeters float64  `json:"altitudeInMeters"`
		} `json:"altitude,omitempty"`
		Coordinate *struct {
			AccuracyInMeters   *float64 `json:"accuracyInMeters,omitempty"`
			LatitudeInDegrees  float64  `json:"latitudeInDegrees"`
			LongitudeInDegrees float64  `json:"longitudeInDegrees"`
		} `json:"coordinate,omitempty"`
		Heading *struct {
			AccuracyInDegrees  *float64 `json:"accuracyInDegrees,omitempty"`
			DirectionInDegrees float64  `json:"directionInDegrees"`
		} `json:"heading,omitempty"`
		Source *string `json:"source,omitempty"`
		Speed  *struct {
			AccuracyInMetersPerSecond *float64 `json:"accuracyInMetersPerSecond,omitempty"`
			SpeedInMetersPerSecond    float64  `json:"speedInMetersPerSecond"`
		} `json:"speed,omitempty"`
	} `json:"geolocationValue,omitempty"`
	Name             string `json:"name"`
	TimeOfLastChange string `json:"timeOfLastChange"`
	TimeOfSample     string `json:"timeOfSample"`
	Type             string `json:"type"`
}

// IlluminanceProperty defines model for IlluminanceProperty.
type IlluminanceProperty struct {
	TypeName         string              `json:"__typename"`
	Accuracy         string              `json:"accuracy"`
	Error            *EventPropertyError `json:"error,omitempty"`
	IlluminanceValue *struct {
		Value *float64 `json:"value,omitempty"`
	} `json:"illuminanceValue,omitempty"`
	Name             string `json:"name"`
	TimeOfLastChange string `json:"timeOfLastChange"`
	TimeOfSample     string `json:"timeOfSample"`
	Type             string `json:"type"`
}

// LockProperty defines model for LockProperty.
type LockProperty struct {
	TypeName     string              `json:"__typename"`
	Accuracy     string              `json:"accuracy"`
	Error        *EventPropertyError `json:"error,omitempty"`
	LockState    string              `json:"lockState"`
	Name         string              `json:"name"`
	TimeOfSample string              `json:"timeOfSample"`
	Type         string              `json:"type"`
}

// ModeProperty defines model for ModeProperty.
type ModeProperty struct {
	TypeName  string              `json:"__typename"`
	Accuracy  string              `json:"accuracy"`
	Error     *EventPropertyError `json:"error,omitempty"`
	ModeValue *struct {
		Value string `json:"value"`
	} `json:"modeValue,omitempty"`
	Name         string `json:"name"`
	TimeOfSample string `json:"timeOfSample"`
	Type         string `json:"type"`
}

// PercentageProperty defines model for PercentageProperty.
type PercentageProperty struct {
	TypeName        string              `json:"__typename"`
	Accuracy        string              `json:"accuracy"`
	Error           *EventPropertyError `json:"error,omitempty"`
	Name            string              `json:"name"`
	PercentageValue *int                `json:"percentageValue,omitempty"`
	TimeOfSample    string              `json:"timeOfSample"`
	Type            string              `json:"type"`
}

// PowerLevelProperty defines model for PowerLevelProperty.
type PowerLevelProperty struct {
	TypeName        string              `json:"__typename"`
	Accuracy        string              `json:"accuracy"`
	Error           *EventPropertyError `json:"error,omitempty"`
	Name            string              `json:"name"`
	PowerLevelValue *int                `json:"powerLevelValue,omitempty"`
	TimeOfSample    string              `json:"timeOfSample"`
	Type            string              `json:"type"`
}

// PowerProperty defines model for PowerProperty.
type PowerProperty struct {
	TypeName        string              `json:"__typename"`
	Accuracy        string              `json:"accuracy"`
	Error           *EventPropertyError `json:"error,omitempty"`
	Name            string              `json:"name"`
	PowerStateValue string              `json:"powerStateValue"`
	TimeOfSample    string              `json:"timeOfSample"`
	Type            string              `json:"type"`
}

// RangeProperty defines model for RangeProperty.
type RangeProperty struct {
	TypeName   string              `json:"__typename"`
	Accuracy   string              `json:"accuracy"`
	Error      *EventPropertyError `json:"error,omitempty"`
	Name       string              `json:"name"`
	RangeValue *struct {
		Value float64 `json:"value"`
	} `json:"rangeValue,omitempty"`
	TimeOfSample string `json:"timeOfSample"`
	Type         string `json:"type"`
}

// RawJSON defines model for RawJSON.
type RawJSON = json.RawMessage

// ReachabilityProperty defines model for ReachabilityProperty.
type ReachabilityProperty struct {
	TypeName                string              `json:"__typename"`
	Accuracy                string              `json:"accuracy"`
	Error                   *EventPropertyError `json:"error,omitempty"`
	Name                    string              `json:"name"`
	ReachabilityStatusValue string              `json:"reachabilityStatusValue"`
	TimeOfLastChange        string              `json:"timeOfLastChange"`
	TimeOfSample            string              `json:"timeOfSample"`
	Type                    string              `json:"type"`
}

// RelativeHumidityProperty defines model for RelativeHumidityProperty.
type RelativeHumidityProperty struct {
	TypeName              string              `json:"__typename"`
	Accuracy              string              `json:"accuracy"`
	Error                 *EventPropertyError `json:"error,omitempty"`
	Name                  string              `json:"name"`
	RelativeHumidityValue *struct {
		Value *float64 `json:"value,omitempty"`
	} `json:"relativeHumidityValue,omitempty"`
	TimeOfLastChange string `json:"timeOfLastChange"`
	TimeOfSample     string `json:"timeOfSample"`
	Type             string `json:"type"`
}

// ResourceMetadataPayload defines model for ResourceMetadataPayload.
type ResourceMetadataPayload struct {
	MetricName string  `json:"metricName"`
	Payload    RawJSON `json:"payload"`
	Timestamp  string  `json:"timestamp"`
	Type       string  `json:"type"`
}

// ResourceMetadataPayloadData defines model for ResourceMetadataPayloadData.
type ResourceMetadataPayloadData struct {
	Data struct {
		TypeName string `json:"__typename"`
		Features []struct {
			TypeName   string  `json:"__typename"`
			Instance   *string `json:"instance,omitempty"`
			Name       string  `json:"name"`
			Properties RawJSON `json:"properties"`
		} `json:"features"`
	} `json:"data"`
	Entity struct {
		TypeName string `json:"__typename"`
		ID       string `json:"id"`
	} `json:"entity"`
}

// SetpointProperty defines model for SetpointProperty.
type SetpointProperty struct {
	TypeName               string              `json:"__typename"`
	Accuracy               string              `json:"accuracy"`
	DeviceNativeScaleValue string              `json:"deviceNativeScaleValue"`
	Error                  *EventPropertyError `json:"error,omitempty"`
	Name                   string              `json:"name"`
	TimeOfLastChange       string              `json:"timeOfLastChange"`
	TimeOfSample           string              `json:"timeOfSample"`
	Type                   string              `json:"type"`
	Value                  *struct {
		Scale string  `json:"scale"`
		Value float64 `json:"value"`
	} `json:"value,omitempty"`
}

// SpeakerProperty defines model for SpeakerProperty.
type SpeakerProperty struct {
	TypeName     string              `json:"__typename"`
	Accuracy     string              `json:"accuracy"`
	Error        *EventPropertyError `json:"error,omitempty"`
	Muted        *bool               `json:"muted,omitempty"`
	Name         string              `json:"name"`
	TimeOfSample string              `json:"timeOfSample"`
	Type         string              `json:"type"`
	Volume       *int                `json:"volume,omitempty"`
}

// StatusCodeProperty defines model for StatusCodeProperty.
type StatusCodeProperty struct {
	TypeName        string              `json:"__typename"`
	Accuracy        string              `json:"accuracy"`
	Error           *EventPropertyError `json:"error,omitempty"`
	Name            string              `json:"name"`
	StatusCodeValue *struct {
		Value []struct {
			Code            *string `json:"code,omitempty"`
			TimeOfDetection *string `json:"timeOfDetection,omitempty"`
		} `json:"value"`
	} `json:"statusCodeValue,omitempty"`
	TimeOfLastChange string `json:"timeOfLastChange"`
	TimeOfSample     string `json:"timeOfSample"`
	Type             string `json:"type"`
}

// TemperatureSensorProperty defines model for TemperatureSensorProperty.
type TemperatureSensorProperty struct {
	TypeName         string              `json:"__typename"`
	Accuracy         string              `json:"accuracy"`
	Error            *EventPropertyError `json:"error,omitempty"`
	Name             string              `json:"name"`
	TimeOfLastChange string              `json:"timeOfLastChange"`
	TimeOfSample     string              `json:"timeOfSample"`
	Type             string              `json:"type"`
	Value            *struct {
		Scale string  `json:"scale"`
		Value float64 `json:"value"`
	} `json:"value,omitempty"`
}

// ThermostatModeProperty defines model for ThermostatModeProperty.
type ThermostatModeProperty struct {
	TypeName            string              `json:"__typename"`
	Accuracy            string              `json:"accuracy"`
	Error               *EventPropertyError `json:"error,omitempty"`
	Name                string              `json:"name"`
	ThermostatModeValue string              `json:"thermostatModeValue"`
	TimeOfLastChange    string              `json:"timeOfLastChange"`
	TimeOfSample        string              `json:"timeOfSample"`
	Type                string              `json:"type"`
}

// ToggleProperty defines model for ToggleProperty.
type ToggleProperty struct {
	TypeName         string              `json:"__typename"`
	Accuracy         string              `json:"accuracy"`
	Error            *EventPropertyError `json:"error,omitempty"`
	Name             string              `json:"name"`
	TimeOfSample     string              `json:"timeOfSample"`
	ToggleStateValue string              `json:"toggleStateValue"`
	Type             string              `json:"type"`
}
