// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
	"fmt"
)

// ActionPayload The action name is library-defined. Additional top-level fields are caller-supplied action parameters and remain open by design.
type ActionPayload struct {
	Action               string                 `json:"action"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// BrightnessAdjustPayload defines model for BrightnessAdjustPayload.
type BrightnessAdjustPayload struct {
	BrightnessDelta int `json:"brightnessDelta"`
}

// BrightnessSetPayload defines model for BrightnessSetPayload.
type BrightnessSetPayload struct {
	Brightness int `json:"brightness"`
}

// ColorSetPayload defines model for ColorSetPayload.
type ColorSetPayload struct {
	Color FeatureColorValue `json:"color"`
}

// ColorTemperatureSetPayload defines model for ColorTemperatureSetPayload.
type ColorTemperatureSetPayload struct {
	ColorTemperatureInKelvin int `json:"colorTemperatureInKelvin"`
}

// FeatureColorValue defines model for FeatureColorValue.
type FeatureColorValue struct {
	Brightness float64 `json:"brightness"`
	Hue        float64 `json:"hue"`
	Saturation float64 `json:"saturation"`
}

// FeatureEmptyPayload Empty object payload used by color-temperature adjustment.
type FeatureEmptyPayload = struct{}

// LockPayload defines model for LockPayload.
type LockPayload struct {
	LockState string `json:"lockState"`
}

// ModeAdjustPayload defines model for ModeAdjustPayload.
type ModeAdjustPayload struct {
	ModeDelta string `json:"modeDelta"`
}

// ModeSetPayload defines model for ModeSetPayload.
type ModeSetPayload struct {
	Mode string `json:"mode"`
}

// PercentageAdjustPayload defines model for PercentageAdjustPayload.
type PercentageAdjustPayload struct {
	PercentageDelta float64 `json:"percentageDelta"`
}

// PercentageSetPayload defines model for PercentageSetPayload.
type PercentageSetPayload struct {
	Percentage float64 `json:"percentage"`
}

// PowerLevelAdjustPayload defines model for PowerLevelAdjustPayload.
type PowerLevelAdjustPayload struct {
	PowerLevelDelta int `json:"powerLevelDelta"`
}

// PowerLevelSetPayload defines model for PowerLevelSetPayload.
type PowerLevelSetPayload struct {
	PowerLevel int `json:"powerLevel"`
}

// RangeAdjustPayload defines model for RangeAdjustPayload.
type RangeAdjustPayload struct {
	RangeValueDelta float64 `json:"rangeValueDelta"`
}

// RangeSetPayload defines model for RangeSetPayload.
type RangeSetPayload struct {
	RangeValue float64 `json:"rangeValue"`
}

// SpeakerAdjustVolumePayload defines model for SpeakerAdjustVolumePayload.
type SpeakerAdjustVolumePayload struct {
	VolumeDelta int `json:"volumeDelta"`
}

// SpeakerSetVolumePayload defines model for SpeakerSetVolumePayload.
type SpeakerSetVolumePayload struct {
	Volume int `json:"volume"`
}

// ThermostatModePayload defines model for ThermostatModePayload.
type ThermostatModePayload struct {
	ThermostatMode string `json:"thermostatMode"`
}

// ThermostatSetpoint defines model for ThermostatSetpoint.
type ThermostatSetpoint struct {
	Scale string  `json:"scale"`
	Value float64 `json:"value"`
}

// ThermostatSetpointAdjustPayload defines model for ThermostatSetpointAdjustPayload.
type ThermostatSetpointAdjustPayload struct {
	TargetSetpointDelta ThermostatSetpoint `json:"targetSetpointDelta"`
}

// ThermostatSetpointSetPayload defines model for ThermostatSetpointSetPayload.
type ThermostatSetpointSetPayload struct {
	TargetSetpoint ThermostatSetpoint `json:"targetSetpoint"`
}

// TogglePayload defines model for TogglePayload.
type TogglePayload struct {
	ToggleState string `json:"toggleState"`
}

// Getter for additional properties for ActionPayload. Returns the specified
// element and whether it was found
func (a ActionPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ActionPayload
func (a *ActionPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ActionPayload to handle AdditionalProperties
func (a *ActionPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["action"]; found {
		err = json.Unmarshal(raw, &a.Action)
		if err != nil {
			return fmt.Errorf("error reading 'action': %w", err)
		}
		delete(object, "action")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ActionPayload to handle AdditionalProperties
func (a ActionPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["action"], err = json.Marshal(a.Action)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'action': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
