// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for WireMediaCommandType.
const (
	WireMediaCommandTypeForward  WireMediaCommandType = "ForwardCommand"
	WireMediaCommandTypeNext     WireMediaCommandType = "NextCommand"
	WireMediaCommandTypePause    WireMediaCommandType = "PauseCommand"
	WireMediaCommandTypePlay     WireMediaCommandType = "PlayCommand"
	WireMediaCommandTypePrevious WireMediaCommandType = "PreviousCommand"
	WireMediaCommandTypeRepeat   WireMediaCommandType = "RepeatCommand"
	WireMediaCommandTypeRewind   WireMediaCommandType = "RewindCommand"
	WireMediaCommandTypeShuffle  WireMediaCommandType = "ShuffleCommand"
)

// Valid indicates whether the value is a known member of the WireMediaCommandType enum.
func (e WireMediaCommandType) Valid() bool {
	switch e {
	case WireMediaCommandTypeForward:
		return true
	case WireMediaCommandTypeNext:
		return true
	case WireMediaCommandTypePause:
		return true
	case WireMediaCommandTypePlay:
		return true
	case WireMediaCommandTypePrevious:
		return true
	case WireMediaCommandTypeRepeat:
		return true
	case WireMediaCommandTypeRewind:
		return true
	case WireMediaCommandTypeShuffle:
		return true
	default:
		return false
	}
}

// WireArt defines model for WireArt.
type WireArt struct {
	AltText              *string                `json:"altText,omitempty"`
	ArtType              *string                `json:"artType,omitempty"`
	ContentType          *string                `json:"contentType,omitempty"`
	IconId               *string                `json:"iconId,omitempty"`
	IconStyles           *string                `json:"iconStyles,omitempty"`
	Url                  *string                `json:"url,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireInfoText defines model for WireInfoText.
type WireInfoText struct {
	Header               *string                `json:"header,omitempty"`
	HeaderSubtext1       *string                `json:"headerSubtext1,omitempty"`
	MultiLineMode        *bool                  `json:"multiLineMode,omitempty"`
	SubText1             *string                `json:"subText1,omitempty"`
	SubText2             *string                `json:"subText2,omitempty"`
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireMediaCommand Example: {"type":"PauseCommand"}
type WireMediaCommand struct {
	Repeat  *bool `json:"repeat,omitempty"`
	Shuffle *bool `json:"shuffle,omitempty"`

	// Type Implementation-derived media command values used by the client.
	Type WireMediaCommandType `json:"type"`
}

// WireMediaCommandType Implementation-derived media command values used by the client.
type WireMediaCommandType string

// WirePlayerInfo defines model for WirePlayerInfo.
type WirePlayerInfo struct {
	Hint                 *string                `json:"hint,omitempty"`
	InfoText             *WireInfoText          `json:"infoText,omitempty"`
	IsPlayingInLemur     *bool                  `json:"isPlayingInLemur,omitempty"`
	LemurVolume          *int                   `json:"lemurVolume,omitempty"`
	Lyrics               *string                `json:"lyrics,omitempty"`
	MainArt              *WireArt               `json:"mainArt,omitempty"`
	MediaId              *string                `json:"mediaId,omitempty"`
	MiniArt              *WireArt               `json:"miniArt,omitempty"`
	MiniInfoText         *WireInfoText          `json:"miniInfoText,omitempty"`
	PlaybackSource       *string                `json:"playbackSource,omitempty"`
	PlayingInLemurId     *string                `json:"playingInLemurId,omitempty"`
	Progress             *WireProgress          `json:"progress,omitempty"`
	Provider             *WireProvider          `json:"provider,omitempty"`
	Quality              *string                `json:"quality,omitempty"`
	QueueId              *string                `json:"queueId,omitempty"`
	State                *string                `json:"state,omitempty"`
	Template             *WireTemplate          `json:"template,omitempty"`
	Transport            *WireTransport         `json:"transport,omitempty"`
	UpNextItems          interface{}            `json:"upNextItems,omitempty"`
	Volume               *WireVolume            `json:"volume,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WirePlayerStateResponse Example: {"playerInfo":{"hint":"Synthetic player state","infoText":{"multiLineMode":false,"subText1":"Synthetic subtitle","title":"Synthetic title"},"isPlayingInLemur":false,"mainArt":{"altText":"Synthetic artwork","contentType":"image/png","url":"https://images.example.invalid/synthetic.png"},"mediaId":"synthetic-media","progress":{"allowScrubbing":false,"mediaLength":180,"mediaProgress":45,"showTiming":true,"visible":true},"provider":{"providerDisplayName":"Synthetic provider","providerName":"synthetic"},"state":"PAUSED","template":{"templateType":"SYNTHETIC"},"transport":{"playPause":"SYNTHETIC_CONTROL"},"upNextItems":[],"volume":{"muted":false,"volume":32}}}
type WirePlayerStateResponse struct {
	PlayerInfo           *WirePlayerInfo        `json:"playerInfo,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireProgress defines model for WireProgress.
type WireProgress struct {
	AllowScrubbing       *bool                  `json:"allowScrubbing,omitempty"`
	LocationInfo         *string                `json:"locationInfo,omitempty"`
	MediaLength          *int                   `json:"mediaLength,omitempty"`
	MediaProgress        *int                   `json:"mediaProgress,omitempty"`
	ShowTiming           *bool                  `json:"showTiming,omitempty"`
	Visible              *bool                  `json:"visible,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireProvider defines model for WireProvider.
type WireProvider struct {
	ArtOverlay           *WireArt               `json:"artOverlay,omitempty"`
	FallbackMainArt      *WireArt               `json:"fallbackMainArt,omitempty"`
	ProviderDisplayName  *string                `json:"providerDisplayName,omitempty"`
	ProviderLogo         *WireArt               `json:"providerLogo,omitempty"`
	ProviderName         *string                `json:"providerName,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireRateContentAction defines model for WireRateContentAction.
type WireRateContentAction struct {
	MediaOwnerCustomerId *string                `json:"mediaOwnerCustomerId,omitempty"`
	Rating               *string                `json:"rating,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireTemplate defines model for WireTemplate.
type WireTemplate struct {
	Art                  *WireArt               `json:"art,omitempty"`
	BackgroundImageUrl   *string                `json:"backgroundImageUrl,omitempty"`
	TemplateType         *string                `json:"templateType,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireTransport defines model for WireTransport.
type WireTransport struct {
	ClosedCaptions       *string                `json:"closedCaptions,omitempty"`
	LayoutType           *string                `json:"layoutType,omitempty"`
	Lyrics               *string                `json:"lyrics,omitempty"`
	Next                 *string                `json:"next,omitempty"`
	PlayPause            *string                `json:"playPause,omitempty"`
	Previous             *string                `json:"previous,omitempty"`
	RateContentAction    *WireRateContentAction `json:"rateContentAction,omitempty"`
	ThumbsDown           *string                `json:"thumbsDown,omitempty"`
	ThumbsUp             *string                `json:"thumbsUp,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireVolume defines model for WireVolume.
type WireVolume struct {
	Muted                *bool                  `json:"muted,omitempty"`
	Volume               *int                   `json:"volume,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceSerialNumber defines model for DeviceSerialNumber.
type DeviceSerialNumber = string

// DeviceType defines model for DeviceType.
type DeviceType = string

// SendMediaCommandParams defines parameters for SendMediaCommand.
type SendMediaCommandParams struct {
	// DeviceSerialNumber Derived from the endpoint object by the media helper.
	DeviceSerialNumber DeviceSerialNumber `form:"deviceSerialNumber" json:"deviceSerialNumber"`

	// DeviceType Derived from the endpoint object by the media helper.
	DeviceType DeviceType `form:"deviceType" json:"deviceType"`
}

// GetMediaPlayerStateParams defines parameters for GetMediaPlayerState.
type GetMediaPlayerStateParams struct {
	// DeviceSerialNumber Derived from the endpoint object by the media helper.
	DeviceSerialNumber DeviceSerialNumber `form:"deviceSerialNumber" json:"deviceSerialNumber"`

	// DeviceType Derived from the endpoint object by the media helper.
	DeviceType DeviceType `form:"deviceType" json:"deviceType"`
}

// SendMediaCommandJSONRequestBody defines body for SendMediaCommand for application/json ContentType.
type SendMediaCommandJSONRequestBody = WireMediaCommand

// Getter for additional properties for WireArt. Returns the specified
// element and whether it was found
func (a WireArt) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireArt
func (a *WireArt) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireArt to handle AdditionalProperties
func (a *WireArt) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["altText"]; found {
		err = json.Unmarshal(raw, &a.AltText)
		if err != nil {
			return fmt.Errorf("error reading 'altText': %w", err)
		}
		delete(object, "altText")
	}

	if raw, found := object["artType"]; found {
		err = json.Unmarshal(raw, &a.ArtType)
		if err != nil {
			return fmt.Errorf("error reading 'artType': %w", err)
		}
		delete(object, "artType")
	}

	if raw, found := object["contentType"]; found {
		err = json.Unmarshal(raw, &a.ContentType)
		if err != nil {
			return fmt.Errorf("error reading 'contentType': %w", err)
		}
		delete(object, "contentType")
	}

	if raw, found := object["iconId"]; found {
		err = json.Unmarshal(raw, &a.IconId)
		if err != nil {
			return fmt.Errorf("error reading 'iconId': %w", err)
		}
		delete(object, "iconId")
	}

	if raw, found := object["iconStyles"]; found {
		err = json.Unmarshal(raw, &a.IconStyles)
		if err != nil {
			return fmt.Errorf("error reading 'iconStyles': %w", err)
		}
		delete(object, "iconStyles")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireArt to handle AdditionalProperties
func (a WireArt) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AltText != nil {
		object["altText"], err = json.Marshal(a.AltText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'altText': %w", err)
		}
	}

	if a.ArtType != nil {
		object["artType"], err = json.Marshal(a.ArtType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'artType': %w", err)
		}
	}

	if a.ContentType != nil {
		object["contentType"], err = json.Marshal(a.ContentType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'contentType': %w", err)
		}
	}

	if a.IconId != nil {
		object["iconId"], err = json.Marshal(a.IconId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconId': %w", err)
		}
	}

	if a.IconStyles != nil {
		object["iconStyles"], err = json.Marshal(a.IconStyles)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconStyles': %w", err)
		}
	}

	if a.Url != nil {
		object["url"], err = json.Marshal(a.Url)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'url': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireInfoText. Returns the specified
// element and whether it was found
func (a WireInfoText) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireInfoText
func (a *WireInfoText) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireInfoText to handle AdditionalProperties
func (a *WireInfoText) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["header"]; found {
		err = json.Unmarshal(raw, &a.Header)
		if err != nil {
			return fmt.Errorf("error reading 'header': %w", err)
		}
		delete(object, "header")
	}

	if raw, found := object["headerSubtext1"]; found {
		err = json.Unmarshal(raw, &a.HeaderSubtext1)
		if err != nil {
			return fmt.Errorf("error reading 'headerSubtext1': %w", err)
		}
		delete(object, "headerSubtext1")
	}

	if raw, found := object["multiLineMode"]; found {
		err = json.Unmarshal(raw, &a.MultiLineMode)
		if err != nil {
			return fmt.Errorf("error reading 'multiLineMode': %w", err)
		}
		delete(object, "multiLineMode")
	}

	if raw, found := object["subText1"]; found {
		err = json.Unmarshal(raw, &a.SubText1)
		if err != nil {
			return fmt.Errorf("error reading 'subText1': %w", err)
		}
		delete(object, "subText1")
	}

	if raw, found := object["subText2"]; found {
		err = json.Unmarshal(raw, &a.SubText2)
		if err != nil {
			return fmt.Errorf("error reading 'subText2': %w", err)
		}
		delete(object, "subText2")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireInfoText to handle AdditionalProperties
func (a WireInfoText) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Header != nil {
		object["header"], err = json.Marshal(a.Header)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'header': %w", err)
		}
	}

	if a.HeaderSubtext1 != nil {
		object["headerSubtext1"], err = json.Marshal(a.HeaderSubtext1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'headerSubtext1': %w", err)
		}
	}

	if a.MultiLineMode != nil {
		object["multiLineMode"], err = json.Marshal(a.MultiLineMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multiLineMode': %w", err)
		}
	}

	if a.SubText1 != nil {
		object["subText1"], err = json.Marshal(a.SubText1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subText1': %w", err)
		}
	}

	if a.SubText2 != nil {
		object["subText2"], err = json.Marshal(a.SubText2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subText2': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WirePlayerInfo. Returns the specified
// element and whether it was found
func (a WirePlayerInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WirePlayerInfo
func (a *WirePlayerInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WirePlayerInfo to handle AdditionalProperties
func (a *WirePlayerInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["hint"]; found {
		err = json.Unmarshal(raw, &a.Hint)
		if err != nil {
			return fmt.Errorf("error reading 'hint': %w", err)
		}
		delete(object, "hint")
	}

	if raw, found := object["infoText"]; found {
		err = json.Unmarshal(raw, &a.InfoText)
		if err != nil {
			return fmt.Errorf("error reading 'infoText': %w", err)
		}
		delete(object, "infoText")
	}

	if raw, found := object["isPlayingInLemur"]; found {
		err = json.Unmarshal(raw, &a.IsPlayingInLemur)
		if err != nil {
			return fmt.Errorf("error reading 'isPlayingInLemur': %w", err)
		}
		delete(object, "isPlayingInLemur")
	}

	if raw, found := object["lemurVolume"]; found {
		err = json.Unmarshal(raw, &a.LemurVolume)
		if err != nil {
			return fmt.Errorf("error reading 'lemurVolume': %w", err)
		}
		delete(object, "lemurVolume")
	}

	if raw, found := object["lyrics"]; found {
		err = json.Unmarshal(raw, &a.Lyrics)
		if err != nil {
			return fmt.Errorf("error reading 'lyrics': %w", err)
		}
		delete(object, "lyrics")
	}

	if raw, found := object["mainArt"]; found {
		err = json.Unmarshal(raw, &a.MainArt)
		if err != nil {
			return fmt.Errorf("error reading 'mainArt': %w", err)
		}
		delete(object, "mainArt")
	}

	if raw, found := object["mediaId"]; found {
		err = json.Unmarshal(raw, &a.MediaId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaId': %w", err)
		}
		delete(object, "mediaId")
	}

	if raw, found := object["miniArt"]; found {
		err = json.Unmarshal(raw, &a.MiniArt)
		if err != nil {
			return fmt.Errorf("error reading 'miniArt': %w", err)
		}
		delete(object, "miniArt")
	}

	if raw, found := object["miniInfoText"]; found {
		err = json.Unmarshal(raw, &a.MiniInfoText)
		if err != nil {
			return fmt.Errorf("error reading 'miniInfoText': %w", err)
		}
		delete(object, "miniInfoText")
	}

	if raw, found := object["playbackSource"]; found {
		err = json.Unmarshal(raw, &a.PlaybackSource)
		if err != nil {
			return fmt.Errorf("error reading 'playbackSource': %w", err)
		}
		delete(object, "playbackSource")
	}

	if raw, found := object["playingInLemurId"]; found {
		err = json.Unmarshal(raw, &a.PlayingInLemurId)
		if err != nil {
			return fmt.Errorf("error reading 'playingInLemurId': %w", err)
		}
		delete(object, "playingInLemurId")
	}

	if raw, found := object["progress"]; found {
		err = json.Unmarshal(raw, &a.Progress)
		if err != nil {
			return fmt.Errorf("error reading 'progress': %w", err)
		}
		delete(object, "progress")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if raw, found := object["quality"]; found {
		err = json.Unmarshal(raw, &a.Quality)
		if err != nil {
			return fmt.Errorf("error reading 'quality': %w", err)
		}
		delete(object, "quality")
	}

	if raw, found := object["queueId"]; found {
		err = json.Unmarshal(raw, &a.QueueId)
		if err != nil {
			return fmt.Errorf("error reading 'queueId': %w", err)
		}
		delete(object, "queueId")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["template"]; found {
		err = json.Unmarshal(raw, &a.Template)
		if err != nil {
			return fmt.Errorf("error reading 'template': %w", err)
		}
		delete(object, "template")
	}

	if raw, found := object["transport"]; found {
		err = json.Unmarshal(raw, &a.Transport)
		if err != nil {
			return fmt.Errorf("error reading 'transport': %w", err)
		}
		delete(object, "transport")
	}

	if raw, found := object["upNextItems"]; found {
		err = json.Unmarshal(raw, &a.UpNextItems)
		if err != nil {
			return fmt.Errorf("error reading 'upNextItems': %w", err)
		}
		delete(object, "upNextItems")
	}

	if raw, found := object["volume"]; found {
		err = json.Unmarshal(raw, &a.Volume)
		if err != nil {
			return fmt.Errorf("error reading 'volume': %w", err)
		}
		delete(object, "volume")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WirePlayerInfo to handle AdditionalProperties
func (a WirePlayerInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Hint != nil {
		object["hint"], err = json.Marshal(a.Hint)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hint': %w", err)
		}
	}

	if a.InfoText != nil {
		object["infoText"], err = json.Marshal(a.InfoText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'infoText': %w", err)
		}
	}

	if a.IsPlayingInLemur != nil {
		object["isPlayingInLemur"], err = json.Marshal(a.IsPlayingInLemur)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isPlayingInLemur': %w", err)
		}
	}

	if a.LemurVolume != nil {
		object["lemurVolume"], err = json.Marshal(a.LemurVolume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lemurVolume': %w", err)
		}
	}

	if a.Lyrics != nil {
		object["lyrics"], err = json.Marshal(a.Lyrics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lyrics': %w", err)
		}
	}

	if a.MainArt != nil {
		object["mainArt"], err = json.Marshal(a.MainArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mainArt': %w", err)
		}
	}

	if a.MediaId != nil {
		object["mediaId"], err = json.Marshal(a.MediaId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaId': %w", err)
		}
	}

	if a.MiniArt != nil {
		object["miniArt"], err = json.Marshal(a.MiniArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'miniArt': %w", err)
		}
	}

	if a.MiniInfoText != nil {
		object["miniInfoText"], err = json.Marshal(a.MiniInfoText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'miniInfoText': %w", err)
		}
	}

	if a.PlaybackSource != nil {
		object["playbackSource"], err = json.Marshal(a.PlaybackSource)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playbackSource': %w", err)
		}
	}

	if a.PlayingInLemurId != nil {
		object["playingInLemurId"], err = json.Marshal(a.PlayingInLemurId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playingInLemurId': %w", err)
		}
	}

	if a.Progress != nil {
		object["progress"], err = json.Marshal(a.Progress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'progress': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Quality != nil {
		object["quality"], err = json.Marshal(a.Quality)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'quality': %w", err)
		}
	}

	if a.QueueId != nil {
		object["queueId"], err = json.Marshal(a.QueueId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'queueId': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.Template != nil {
		object["template"], err = json.Marshal(a.Template)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'template': %w", err)
		}
	}

	if a.Transport != nil {
		object["transport"], err = json.Marshal(a.Transport)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'transport': %w", err)
		}
	}

	object["upNextItems"], err = json.Marshal(a.UpNextItems)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'upNextItems': %w", err)
	}

	if a.Volume != nil {
		object["volume"], err = json.Marshal(a.Volume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WirePlayerStateResponse. Returns the specified
// element and whether it was found
func (a WirePlayerStateResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WirePlayerStateResponse
func (a *WirePlayerStateResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WirePlayerStateResponse to handle AdditionalProperties
func (a *WirePlayerStateResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["playerInfo"]; found {
		err = json.Unmarshal(raw, &a.PlayerInfo)
		if err != nil {
			return fmt.Errorf("error reading 'playerInfo': %w", err)
		}
		delete(object, "playerInfo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WirePlayerStateResponse to handle AdditionalProperties
func (a WirePlayerStateResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PlayerInfo != nil {
		object["playerInfo"], err = json.Marshal(a.PlayerInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playerInfo': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireProgress. Returns the specified
// element and whether it was found
func (a WireProgress) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireProgress
func (a *WireProgress) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireProgress to handle AdditionalProperties
func (a *WireProgress) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["allowScrubbing"]; found {
		err = json.Unmarshal(raw, &a.AllowScrubbing)
		if err != nil {
			return fmt.Errorf("error reading 'allowScrubbing': %w", err)
		}
		delete(object, "allowScrubbing")
	}

	if raw, found := object["locationInfo"]; found {
		err = json.Unmarshal(raw, &a.LocationInfo)
		if err != nil {
			return fmt.Errorf("error reading 'locationInfo': %w", err)
		}
		delete(object, "locationInfo")
	}

	if raw, found := object["mediaLength"]; found {
		err = json.Unmarshal(raw, &a.MediaLength)
		if err != nil {
			return fmt.Errorf("error reading 'mediaLength': %w", err)
		}
		delete(object, "mediaLength")
	}

	if raw, found := object["mediaProgress"]; found {
		err = json.Unmarshal(raw, &a.MediaProgress)
		if err != nil {
			return fmt.Errorf("error reading 'mediaProgress': %w", err)
		}
		delete(object, "mediaProgress")
	}

	if raw, found := object["showTiming"]; found {
		err = json.Unmarshal(raw, &a.ShowTiming)
		if err != nil {
			return fmt.Errorf("error reading 'showTiming': %w", err)
		}
		delete(object, "showTiming")
	}

	if raw, found := object["visible"]; found {
		err = json.Unmarshal(raw, &a.Visible)
		if err != nil {
			return fmt.Errorf("error reading 'visible': %w", err)
		}
		delete(object, "visible")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireProgress to handle AdditionalProperties
func (a WireProgress) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AllowScrubbing != nil {
		object["allowScrubbing"], err = json.Marshal(a.AllowScrubbing)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'allowScrubbing': %w", err)
		}
	}

	if a.LocationInfo != nil {
		object["locationInfo"], err = json.Marshal(a.LocationInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationInfo': %w", err)
		}
	}

	if a.MediaLength != nil {
		object["mediaLength"], err = json.Marshal(a.MediaLength)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaLength': %w", err)
		}
	}

	if a.MediaProgress != nil {
		object["mediaProgress"], err = json.Marshal(a.MediaProgress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaProgress': %w", err)
		}
	}

	if a.ShowTiming != nil {
		object["showTiming"], err = json.Marshal(a.ShowTiming)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'showTiming': %w", err)
		}
	}

	if a.Visible != nil {
		object["visible"], err = json.Marshal(a.Visible)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'visible': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireProvider. Returns the specified
// element and whether it was found
func (a WireProvider) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireProvider
func (a *WireProvider) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireProvider to handle AdditionalProperties
func (a *WireProvider) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["artOverlay"]; found {
		err = json.Unmarshal(raw, &a.ArtOverlay)
		if err != nil {
			return fmt.Errorf("error reading 'artOverlay': %w", err)
		}
		delete(object, "artOverlay")
	}

	if raw, found := object["fallbackMainArt"]; found {
		err = json.Unmarshal(raw, &a.FallbackMainArt)
		if err != nil {
			return fmt.Errorf("error reading 'fallbackMainArt': %w", err)
		}
		delete(object, "fallbackMainArt")
	}

	if raw, found := object["providerDisplayName"]; found {
		err = json.Unmarshal(raw, &a.ProviderDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'providerDisplayName': %w", err)
		}
		delete(object, "providerDisplayName")
	}

	if raw, found := object["providerLogo"]; found {
		err = json.Unmarshal(raw, &a.ProviderLogo)
		if err != nil {
			return fmt.Errorf("error reading 'providerLogo': %w", err)
		}
		delete(object, "providerLogo")
	}

	if raw, found := object["providerName"]; found {
		err = json.Unmarshal(raw, &a.ProviderName)
		if err != nil {
			return fmt.Errorf("error reading 'providerName': %w", err)
		}
		delete(object, "providerName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireProvider to handle AdditionalProperties
func (a WireProvider) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ArtOverlay != nil {
		object["artOverlay"], err = json.Marshal(a.ArtOverlay)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'artOverlay': %w", err)
		}
	}

	if a.FallbackMainArt != nil {
		object["fallbackMainArt"], err = json.Marshal(a.FallbackMainArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fallbackMainArt': %w", err)
		}
	}

	if a.ProviderDisplayName != nil {
		object["providerDisplayName"], err = json.Marshal(a.ProviderDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerDisplayName': %w", err)
		}
	}

	if a.ProviderLogo != nil {
		object["providerLogo"], err = json.Marshal(a.ProviderLogo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerLogo': %w", err)
		}
	}

	if a.ProviderName != nil {
		object["providerName"], err = json.Marshal(a.ProviderName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireRateContentAction. Returns the specified
// element and whether it was found
func (a WireRateContentAction) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireRateContentAction
func (a *WireRateContentAction) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireRateContentAction to handle AdditionalProperties
func (a *WireRateContentAction) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["mediaOwnerCustomerId"]; found {
		err = json.Unmarshal(raw, &a.MediaOwnerCustomerId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaOwnerCustomerId': %w", err)
		}
		delete(object, "mediaOwnerCustomerId")
	}

	if raw, found := object["rating"]; found {
		err = json.Unmarshal(raw, &a.Rating)
		if err != nil {
			return fmt.Errorf("error reading 'rating': %w", err)
		}
		delete(object, "rating")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireRateContentAction to handle AdditionalProperties
func (a WireRateContentAction) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MediaOwnerCustomerId != nil {
		object["mediaOwnerCustomerId"], err = json.Marshal(a.MediaOwnerCustomerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaOwnerCustomerId': %w", err)
		}
	}

	if a.Rating != nil {
		object["rating"], err = json.Marshal(a.Rating)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rating': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireTemplate. Returns the specified
// element and whether it was found
func (a WireTemplate) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireTemplate
func (a *WireTemplate) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireTemplate to handle AdditionalProperties
func (a *WireTemplate) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["art"]; found {
		err = json.Unmarshal(raw, &a.Art)
		if err != nil {
			return fmt.Errorf("error reading 'art': %w", err)
		}
		delete(object, "art")
	}

	if raw, found := object["backgroundImageUrl"]; found {
		err = json.Unmarshal(raw, &a.BackgroundImageUrl)
		if err != nil {
			return fmt.Errorf("error reading 'backgroundImageUrl': %w", err)
		}
		delete(object, "backgroundImageUrl")
	}

	if raw, found := object["templateType"]; found {
		err = json.Unmarshal(raw, &a.TemplateType)
		if err != nil {
			return fmt.Errorf("error reading 'templateType': %w", err)
		}
		delete(object, "templateType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireTemplate to handle AdditionalProperties
func (a WireTemplate) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Art != nil {
		object["art"], err = json.Marshal(a.Art)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'art': %w", err)
		}
	}

	if a.BackgroundImageUrl != nil {
		object["backgroundImageUrl"], err = json.Marshal(a.BackgroundImageUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backgroundImageUrl': %w", err)
		}
	}

	if a.TemplateType != nil {
		object["templateType"], err = json.Marshal(a.TemplateType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'templateType': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireTransport. Returns the specified
// element and whether it was found
func (a WireTransport) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireTransport
func (a *WireTransport) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireTransport to handle AdditionalProperties
func (a *WireTransport) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["closedCaptions"]; found {
		err = json.Unmarshal(raw, &a.ClosedCaptions)
		if err != nil {
			return fmt.Errorf("error reading 'closedCaptions': %w", err)
		}
		delete(object, "closedCaptions")
	}

	if raw, found := object["layoutType"]; found {
		err = json.Unmarshal(raw, &a.LayoutType)
		if err != nil {
			return fmt.Errorf("error reading 'layoutType': %w", err)
		}
		delete(object, "layoutType")
	}

	if raw, found := object["lyrics"]; found {
		err = json.Unmarshal(raw, &a.Lyrics)
		if err != nil {
			return fmt.Errorf("error reading 'lyrics': %w", err)
		}
		delete(object, "lyrics")
	}

	if raw, found := object["next"]; found {
		err = json.Unmarshal(raw, &a.Next)
		if err != nil {
			return fmt.Errorf("error reading 'next': %w", err)
		}
		delete(object, "next")
	}

	if raw, found := object["playPause"]; found {
		err = json.Unmarshal(raw, &a.PlayPause)
		if err != nil {
			return fmt.Errorf("error reading 'playPause': %w", err)
		}
		delete(object, "playPause")
	}

	if raw, found := object["previous"]; found {
		err = json.Unmarshal(raw, &a.Previous)
		if err != nil {
			return fmt.Errorf("error reading 'previous': %w", err)
		}
		delete(object, "previous")
	}

	if raw, found := object["rateContentAction"]; found {
		err = json.Unmarshal(raw, &a.RateContentAction)
		if err != nil {
			return fmt.Errorf("error reading 'rateContentAction': %w", err)
		}
		delete(object, "rateContentAction")
	}

	if raw, found := object["thumbsDown"]; found {
		err = json.Unmarshal(raw, &a.ThumbsDown)
		if err != nil {
			return fmt.Errorf("error reading 'thumbsDown': %w", err)
		}
		delete(object, "thumbsDown")
	}

	if raw, found := object["thumbsUp"]; found {
		err = json.Unmarshal(raw, &a.ThumbsUp)
		if err != nil {
			return fmt.Errorf("error reading 'thumbsUp': %w", err)
		}
		delete(object, "thumbsUp")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireTransport to handle AdditionalProperties
func (a WireTransport) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ClosedCaptions != nil {
		object["closedCaptions"], err = json.Marshal(a.ClosedCaptions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'closedCaptions': %w", err)
		}
	}

	if a.LayoutType != nil {
		object["layoutType"], err = json.Marshal(a.LayoutType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'layoutType': %w", err)
		}
	}

	if a.Lyrics != nil {
		object["lyrics"], err = json.Marshal(a.Lyrics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lyrics': %w", err)
		}
	}

	if a.Next != nil {
		object["next"], err = json.Marshal(a.Next)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'next': %w", err)
		}
	}

	if a.PlayPause != nil {
		object["playPause"], err = json.Marshal(a.PlayPause)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playPause': %w", err)
		}
	}

	if a.Previous != nil {
		object["previous"], err = json.Marshal(a.Previous)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'previous': %w", err)
		}
	}

	if a.RateContentAction != nil {
		object["rateContentAction"], err = json.Marshal(a.RateContentAction)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rateContentAction': %w", err)
		}
	}

	if a.ThumbsDown != nil {
		object["thumbsDown"], err = json.Marshal(a.ThumbsDown)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'thumbsDown': %w", err)
		}
	}

	if a.ThumbsUp != nil {
		object["thumbsUp"], err = json.Marshal(a.ThumbsUp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'thumbsUp': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireVolume. Returns the specified
// element and whether it was found
func (a WireVolume) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireVolume
func (a *WireVolume) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireVolume to handle AdditionalProperties
func (a *WireVolume) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["muted"]; found {
		err = json.Unmarshal(raw, &a.Muted)
		if err != nil {
			return fmt.Errorf("error reading 'muted': %w", err)
		}
		delete(object, "muted")
	}

	if raw, found := object["volume"]; found {
		err = json.Unmarshal(raw, &a.Volume)
		if err != nil {
			return fmt.Errorf("error reading 'volume': %w", err)
		}
		delete(object, "volume")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireVolume to handle AdditionalProperties
func (a WireVolume) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Muted != nil {
		object["muted"], err = json.Marshal(a.Muted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'muted': %w", err)
		}
	}

	if a.Volume != nil {
		object["volume"], err = json.Marshal(a.Volume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
