// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// Defines values for VideoProviderID.
const (
	VideoProviderIDAmazon      VideoProviderID = "PRIME VIDEO"
	VideoProviderIDDailymotion VideoProviderID = "DAILYMOTION"
	VideoProviderIDNetflix     VideoProviderID = "NETFLIX"
	VideoProviderIDYouTube     VideoProviderID = "YOUTUBE"
)

// Valid indicates whether the value is a known member of the VideoProviderID enum.
func (e VideoProviderID) Valid() bool {
	switch e {
	case VideoProviderIDAmazon:
		return true
	case VideoProviderIDDailymotion:
		return true
	case VideoProviderIDNetflix:
		return true
	case VideoProviderIDYouTube:
		return true
	default:
		return false
	}
}

// Art defines model for Art.
type Art struct {
	AltText     string  `json:"altText,omitempty"`
	ArtType     string  `json:"artType,omitempty"`
	ContentType *string `json:"contentType,omitempty"`
	IconId      *string `json:"iconId,omitempty"`
	IconStyles  *string `json:"iconStyles,omitempty"`
	URL         *string `json:"url,omitempty"`
}

// InfoText defines model for InfoText.
type InfoText struct {
	Header         *string `json:"header,omitempty"`
	HeaderSubtext1 *string `json:"headerSubtext1,omitempty"`
	MultiLineMode  bool    `json:"multiLineMode,omitempty"`
	SubText1       string  `json:"subText1,omitempty"`
	SubText2       string  `json:"subText2,omitempty"`
	Title          string  `json:"title,omitempty"`
}

// MediaCommand defines model for MediaCommand.
type MediaCommand struct {
	Repeat  *bool  `json:"repeat,omitempty"`
	Shuffle *bool  `json:"shuffle,omitempty"`
	Type    string `json:"type"`
}

// MediaControlRequest defines model for MediaControlRequest.
type MediaControlRequest struct {
	Endpoint Endpoint `json:"-,omitempty"`
}

// PlayAudioURIRequest defines model for PlayAudioURIRequest.
type PlayAudioURIRequest struct {
	Endpoint   Endpoint `json:"-,omitempty"`
	CustomerID string   `json:"customerId,omitempty"`
	URI        string   `json:"uri"`
}

// PlayMusicRequest defines model for PlayMusicRequest.
type PlayMusicRequest struct {
	Endpoint     Endpoint `json:"-,omitempty"`
	CustomerID   string   `json:"customerId,omitempty"`
	ProviderID   string   `json:"providerId"`
	SearchPhrase string   `json:"searchPhrase"`
	TimerSeconds *int     `json:"timerSeconds,omitempty"`
}

// PlayVideoRequest defines model for PlayVideoRequest.
type PlayVideoRequest struct {
	Endpoint        Endpoint `json:"-,omitempty"`
	CustomerID      string   `json:"customerId,omitempty"`
	SearchPhrase    string   `json:"searchPhrase"`
	TimerSeconds    *int     `json:"timerSeconds,omitempty"`
	VideoProviderID string   `json:"videoProviderId"`
}

// PlayerInfo defines model for PlayerInfo.
type PlayerInfo struct {
	Hint             *string     `json:"hint,omitempty"`
	InfoText         *InfoText   `json:"infoText,omitempty"`
	IsPlayingInLemur bool        `json:"isPlayingInLemur,omitempty"`
	LemurVolume      *int        `json:"lemurVolume,omitempty"`
	Lyrics           *string     `json:"lyrics,omitempty"`
	MainArt          *Art        `json:"mainArt,omitempty"`
	MediaId          string      `json:"mediaId,omitempty"`
	MiniArt          *Art        `json:"miniArt,omitempty"`
	MiniInfoText     *InfoText   `json:"miniInfoText,omitempty"`
	PlaybackSource   *string     `json:"playbackSource,omitempty"`
	PlayingInLemurId *string     `json:"playingInLemurId,omitempty"`
	Progress         *Progress   `json:"progress,omitempty"`
	Provider         *Provider   `json:"provider,omitempty"`
	Quality          *string     `json:"quality,omitempty"`
	QueueId          string      `json:"queueId,omitempty"`
	State            string      `json:"state,omitempty"`
	Template         *Template   `json:"template,omitempty"`
	Transport        *Transport  `json:"transport,omitempty"`
	UpNextItems      interface{} `json:"upNextItems,omitempty"`
	Volume           *Volume     `json:"volume,omitempty"`
}

// PlayerStateRequest defines model for PlayerStateRequest.
type PlayerStateRequest struct {
	Endpoint Endpoint `json:"-,omitempty"`
}

// PlayerStateResponse defines model for PlayerStateResponse.
type PlayerStateResponse struct {
	PlayerInfo *PlayerInfo `json:"playerInfo,omitempty"`
}

// Progress defines model for Progress.
type Progress struct {
	AllowScrubbing bool    `json:"allowScrubbing,omitempty"`
	LocationInfo   *string `json:"locationInfo,omitempty"`
	MediaLength    int     `json:"mediaLength,omitempty"`
	MediaProgress  int     `json:"mediaProgress,omitempty"`
	ShowTiming     bool    `json:"showTiming,omitempty"`
	Visible        bool    `json:"visible,omitempty"`
}

// Provider defines model for Provider.
type Provider struct {
	ArtOverlay          *Art    `json:"artOverlay,omitempty"`
	FallbackMainArt     *Art    `json:"fallbackMainArt,omitempty"`
	ProviderDisplayName *string `json:"providerDisplayName,omitempty"`
	ProviderLogo        *Art    `json:"providerLogo,omitempty"`
	ProviderName        string  `json:"providerName,omitempty"`
}

// RateContentAction defines model for RateContentAction.
type RateContentAction struct {
	MediaOwnerCustomerId string  `json:"mediaOwnerCustomerId,omitempty"`
	Rating               *string `json:"rating,omitempty"`
	Type                 string  `json:"type,omitempty"`
}

// StopPlaybackRequest defines model for StopPlaybackRequest.
type StopPlaybackRequest struct {
	Endpoint   Endpoint `json:"-,omitempty"`
	AllDevices bool     `json:"allDevices,omitempty"`
	CustomerID string   `json:"customerId,omitempty"`
}

// Template defines model for Template.
type Template struct {
	Art                *Art   `json:"art,omitempty"`
	BackgroundImageURL string `json:"backgroundImageUrl,omitempty"`
	TemplateType       string `json:"templateType,omitempty"`
}

// Transport defines model for Transport.
type Transport struct {
	ClosedCaptions    *string            `json:"closedCaptions,omitempty"`
	LayoutType        string             `json:"layoutType,omitempty"`
	Lyrics            string             `json:"lyrics,omitempty"`
	Next              string             `json:"next,omitempty"`
	PlayPause         string             `json:"playPause,omitempty"`
	Previous          string             `json:"previous,omitempty"`
	RateContentAction *RateContentAction `json:"rateContentAction,omitempty"`
	ThumbsDown        string             `json:"thumbsDown,omitempty"`
	ThumbsUp          string             `json:"thumbsUp,omitempty"`
}

// VideoProviderID defines model for VideoProviderID.
type VideoProviderID string

// Volume defines model for Volume.
type Volume struct {
	Muted  bool `json:"muted,omitempty"`
	Volume int  `json:"volume,omitempty"`
}

// VolumeControlRequest defines model for VolumeControlRequest.
type VolumeControlRequest struct {
	Endpoint   Endpoint `json:"-,omitempty"`
	CustomerID string   `json:"customerId,omitempty"`
	Delta      *int     `json:"delta,omitempty"`
	SetVolume  bool     `json:"setVolume,omitempty"`
	Volume     *int     `json:"volume,omitempty"`
}
