// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

// UserInfo defines model for UserInfo.
type UserInfo struct {
	CountryOfResidence     string   `json:"countryOfResidence"`
	EffectiveMarketPlaceID string   `json:"effectiveMarketPlaceId"`
	Email                  string   `json:"email"`
	EulaAcceptance         bool     `json:"eulaAcceptance"`
	Features               []string `json:"features"`
	FullName               string   `json:"fullName"`
	HasActiveDopplers      bool     `json:"hasActiveDopplers"`
	ID                     string   `json:"id"`
	MarketPlaceDomainName  string   `json:"marketPlaceDomainName"`
	MarketPlaceID          string   `json:"marketPlaceId"`
	MarketPlaceLocale      string   `json:"marketPlaceLocale"`
}
