// Package alexamodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package alexamodels

import (
	"encoding/json"
	"fmt"
)

// WireUserInfo May contain personal account information.
type WireUserInfo struct {
	CountryOfResidence     *string                `json:"countryOfResidence,omitempty"`
	EffectiveMarketPlaceId *string                `json:"effectiveMarketPlaceId,omitempty"`
	Email                  *string                `json:"email,omitempty"`
	EulaAcceptance         *bool                  `json:"eulaAcceptance,omitempty"`
	Features               *[]string              `json:"features,omitempty"`
	FullName               *string                `json:"fullName,omitempty"`
	HasActiveDopplers      *bool                  `json:"hasActiveDopplers,omitempty"`
	Id                     *string                `json:"id,omitempty"`
	MarketPlaceDomainName  *string                `json:"marketPlaceDomainName,omitempty"`
	MarketPlaceId          *string                `json:"marketPlaceId,omitempty"`
	MarketPlaceLocale      *string                `json:"marketPlaceLocale,omitempty"`
	AdditionalProperties   map[string]interface{} `json:"-"`
}

// GetUserInfoParams defines parameters for GetUserInfo.
type GetUserInfoParams struct {
	Platform *string `form:"platform,omitempty" json:"platform,omitempty"`
	Version  *string `form:"version,omitempty" json:"version,omitempty"`

	// Csrf A supplied CSRF token is serialized as a Cookie header by the helper.
	Csrf *string `json:"csrf,omitempty"`
}

// Getter for additional properties for WireUserInfo. Returns the specified
// element and whether it was found
func (a WireUserInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireUserInfo
func (a *WireUserInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireUserInfo to handle AdditionalProperties
func (a *WireUserInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["countryOfResidence"]; found {
		err = json.Unmarshal(raw, &a.CountryOfResidence)
		if err != nil {
			return fmt.Errorf("error reading 'countryOfResidence': %w", err)
		}
		delete(object, "countryOfResidence")
	}

	if raw, found := object["effectiveMarketPlaceId"]; found {
		err = json.Unmarshal(raw, &a.EffectiveMarketPlaceId)
		if err != nil {
			return fmt.Errorf("error reading 'effectiveMarketPlaceId': %w", err)
		}
		delete(object, "effectiveMarketPlaceId")
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &a.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		delete(object, "email")
	}

	if raw, found := object["eulaAcceptance"]; found {
		err = json.Unmarshal(raw, &a.EulaAcceptance)
		if err != nil {
			return fmt.Errorf("error reading 'eulaAcceptance': %w", err)
		}
		delete(object, "eulaAcceptance")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["fullName"]; found {
		err = json.Unmarshal(raw, &a.FullName)
		if err != nil {
			return fmt.Errorf("error reading 'fullName': %w", err)
		}
		delete(object, "fullName")
	}

	if raw, found := object["hasActiveDopplers"]; found {
		err = json.Unmarshal(raw, &a.HasActiveDopplers)
		if err != nil {
			return fmt.Errorf("error reading 'hasActiveDopplers': %w", err)
		}
		delete(object, "hasActiveDopplers")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["marketPlaceDomainName"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceDomainName)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceDomainName': %w", err)
		}
		delete(object, "marketPlaceDomainName")
	}

	if raw, found := object["marketPlaceId"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceId)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceId': %w", err)
		}
		delete(object, "marketPlaceId")
	}

	if raw, found := object["marketPlaceLocale"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceLocale)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceLocale': %w", err)
		}
		delete(object, "marketPlaceLocale")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireUserInfo to handle AdditionalProperties
func (a WireUserInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CountryOfResidence != nil {
		object["countryOfResidence"], err = json.Marshal(a.CountryOfResidence)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'countryOfResidence': %w", err)
		}
	}

	if a.EffectiveMarketPlaceId != nil {
		object["effectiveMarketPlaceId"], err = json.Marshal(a.EffectiveMarketPlaceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'effectiveMarketPlaceId': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.EulaAcceptance != nil {
		object["eulaAcceptance"], err = json.Marshal(a.EulaAcceptance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'eulaAcceptance': %w", err)
		}
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	if a.FullName != nil {
		object["fullName"], err = json.Marshal(a.FullName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fullName': %w", err)
		}
	}

	if a.HasActiveDopplers != nil {
		object["hasActiveDopplers"], err = json.Marshal(a.HasActiveDopplers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasActiveDopplers': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.MarketPlaceDomainName != nil {
		object["marketPlaceDomainName"], err = json.Marshal(a.MarketPlaceDomainName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceDomainName': %w", err)
		}
	}

	if a.MarketPlaceId != nil {
		object["marketPlaceId"], err = json.Marshal(a.MarketPlaceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceId': %w", err)
		}
	}

	if a.MarketPlaceLocale != nil {
		object["marketPlaceLocale"], err = json.Marshal(a.MarketPlaceLocale)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceLocale': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
