package main

import (
	"bytes"
	"errors"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"strings"
	"testing"
)

const compositionSchema = `components:
  schemas:
    Identity:
      x-go-type-name: IdentityModel
      properties:
        id: {type: string}
    Operation:
      allOf:
        - $ref: '#/components/schemas/Identity'
      properties:
        value: {type: number, x-go-type: float64}
`

const flattenedModels = "// Code generated by a schema tool. DO NOT EDIT.\n" +
	"package sample\n" +
	"type IdentityModel struct { ID string `json:\"id\"` }\n" +
	"type Operation struct { ID string `json:\"id\"`; Value float64 `json:\"value\"` }\n"

func TestCompositionPreservesConsumerLiteralsAndIsStable(t *testing.T) {
	t.Parallel()

	output, err := transform([]byte(compositionSchema), []byte(flattenedModels))
	if err != nil {
		t.Fatalf("transform: %v", err)
	}

	consumer := append(bytes.Clone(output), []byte(`
func consume() {
    request := Operation{IdentityModel: IdentityModel{ID: "device"}, Value: 1.25}
    var number float64 = request.Value
    var identifier string = request.ID
    _, _ = number, identifier
}
`)...)
	fileSet := token.NewFileSet()

	file, err := parser.ParseFile(fileSet, "models.go", consumer, 0)
	if err != nil {
		t.Fatalf("parse consumer: %v", err)
	}

	var config types.Config

	_, err = config.Check("example.com/sample", fileSet, []*ast.File{file}, nil)
	if err != nil {
		t.Fatalf("generated embedding breaks consumer: %v", err)
	}

	repeated, err := transform([]byte(compositionSchema), output)
	if err != nil {
		t.Fatalf("repeat transform: %v", err)
	}

	if !bytes.Equal(output, repeated) {
		t.Fatal("repeat transform changed generated bytes")
	}
}

func TestCompositionRejectsSchemaAndGeneratedDrift(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		schema string
		source string
	}{
		{
			name:   "missing parent schema",
			schema: strings.ReplaceAll(compositionSchema, "#/components/schemas/Identity", "#/components/schemas/Missing"),
			source: flattenedModels,
		},
		{
			name:   "external parent reference",
			schema: strings.ReplaceAll(compositionSchema, "#/components/schemas/Identity", "other.yaml#/components/schemas/Identity"),
			source: flattenedModels,
		},
		{
			name:   "multiple composition parents",
			schema: strings.ReplaceAll(compositionSchema, "      allOf:\n", "      allOf:\n        - $ref: '#/components/schemas/Identity'\n"),
			source: flattenedModels,
		},
		{
			name:   "inherited field override",
			schema: strings.ReplaceAll(compositionSchema, "        value:", "        id: {type: string}\n        value:"),
			source: flattenedModels,
		},
		{
			name:   "missing generated parent",
			schema: compositionSchema,
			source: strings.ReplaceAll(flattenedModels, "type IdentityModel struct { ID string `json:\"id\"` }\n", ""),
		},
		{
			name:   "missing generated child field",
			schema: compositionSchema,
			source: strings.ReplaceAll(flattenedModels, "; Value float64 `json:\"value\"`", ""),
		},
		{
			name:   "inherited field type changed",
			schema: compositionSchema,
			source: strings.ReplaceAll(flattenedModels, "Operation struct { ID string", "Operation struct { ID int"),
		},
		{
			name:   "unlisted generated child field",
			schema: compositionSchema,
			source: strings.ReplaceAll(flattenedModels, "Value float64", "Other string `json:\"other\"`; Value float64"),
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			_, err := transform([]byte(test.schema), []byte(test.source))
			if !errors.Is(err, errComposition) {
				t.Fatalf("transform error = %v; want composition rejection", err)
			}
		})
	}
}
