// Code generated by Modelina. DO NOT EDIT.

package wire

type RenderingUpdate struct {
	Route                string                 `json:"route,omitempty"`
	ResourceId           string                 `json:"resourceId,omitempty"`
	ResourceMetadata     string                 `json:"resourceMetadata" binding:"required"`
	AdditionalProperties map[string]interface{} `json:"-,omitempty"`
}
