// Command graphqlmodels moves schema-generated GraphQL object types and their
// JSON behavior into pkg/dependencymodels while leaving operation functions in
// pkg/dependencies/graphql. It also emits compatibility aliases for existing
// imports of pkg/dependencies/graphql.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	inputPath                          = "pkg/dependencies/graphql/generated.go"
	modelsOutputPath                   = "pkg/dependencymodels/graphql_models.gen.go"
	aliasesPath                        = "pkg/dependencies/graphql/model_aliases.gen.go"
	modulePath                         = "github.com/portpowered/go-alexa/pkg/dependencymodels"
	generatedHeader                    = "// Code generated by tools/graphqlmodels from genqlient output; DO NOT EDIT.\n"
	generatedDirectoryMode fs.FileMode = 0o750
	generatedFileMode      fs.FileMode = 0o600
)

var errNoModelTypeDeclarations = errors.New("genqlient output contains no model type declarations")

type importSpec struct {
	name string
	path string
	raw  string
}

type splitResult struct {
	models        []byte
	operations    []byte
	aliases       []byte
	modelNames    []string
	constantNames []string
	variableTypes map[string]string
}

type generatedNames struct {
	typeNames     map[string]string
	modelNames    []string
	constantNames []string
	variableTypes map[string]string
}

func main() {
	err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() error {
	source, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read GraphQL generated source: %w", err)
	}

	result, err := split(source)
	if err != nil {
		return err
	}

	outputs := []struct {
		path string
		data []byte
	}{
		{modelsOutputPath, result.models},
		{inputPath, result.operations},
		{aliasesPath, result.aliases},
	}

	for _, output := range outputs {
		err = os.MkdirAll(filepath.Dir(output.path), generatedDirectoryMode)
		if err != nil {
			return fmt.Errorf("create generated directory for %s: %w", output.path, err)
		}

		err = os.WriteFile(output.path, output.data, generatedFileMode)
		if err != nil {
			return fmt.Errorf("write generated file %s: %w", output.path, err)
		}
	}

	return nil
}

func split(source []byte) (splitResult, error) {
	fset, file, err := parseGeneratedSource(source)
	if err != nil {
		return splitResult{}, err
	}

	names := collectGeneratedNames(fset, file)
	if len(names.typeNames) == 0 {
		return splitResult{}, errNoModelTypeDeclarations
	}

	modelDecls, operationDecls := splitDeclarations(file.Decls, names.typeNames)

	modelImports := importsUsedBy(file.Imports, modelDecls)
	operationImports := importsUsedBy(file.Imports, operationDecls)

	modelOutput, err := formatFile(fset, "alexamodels", modelImports, modelDecls)
	if err != nil {
		return splitResult{}, fmt.Errorf("format moved GraphQL models: %w", err)
	}

	operationOutput, err := formatFile(fset, "graphql", operationImports, operationDecls)
	if err != nil {
		return splitResult{}, fmt.Errorf("format GraphQL operations: %w", err)
	}

	aliasOutput, err := formatAliases(names.typeNames, names.constantNames, names.variableTypes)
	if err != nil {
		return splitResult{}, fmt.Errorf("format GraphQL compatibility aliases: %w", err)
	}

	return splitResult{
		models:        append([]byte(generatedHeader), modelOutput...),
		operations:    append([]byte(generatedHeader), operationOutput...),
		aliases:       append([]byte(generatedHeader), aliasOutput...),
		modelNames:    uniqueSorted(names.modelNames),
		constantNames: uniqueSorted(names.constantNames),
		variableTypes: names.variableTypes,
	}, nil
}

func parseGeneratedSource(source []byte) (*token.FileSet, *ast.File, error) {
	fset := token.NewFileSet()

	file, err := parser.ParseFile(fset, inputPath, source, parser.ParseComments)
	if err != nil {
		return nil, nil, fmt.Errorf("parse genqlient output: %w", err)
	}

	return fset, file, nil
}

func collectGeneratedNames(fset *token.FileSet, file *ast.File) generatedNames {
	names := generatedNames{
		typeNames:     make(map[string]string),
		modelNames:    nil,
		constantNames: nil,
		variableTypes: make(map[string]string),
	}

	for _, declaration := range file.Decls {
		gen, ok := declaration.(*ast.GenDecl)
		if !ok {
			continue
		}

		if gen.Tok == token.TYPE {
			collectTypeNames(gen, &names)

			continue
		}

		if gen.Tok == token.CONST {
			collectConstantNames(gen, &names)

			continue
		}

		if gen.Tok == token.VAR {
			collectVariableTypes(fset, gen, &names)
		}
	}

	return names
}

func collectTypeNames(declaration *ast.GenDecl, names *generatedNames) {
	for _, spec := range declaration.Specs {
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}

		name := typeSpec.Name.Name
		names.typeNames[name] = modelName(name)
		names.modelNames = append(names.modelNames, name)
	}
}

func collectConstantNames(declaration *ast.GenDecl, names *generatedNames) {
	for _, spec := range declaration.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		if isOperationConstant(valueSpec) {
			continue
		}

		for _, name := range valueSpec.Names {
			names.constantNames = append(names.constantNames, name.Name)
		}
	}
}

func collectVariableTypes(fset *token.FileSet, declaration *ast.GenDecl, names *generatedNames) {
	for _, spec := range declaration.Specs {
		valueSpec, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		for index, name := range valueSpec.Names {
			names.variableTypes[name.Name] = inferredSliceType(fset, valueSpec, index)
		}
	}
}

func splitDeclarations(declarations []ast.Decl, typeNames map[string]string) ([]ast.Decl, []ast.Decl) {
	models := make([]ast.Decl, 0, len(declarations))
	operations := make([]ast.Decl, 0, len(declarations))

	for _, declaration := range declarations {
		modelDeclarations, operationDeclarations := splitDeclaration(declaration, typeNames)
		models = append(models, modelDeclarations...)
		operations = append(operations, operationDeclarations...)
	}

	return models, operations
}

func splitDeclaration(declaration ast.Decl, typeNames map[string]string) ([]ast.Decl, []ast.Decl) {
	if generatedImportDeclaration(declaration) {
		return nil, nil
	}

	if belongsToModels(declaration, typeNames) {
		renamePrivateModelIdentifiers(declaration, typeNames)

		return []ast.Decl{declaration}, nil
	}

	gen, ok := declaration.(*ast.GenDecl)
	if !ok || (gen.Tok != token.CONST && gen.Tok != token.VAR) {
		return nil, []ast.Decl{declaration}
	}

	modelSpecs, operationSpecs := splitValueSpecs(gen)

	var modelDeclarations []ast.Decl

	if len(modelSpecs) > 0 {
		modelDeclaration := *gen
		modelDeclaration.Specs = modelSpecs
		renamePrivateModelIdentifiers(&modelDeclaration, typeNames)
		modelDeclarations = append(modelDeclarations, &modelDeclaration)
	}

	var operationDeclarations []ast.Decl

	if len(operationSpecs) > 0 {
		operationDeclaration := *gen
		operationDeclaration.Specs = operationSpecs
		operationDeclarations = append(operationDeclarations, &operationDeclaration)
	}

	return modelDeclarations, operationDeclarations
}

func generatedImportDeclaration(declaration ast.Decl) bool {
	gen, ok := declaration.(*ast.GenDecl)

	return ok && gen.Tok == token.IMPORT
}

func belongsToModels(declaration ast.Decl, typeNames map[string]string) bool {
	switch value := declaration.(type) {
	case *ast.GenDecl:
		return value.Tok == token.TYPE
	case *ast.FuncDecl:
		if value.Recv != nil {
			return typeNames[receiverName(value.Recv.List[0].Type)] != ""
		}

		return isGeneratedJSONHelper(value.Name.Name)
	default:
		return false
	}
}

func isGeneratedJSONHelper(name string) bool {
	return strings.HasPrefix(name, "__unmarshal") || strings.HasPrefix(name, "__marshal")
}

func receiverName(expression ast.Expr) string {
	switch value := expression.(type) {
	case *ast.Ident:
		return value.Name
	case *ast.StarExpr:
		return receiverName(value.X)
	case *ast.IndexExpr:
		return receiverName(value.X)
	case *ast.IndexListExpr:
		return receiverName(value.X)
	default:
		return ""
	}
}

func modelName(name string) string {
	if strings.HasPrefix(name, "__") {
		return "GraphQL" + strings.TrimLeft(name, "_")
	}

	return name
}

func renamePrivateModelIdentifiers(node ast.Node, names map[string]string) {
	ast.Inspect(node, func(current ast.Node) bool {
		identifier, ok := current.(*ast.Ident)
		if !ok {
			return true
		}

		replacement := names[identifier.Name]
		if replacement == "" {
			return true
		}

		identifier.Name = replacement

		return true
	})
}

func isOperationConstant(value *ast.ValueSpec) bool {
	for _, name := range value.Names {
		if strings.HasSuffix(name.Name, "_Operation") {
			return true
		}
	}

	return false
}

func splitValueSpecs(declaration *ast.GenDecl) ([]ast.Spec, []ast.Spec) {
	models := make([]ast.Spec, 0, len(declaration.Specs))

	var operations []ast.Spec

	for _, spec := range declaration.Specs {
		value, ok := spec.(*ast.ValueSpec)
		if !ok {
			operations = append(operations, spec)

			continue
		}

		if declaration.Tok == token.CONST && isOperationConstant(value) {
			operations = append(operations, spec)

			continue
		}

		models = append(models, spec)
	}

	return models, operations
}

func inferredSliceType(fset *token.FileSet, value *ast.ValueSpec, index int) string {
	if index >= len(value.Values) {
		return ""
	}

	literal, isComposite := value.Values[index].(*ast.CompositeLit)
	if !isComposite {
		return ""
	}

	array, ok := literal.Type.(*ast.ArrayType)
	if !ok || array.Len != nil {
		return ""
	}

	var output bytes.Buffer

	err := format.Node(&output, fset, array)
	if err != nil {
		return ""
	}

	return output.String()
}

func importsUsedBy(original []*ast.ImportSpec, declarations []ast.Decl) []importSpec {
	usedNames := make(map[string]struct{})

	for _, declaration := range declarations {
		ast.Inspect(declaration, func(node ast.Node) bool {
			selector, isSelector := node.(*ast.SelectorExpr)
			if !isSelector {
				return true
			}

			identifier, ok := selector.X.(*ast.Ident)
			if ok {
				usedNames[identifier.Name] = struct{}{}
			}

			return true
		})
	}

	imports := make([]importSpec, 0, len(original))

	for _, spec := range original {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}

		name := filepath.Base(path)
		if spec.Name != nil {
			name = spec.Name.Name
		}

		if _, ok := usedNames[name]; !ok {
			continue
		}

		raw := "\t" + strconv.Quote(path)
		if spec.Name != nil {
			raw = "\t" + name + " " + strconv.Quote(path)
		}

		imports = append(imports, importSpec{name: name, path: path, raw: raw})
	}

	sort.Slice(imports, func(left, right int) bool { return imports[left].path < imports[right].path })

	return imports
}

func formatFile(fset *token.FileSet, packageName string, imports []importSpec, declarations []ast.Decl) ([]byte, error) {
	var source strings.Builder

	fmt.Fprintf(&source, "package %s\n\n", packageName)

	if len(imports) > 0 {
		source.WriteString("import (\n")

		for _, item := range imports {
			source.WriteString(item.raw)
			source.WriteByte('\n')
		}

		source.WriteString(")\n\n")
	}

	for _, declaration := range declarations {
		var rendered bytes.Buffer

		err := format.Node(&rendered, fset, declaration)
		if err != nil {
			return nil, fmt.Errorf("format declaration: %w", err)
		}

		source.Write(rendered.Bytes())
		source.WriteString("\n\n")
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return formatted, nil
}

func formatAliases(typeNames map[string]string, constants []string, variables map[string]string) ([]byte, error) {
	var source strings.Builder

	source.WriteString("package graphql\n\nimport alexamodels \"" + modulePath + "\"\n\n")

	oldNames := make([]string, 0, len(typeNames))
	for oldName := range typeNames {
		oldNames = append(oldNames, oldName)
	}

	sort.Strings(oldNames)

	for _, oldName := range oldNames {
		fmt.Fprintf(&source, "type %s = alexamodels.%s\n", oldName, typeNames[oldName])
	}

	for _, name := range uniqueSorted(constants) {
		fmt.Fprintf(&source, "const %s = alexamodels.%s\n", name, name)
	}

	variableNames := make([]string, 0, len(variables))
	for name := range variables {
		variableNames = append(variableNames, name)
	}

	sort.Strings(variableNames)

	for _, name := range variableNames {
		sliceType := variables[name]
		if sliceType == "" {
			fmt.Fprintf(&source, "var %s = alexamodels.%s\n", name, name)

			continue
		}

		fmt.Fprintf(&source, "var %s = append(%s(nil), alexamodels.%s...)\n", name, sliceType, name)
	}

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format aliases source: %w", err)
	}

	return formatted, nil
}

func uniqueSorted(values []string) []string {
	sorted := append([]string(nil), values...)
	sort.Strings(sorted)

	result := sorted[:0]
	for _, value := range sorted {
		if len(result) == 0 || result[len(result)-1] != value {
			result = append(result, value)
		}
	}

	return result
}
