// Command graphqlops generates the generic GraphQL client's operation gate.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	const source = "pkg/dependencies/graphql/generated.go"
	const output = "pkg/dependencies/graphql/allowed_operations.gen.go"
	file, err := parser.ParseFile(token.NewFileSet(), source, nil, 0)
	if err != nil {
		fail(err)
	}
	var names []string
	ast.Inspect(file, func(node ast.Node) bool {
		declaration, ok := node.(*ast.GenDecl)
		if !ok || declaration.Tok != token.CONST {
			return true
		}
		for _, spec := range declaration.Specs {
			for _, name := range spec.(*ast.ValueSpec).Names {
				if strings.HasSuffix(name.Name, "_Operation") {
					names = append(names, name.Name)
				}
			}
		}
		return false
	})
	if len(names) == 0 {
		fail(fmt.Errorf("genqlient generated no GraphQL operations"))
	}
	sort.Strings(names)
	var outputText strings.Builder
	outputText.WriteString("// Code generated by tools/graphqlops; DO NOT EDIT.\npackage graphql\n\n")
	outputText.WriteString("func schemaBackedGraphQLOperation(query string) bool {\n\tswitch query {\n\tcase ")
	outputText.WriteString(strings.Join(names, ", "))
	outputText.WriteString(":\n\t\treturn true\n\tdefault:\n\t\treturn false\n\t}\n}\n")
	formatted, err := format.Source([]byte(outputText.String()))
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		fail(err)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
