// Package wire provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package wire

import (
	"encoding/json"
	"fmt"
)

// Defines values for WireMediaCommandType.
const (
	ForwardCommand  WireMediaCommandType = "ForwardCommand"
	NextCommand     WireMediaCommandType = "NextCommand"
	PauseCommand    WireMediaCommandType = "PauseCommand"
	PlayCommand     WireMediaCommandType = "PlayCommand"
	PreviousCommand WireMediaCommandType = "PreviousCommand"
	RepeatCommand   WireMediaCommandType = "RepeatCommand"
	RewindCommand   WireMediaCommandType = "RewindCommand"
	ShuffleCommand  WireMediaCommandType = "ShuffleCommand"
)

// Valid indicates whether the value is a known member of the WireMediaCommandType enum.
func (e WireMediaCommandType) Valid() bool {
	switch e {
	case ForwardCommand:
		return true
	case NextCommand:
		return true
	case PauseCommand:
		return true
	case PlayCommand:
		return true
	case PreviousCommand:
		return true
	case RepeatCommand:
		return true
	case RewindCommand:
		return true
	case ShuffleCommand:
		return true
	default:
		return false
	}
}

// WireAppDevice defines model for WireAppDevice.
type WireAppDevice struct {
	DeviceAccountId      *string                `json:"deviceAccountId,omitempty"`
	DeviceType           *string                `json:"deviceType,omitempty"`
	SerialNumber         *string                `json:"serialNumber,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireArt defines model for WireArt.
type WireArt struct {
	AltText              *string                `json:"altText,omitempty"`
	ArtType              *string                `json:"artType,omitempty"`
	ContentType          *string                `json:"contentType,omitempty"`
	IconId               *string                `json:"iconId,omitempty"`
	IconStyles           *string                `json:"iconStyles,omitempty"`
	Url                  *string                `json:"url,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireAssociatedUnitsFilter defines model for WireAssociatedUnitsFilter.
type WireAssociatedUnitsFilter struct {
	Id string `json:"id"`
}

// WireAuthData defines model for WireAuthData.
type WireAuthData struct {
	CodePair      *WireCodePairAuth      `json:"code_pair,omitempty"`
	EmailPassword *WireEmailPasswordAuth `json:"email_password,omitempty"`
}

// WireBearerTokens defines model for WireBearerTokens.
type WireBearerTokens struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// WireBehaviorPreviewRequest defines model for WireBehaviorPreviewRequest.
type WireBehaviorPreviewRequest struct {
	BehaviorId string `json:"behaviorId"`

	// SequenceJson JSON-encoded sequence serialized as a string by the client.
	SequenceJson string `json:"sequenceJson"`
	Status       string `json:"status"`
}

// WireCapabilityInterface Open string value; the implementation does not reject unknown capability names.
type WireCapabilityInterface = string

// WireChallenge defines model for WireChallenge.
type WireChallenge struct {
	ChallengeReason              *string `json:"challenge_reason,omitempty"`
	RequiredAuthenticationMethod *string `json:"required_authentication_method,omitempty"`
}

// WireChallengeEnvelope defines model for WireChallengeEnvelope.
type WireChallengeEnvelope struct {
	Challenge *WireChallenge `json:"challenge,omitempty"`
}

// WireChallengeResponse defines model for WireChallengeResponse.
type WireChallengeResponse struct {
	Response *WireChallengeEnvelope `json:"response,omitempty"`
}

// WireCodeData defines model for WireCodeData.
type WireCodeData struct {
	AppName               string `json:"app_name"`
	AppVersion            string `json:"app_version"`
	DeviceModel           string `json:"device_model"`
	DeviceName            string `json:"device_name"`
	DeviceSerial          string `json:"device_serial"`
	DeviceType            string `json:"device_type"`
	Domain                string `json:"domain"`
	OsVersion             string `json:"os_version"`
	SecondaryRegistration string `json:"secondary_registration"`
}

// WireCodePairAuth defines model for WireCodePairAuth.
type WireCodePairAuth struct {
	PrivateCode string `json:"private_code"`
	PublicCode  string `json:"public_code"`
}

// WireCodePairRequest defines model for WireCodePairRequest.
type WireCodePairRequest struct {
	CodeData WireCodeData `json:"code_data"`
	Scopes   []string     `json:"scopes"`
}

// WireCodePairResponse defines model for WireCodePairResponse.
type WireCodePairResponse struct {
	PrivateCode *string `json:"private_code,omitempty"`
	PublicCode  *string `json:"public_code,omitempty"`
}

// WireCommand defines model for WireCommand.
type WireCommand struct {
	DeviceId             *string                `json:"device_id,omitempty"`
	Name                 *string                `json:"name,omitempty"`
	Namespace            *string                `json:"namespace,omitempty"`
	Payload              interface{}            `json:"payload,omitempty"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireCookieExchangeEnvelope defines model for WireCookieExchangeEnvelope.
type WireCookieExchangeEnvelope struct {
	Tokens *WireCookieTokens `json:"tokens,omitempty"`
}

// WireCookieExchangeRequest defines model for WireCookieExchangeRequest.
type WireCookieExchangeRequest struct {
	AppName            string `json:"app_name"`
	Domain             string `json:"domain"`
	RequestedTokenType string `json:"requested_token_type"`
	SourceToken        string `json:"source_token"`
	SourceTokenType    string `json:"source_token_type"`
}

// WireCookieExchangeResponse defines model for WireCookieExchangeResponse.
type WireCookieExchangeResponse struct {
	Response *WireCookieExchangeEnvelope `json:"response,omitempty"`
}

// WireCookieRecord defines model for WireCookieRecord.
type WireCookieRecord struct {
	Expires  *string `json:"Expires,omitempty"`
	HttpOnly *bool   `json:"HttpOnly,omitempty"`
	Name     *string `json:"Name,omitempty"`
	Path     *string `json:"Path,omitempty"`
	Secure   *bool   `json:"Secure,omitempty"`
	Value    *string `json:"Value,omitempty"`
}

// WireCookieTokens defines model for WireCookieTokens.
type WireCookieTokens struct {
	Cookies *map[string][]WireCookieRecord `json:"cookies,omitempty"`
}

// WireDevice defines model for WireDevice.
type WireDevice struct {
	Capabilities         *[]WireCapabilityInterface `json:"capabilities,omitempty"`
	Id                   *string                    `json:"id,omitempty"`
	Metadata             *map[string]interface{}    `json:"metadata,omitempty"`
	Name                 *string                    `json:"name,omitempty"`
	State                *map[string]interface{}    `json:"state,omitempty"`
	Type                 *string                    `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}     `json:"-"`
}

// WireDeviceMetadata defines model for WireDeviceMetadata.
type WireDeviceMetadata struct {
	DeviceModel  string `json:"device_model"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Manufacturer string `json:"manufacturer"`
	OsVersion    string `json:"os_version"`
}

// WireDeviceV2 defines model for WireDeviceV2.
type WireDeviceV2 struct {
	AccountName            *string                `json:"accountName,omitempty"`
	AppDeviceList          *[]WireAppDevice       `json:"appDeviceList,omitempty"`
	AssociatedUnitIds      *[]string              `json:"associatedUnitIds,omitempty"`
	Capabilities           *[]string              `json:"capabilities,omitempty"`
	Charging               *bool                  `json:"charging,omitempty"`
	ClusterMembers         *[]string              `json:"clusterMembers,omitempty"`
	DeviceAccountId        *string                `json:"deviceAccountId,omitempty"`
	DeviceFamily           *string                `json:"deviceFamily,omitempty"`
	DeviceOwnerCustomerId  *string                `json:"deviceOwnerCustomerId,omitempty"`
	DeviceType             *string                `json:"deviceType,omitempty"`
	DeviceTypeFriendlyName *string                `json:"deviceTypeFriendlyName,omitempty"`
	Essid                  *string                `json:"essid,omitempty"`
	Language               *string                `json:"language,omitempty"`
	MacAddress             *string                `json:"macAddress,omitempty"`
	Online                 *bool                  `json:"online,omitempty"`
	ParentClusters         *[]string              `json:"parentClusters,omitempty"`
	PostalCode             *string                `json:"postalCode,omitempty"`
	RegistrationId         *string                `json:"registrationId,omitempty"`
	RemainingBatteryLevel  *int                   `json:"remainingBatteryLevel,omitempty"`
	SerialNumber           *string                `json:"serialNumber,omitempty"`
	SoftwareVersion        *string                `json:"softwareVersion,omitempty"`
	AdditionalProperties   map[string]interface{} `json:"-"`
}

// WireDevicesV2Response defines model for WireDevicesV2Response.
type WireDevicesV2Response struct {
	Devices              []WireDeviceV2         `json:"devices"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireEmailPasswordAuth defines model for WireEmailPasswordAuth.
type WireEmailPasswordAuth struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// WireEndpointIncludeFields defines model for WireEndpointIncludeFields.
type WireEndpointIncludeFields struct {
	Capabilities *bool `json:"capabilities,omitempty"`
	States       *bool `json:"states,omitempty"`
}

// WireEndpointListResponse defines model for WireEndpointListResponse.
type WireEndpointListResponse struct {
	NextToken            *string                `json:"nextToken,omitempty"`
	Results              *[]WireDevice          `json:"results,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireEndpointQuery defines model for WireEndpointQuery.
type WireEndpointQuery struct {
	And               *[]WireEndpointQueryClause `json:"and,omitempty"`
	IncludeFields     *WireEndpointIncludeFields `json:"includeFields,omitempty"`
	Or                *[]WireEndpointQueryClause `json:"or,omitempty"`
	PaginationContext *WirePaginationContext     `json:"paginationContext,omitempty"`
}

// WireEndpointQueryClause defines model for WireEndpointQueryClause.
type WireEndpointQueryClause struct {
	AssociatedUnits *WireAssociatedUnitsFilter `json:"associatedUnits,omitempty"`
	Manufacturer    *WireStringFilter          `json:"manufacturer,omitempty"`
	Model           *WireStringFilter          `json:"model,omitempty"`
}

// WireEndpointQueryRequest defines model for WireEndpointQueryRequest.
type WireEndpointQueryRequest struct {
	Query WireEndpointQuery `json:"query"`
}

// WireFriendlyNameRequest defines model for WireFriendlyNameRequest.
type WireFriendlyNameRequest struct {
	FriendlyName WireFriendlyNameValue `json:"friendlyName"`
}

// WireFriendlyNameText defines model for WireFriendlyNameText.
type WireFriendlyNameText struct {
	Text string `json:"text"`
}

// WireFriendlyNameValue defines model for WireFriendlyNameValue.
type WireFriendlyNameValue struct {
	Type  string               `json:"type"`
	Value WireFriendlyNameText `json:"value"`
}

// WireInfoText defines model for WireInfoText.
type WireInfoText struct {
	Header               *string                `json:"header,omitempty"`
	HeaderSubtext1       *string                `json:"headerSubtext1,omitempty"`
	MultiLineMode        *bool                  `json:"multiLineMode,omitempty"`
	SubText1             *string                `json:"subText1,omitempty"`
	SubText2             *string                `json:"subText2,omitempty"`
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireInterfacePayload Caller-supplied JSON object; nil is serialized by this client as an empty object.
type WireInterfacePayload map[string]interface{}

// WireMediaCommand defines model for WireMediaCommand.
type WireMediaCommand struct {
	Repeat  *bool                `json:"repeat,omitempty"`
	Shuffle *bool                `json:"shuffle,omitempty"`
	Type    WireMediaCommandType `json:"type"`
}

// WireMediaCommandType defines model for WireMediaCommand.Type.
type WireMediaCommandType string

// WirePaginationContext defines model for WirePaginationContext.
type WirePaginationContext struct {
	MaxResults        *int    `json:"maxResults,omitempty"`
	NextToken         *string `json:"nextToken,omitempty"`
	PerformPagination *bool   `json:"performPagination,omitempty"`
}

// WirePlayerInfo defines model for WirePlayerInfo.
type WirePlayerInfo struct {
	Hint                 *string                `json:"hint,omitempty"`
	InfoText             *WireInfoText          `json:"infoText,omitempty"`
	IsPlayingInLemur     *bool                  `json:"isPlayingInLemur,omitempty"`
	LemurVolume          *int                   `json:"lemurVolume,omitempty"`
	Lyrics               *string                `json:"lyrics,omitempty"`
	MainArt              *WireArt               `json:"mainArt,omitempty"`
	MediaId              *string                `json:"mediaId,omitempty"`
	MiniArt              *WireArt               `json:"miniArt,omitempty"`
	MiniInfoText         *WireInfoText          `json:"miniInfoText,omitempty"`
	PlaybackSource       *string                `json:"playbackSource,omitempty"`
	PlayingInLemurId     *string                `json:"playingInLemurId,omitempty"`
	Progress             *WireProgress          `json:"progress,omitempty"`
	Provider             *WireProvider          `json:"provider,omitempty"`
	Quality              *string                `json:"quality,omitempty"`
	QueueId              *string                `json:"queueId,omitempty"`
	State                *string                `json:"state,omitempty"`
	Template             *WireTemplate          `json:"template,omitempty"`
	Transport            *WireTransport         `json:"transport,omitempty"`
	UpNextItems          interface{}            `json:"upNextItems,omitempty"`
	Volume               *WireVolume            `json:"volume,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WirePlayerStateResponse defines model for WirePlayerStateResponse.
type WirePlayerStateResponse struct {
	PlayerInfo           *WirePlayerInfo        `json:"playerInfo,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireProgress defines model for WireProgress.
type WireProgress struct {
	AllowScrubbing       *bool                  `json:"allowScrubbing,omitempty"`
	LocationInfo         *string                `json:"locationInfo,omitempty"`
	MediaLength          *int                   `json:"mediaLength,omitempty"`
	MediaProgress        *int                   `json:"mediaProgress,omitempty"`
	ShowTiming           *bool                  `json:"showTiming,omitempty"`
	Visible              *bool                  `json:"visible,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireProvider defines model for WireProvider.
type WireProvider struct {
	ArtOverlay           *WireArt               `json:"artOverlay,omitempty"`
	FallbackMainArt      *WireArt               `json:"fallbackMainArt,omitempty"`
	ProviderDisplayName  *string                `json:"providerDisplayName,omitempty"`
	ProviderLogo         *WireArt               `json:"providerLogo,omitempty"`
	ProviderName         *string                `json:"providerName,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireRateContentAction defines model for WireRateContentAction.
type WireRateContentAction struct {
	MediaOwnerCustomerId *string                `json:"mediaOwnerCustomerId,omitempty"`
	Rating               *string                `json:"rating,omitempty"`
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireRegistrationData defines model for WireRegistrationData.
type WireRegistrationData struct {
	AppName      string `json:"app_name"`
	AppVersion   string `json:"app_version"`
	DeviceModel  string `json:"device_model"`
	DeviceName   string `json:"device_name"`
	DeviceSerial string `json:"device_serial"`
	DeviceType   string `json:"device_type"`
	Domain       string `json:"domain"`
	OsVersion    string `json:"os_version"`
}

// WireRegistrationRequest defines model for WireRegistrationRequest.
type WireRegistrationRequest struct {
	AuthData           WireAuthData         `json:"auth_data"`
	RegistrationData   WireRegistrationData `json:"registration_data"`
	RequestedTokenType []string             `json:"requested_token_type"`
}

// WireRegistrationResponse defines model for WireRegistrationResponse.
type WireRegistrationResponse struct {
	Response *WireRegistrationResponseEnvelope `json:"response,omitempty"`
}

// WireRegistrationResponseEnvelope defines model for WireRegistrationResponseEnvelope.
type WireRegistrationResponseEnvelope struct {
	Success *WireRegistrationSuccess `json:"success,omitempty"`
}

// WireRegistrationSuccess defines model for WireRegistrationSuccess.
type WireRegistrationSuccess struct {
	Tokens *WireRegistrationTokens `json:"tokens,omitempty"`
}

// WireRegistrationTokens defines model for WireRegistrationTokens.
type WireRegistrationTokens struct {
	Bearer *WireBearerTokens `json:"bearer,omitempty"`
}

// WireStringFilter defines model for WireStringFilter.
type WireStringFilter struct {
	Value WireStringFilterValue `json:"value"`
}

// WireStringFilterValue defines model for WireStringFilterValue.
type WireStringFilterValue struct {
	Text string `json:"text"`
}

// WireTemplate defines model for WireTemplate.
type WireTemplate struct {
	Art                  *WireArt               `json:"art,omitempty"`
	BackgroundImageUrl   *string                `json:"backgroundImageUrl,omitempty"`
	TemplateType         *string                `json:"templateType,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireTokenRefreshRequest defines model for WireTokenRefreshRequest.
type WireTokenRefreshRequest struct {
	AppName            string             `json:"app_name"`
	AppVersion         string             `json:"app_version"`
	DeviceMetadata     WireDeviceMetadata `json:"device_metadata"`
	RequestedTokenType string             `json:"requested_token_type"`
	SourceToken        string             `json:"source_token"`
	SourceTokenType    string             `json:"source_token_type"`
}

// WireTokenRefreshResponse defines model for WireTokenRefreshResponse.
type WireTokenRefreshResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	ExpiresIn   *int    `json:"expires_in,omitempty"`
}

// WireTransport defines model for WireTransport.
type WireTransport struct {
	ClosedCaptions       *string                `json:"closedCaptions,omitempty"`
	LayoutType           *string                `json:"layoutType,omitempty"`
	Lyrics               *string                `json:"lyrics,omitempty"`
	Next                 *string                `json:"next,omitempty"`
	PlayPause            *string                `json:"playPause,omitempty"`
	Previous             *string                `json:"previous,omitempty"`
	RateContentAction    *WireRateContentAction `json:"rateContentAction,omitempty"`
	ThumbsDown           *string                `json:"thumbsDown,omitempty"`
	ThumbsUp             *string                `json:"thumbsUp,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WireUserInfo May contain personal account information.
type WireUserInfo struct {
	CountryOfResidence     *string                `json:"countryOfResidence,omitempty"`
	EffectiveMarketPlaceId *string                `json:"effectiveMarketPlaceId,omitempty"`
	Email                  *string                `json:"email,omitempty"`
	EulaAcceptance         *bool                  `json:"eulaAcceptance,omitempty"`
	Features               *[]string              `json:"features,omitempty"`
	FullName               *string                `json:"fullName,omitempty"`
	HasActiveDopplers      *bool                  `json:"hasActiveDopplers,omitempty"`
	Id                     *string                `json:"id,omitempty"`
	MarketPlaceDomainName  *string                `json:"marketPlaceDomainName,omitempty"`
	MarketPlaceId          *string                `json:"marketPlaceId,omitempty"`
	MarketPlaceLocale      *string                `json:"marketPlaceLocale,omitempty"`
	AdditionalProperties   map[string]interface{} `json:"-"`
}

// WireVolume defines model for WireVolume.
type WireVolume struct {
	Muted                *bool                  `json:"muted,omitempty"`
	Volume               *int                   `json:"volume,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DeviceSerialNumber defines model for DeviceSerialNumber.
type DeviceSerialNumber = string

// DeviceType defines model for DeviceType.
type DeviceType = string

// EndpointId defines model for EndpointId.
type EndpointId = string

// Expand defines model for Expand.
type Expand = []string

// MaxResults defines model for MaxResults.
type MaxResults = int

// NextToken defines model for NextToken.
type NextToken = string

// Owner defines model for Owner.
type Owner = string

// ExchangeRefreshTokenForCookiesParams defines parameters for ExchangeRefreshTokenForCookies.
type ExchangeRefreshTokenForCookiesParams struct {
	// XAmznIdentityAuthDomain Set by the cookie exchange implementation to `api.{domain}`.
	XAmznIdentityAuthDomain string `json:"x-amzn-identity-auth-domain"`
}

// ListFirstPartyDevicesParams defines parameters for ListFirstPartyDevices.
type ListFirstPartyDevicesParams struct {
	// Csrf The helper can send this value in its Cookie header.
	Csrf *string `json:"csrf,omitempty"`
}

// SendMediaCommandParams defines parameters for SendMediaCommand.
type SendMediaCommandParams struct {
	// DeviceSerialNumber Derived from the endpoint object by the media helper.
	DeviceSerialNumber DeviceSerialNumber `form:"deviceSerialNumber" json:"deviceSerialNumber"`

	// DeviceType Derived from the endpoint object by the media helper.
	DeviceType DeviceType `form:"deviceType" json:"deviceType"`
}

// GetMediaPlayerStateParams defines parameters for GetMediaPlayerState.
type GetMediaPlayerStateParams struct {
	// DeviceSerialNumber Derived from the endpoint object by the media helper.
	DeviceSerialNumber DeviceSerialNumber `form:"deviceSerialNumber" json:"deviceSerialNumber"`

	// DeviceType Derived from the endpoint object by the media helper.
	DeviceType DeviceType `form:"deviceType" json:"deviceType"`
}

// GetUserInfoParams defines parameters for GetUserInfo.
type GetUserInfoParams struct {
	Platform *string `form:"platform,omitempty" json:"platform,omitempty"`
	Version  *string `form:"version,omitempty" json:"version,omitempty"`

	// Csrf A supplied CSRF token is serialized as a Cookie header by the helper.
	Csrf *string `json:"csrf,omitempty"`
}

// QueryRestEndpointsParams defines parameters for QueryRestEndpoints.
type QueryRestEndpointsParams struct {
	// Expand Repeated query parameter accepted by the current request builder.
	Expand *Expand `form:"expand,omitempty" json:"expand,omitempty"`

	// MaxResults Integer pagination value passed through by the current REST helper.
	MaxResults *MaxResults `form:"maxResults,omitempty" json:"maxResults,omitempty"`
	NextToken  *NextToken  `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// ListRestEndpointsParams defines parameters for ListRestEndpoints.
type ListRestEndpointsParams struct {
	// Owner Defaults to `~caller` in the current REST helper.
	Owner *Owner `form:"owner,omitempty" json:"owner,omitempty"`

	// Expand Repeated query parameter accepted by the current request builder.
	Expand *Expand `form:"expand,omitempty" json:"expand,omitempty"`

	// MaxResults Integer pagination value passed through by the current REST helper.
	MaxResults *MaxResults `form:"maxResults,omitempty" json:"maxResults,omitempty"`
	NextToken  *NextToken  `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetRestEndpointParams defines parameters for GetRestEndpoint.
type GetRestEndpointParams struct {
	// Expand Repeated query parameter accepted by the current request builder.
	Expand *Expand `form:"expand,omitempty" json:"expand,omitempty"`
}

// ExchangeRefreshTokenForCookiesJSONRequestBody defines body for ExchangeRefreshTokenForCookies for application/json ContentType.
type ExchangeRefreshTokenForCookiesJSONRequestBody = WireCookieExchangeRequest

// SubmitBehaviorPreviewJSONRequestBody defines body for SubmitBehaviorPreview for application/json ContentType.
type SubmitBehaviorPreviewJSONRequestBody = WireBehaviorPreviewRequest

// SendMediaCommandJSONRequestBody defines body for SendMediaCommand for application/json ContentType.
type SendMediaCommandJSONRequestBody = WireMediaCommand

// CreateCodePairJSONRequestBody defines body for CreateCodePair for application/json ContentType.
type CreateCodePairJSONRequestBody = WireCodePairRequest

// RegisterDeviceJSONRequestBody defines body for RegisterDevice for application/json ContentType.
type RegisterDeviceJSONRequestBody = WireRegistrationRequest

// RefreshAccessTokenJSONRequestBody defines body for RefreshAccessToken for application/json ContentType.
type RefreshAccessTokenJSONRequestBody = WireTokenRefreshRequest

// QueryRestEndpointsJSONRequestBody defines body for QueryRestEndpoints for application/json ContentType.
type QueryRestEndpointsJSONRequestBody = WireEndpointQueryRequest

// ControlRestEndpointJSONRequestBody defines body for ControlRestEndpoint for application/json ContentType.
type ControlRestEndpointJSONRequestBody = WireCommand

// UpdateEndpointFriendlyNameJSONRequestBody defines body for UpdateEndpointFriendlyName for application/json ContentType.
type UpdateEndpointFriendlyNameJSONRequestBody = WireFriendlyNameRequest

// SendEndpointInterfaceMessageJSONRequestBody defines body for SendEndpointInterfaceMessage for application/json ContentType.
type SendEndpointInterfaceMessageJSONRequestBody = WireInterfacePayload

// Getter for additional properties for WireAppDevice. Returns the specified
// element and whether it was found
func (a WireAppDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireAppDevice
func (a *WireAppDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireAppDevice to handle AdditionalProperties
func (a *WireAppDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["deviceAccountId"]; found {
		err = json.Unmarshal(raw, &a.DeviceAccountId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceAccountId': %w", err)
		}
		delete(object, "deviceAccountId")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireAppDevice to handle AdditionalProperties
func (a WireAppDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DeviceAccountId != nil {
		object["deviceAccountId"], err = json.Marshal(a.DeviceAccountId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceAccountId': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireArt. Returns the specified
// element and whether it was found
func (a WireArt) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireArt
func (a *WireArt) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireArt to handle AdditionalProperties
func (a *WireArt) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["altText"]; found {
		err = json.Unmarshal(raw, &a.AltText)
		if err != nil {
			return fmt.Errorf("error reading 'altText': %w", err)
		}
		delete(object, "altText")
	}

	if raw, found := object["artType"]; found {
		err = json.Unmarshal(raw, &a.ArtType)
		if err != nil {
			return fmt.Errorf("error reading 'artType': %w", err)
		}
		delete(object, "artType")
	}

	if raw, found := object["contentType"]; found {
		err = json.Unmarshal(raw, &a.ContentType)
		if err != nil {
			return fmt.Errorf("error reading 'contentType': %w", err)
		}
		delete(object, "contentType")
	}

	if raw, found := object["iconId"]; found {
		err = json.Unmarshal(raw, &a.IconId)
		if err != nil {
			return fmt.Errorf("error reading 'iconId': %w", err)
		}
		delete(object, "iconId")
	}

	if raw, found := object["iconStyles"]; found {
		err = json.Unmarshal(raw, &a.IconStyles)
		if err != nil {
			return fmt.Errorf("error reading 'iconStyles': %w", err)
		}
		delete(object, "iconStyles")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireArt to handle AdditionalProperties
func (a WireArt) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AltText != nil {
		object["altText"], err = json.Marshal(a.AltText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'altText': %w", err)
		}
	}

	if a.ArtType != nil {
		object["artType"], err = json.Marshal(a.ArtType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'artType': %w", err)
		}
	}

	if a.ContentType != nil {
		object["contentType"], err = json.Marshal(a.ContentType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'contentType': %w", err)
		}
	}

	if a.IconId != nil {
		object["iconId"], err = json.Marshal(a.IconId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconId': %w", err)
		}
	}

	if a.IconStyles != nil {
		object["iconStyles"], err = json.Marshal(a.IconStyles)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'iconStyles': %w", err)
		}
	}

	if a.Url != nil {
		object["url"], err = json.Marshal(a.Url)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'url': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireCommand. Returns the specified
// element and whether it was found
func (a WireCommand) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireCommand
func (a *WireCommand) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireCommand to handle AdditionalProperties
func (a *WireCommand) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["device_id"]; found {
		err = json.Unmarshal(raw, &a.DeviceId)
		if err != nil {
			return fmt.Errorf("error reading 'device_id': %w", err)
		}
		delete(object, "device_id")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["namespace"]; found {
		err = json.Unmarshal(raw, &a.Namespace)
		if err != nil {
			return fmt.Errorf("error reading 'namespace': %w", err)
		}
		delete(object, "namespace")
	}

	if raw, found := object["payload"]; found {
		err = json.Unmarshal(raw, &a.Payload)
		if err != nil {
			return fmt.Errorf("error reading 'payload': %w", err)
		}
		delete(object, "payload")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireCommand to handle AdditionalProperties
func (a WireCommand) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DeviceId != nil {
		object["device_id"], err = json.Marshal(a.DeviceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'device_id': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Namespace != nil {
		object["namespace"], err = json.Marshal(a.Namespace)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'namespace': %w", err)
		}
	}

	object["payload"], err = json.Marshal(a.Payload)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'payload': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireDevice. Returns the specified
// element and whether it was found
func (a WireDevice) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireDevice
func (a *WireDevice) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireDevice to handle AdditionalProperties
func (a *WireDevice) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["capabilities"]; found {
		err = json.Unmarshal(raw, &a.Capabilities)
		if err != nil {
			return fmt.Errorf("error reading 'capabilities': %w", err)
		}
		delete(object, "capabilities")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireDevice to handle AdditionalProperties
func (a WireDevice) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Capabilities != nil {
		object["capabilities"], err = json.Marshal(a.Capabilities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'capabilities': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireDeviceV2. Returns the specified
// element and whether it was found
func (a WireDeviceV2) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireDeviceV2
func (a *WireDeviceV2) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireDeviceV2 to handle AdditionalProperties
func (a *WireDeviceV2) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["accountName"]; found {
		err = json.Unmarshal(raw, &a.AccountName)
		if err != nil {
			return fmt.Errorf("error reading 'accountName': %w", err)
		}
		delete(object, "accountName")
	}

	if raw, found := object["appDeviceList"]; found {
		err = json.Unmarshal(raw, &a.AppDeviceList)
		if err != nil {
			return fmt.Errorf("error reading 'appDeviceList': %w", err)
		}
		delete(object, "appDeviceList")
	}

	if raw, found := object["associatedUnitIds"]; found {
		err = json.Unmarshal(raw, &a.AssociatedUnitIds)
		if err != nil {
			return fmt.Errorf("error reading 'associatedUnitIds': %w", err)
		}
		delete(object, "associatedUnitIds")
	}

	if raw, found := object["capabilities"]; found {
		err = json.Unmarshal(raw, &a.Capabilities)
		if err != nil {
			return fmt.Errorf("error reading 'capabilities': %w", err)
		}
		delete(object, "capabilities")
	}

	if raw, found := object["charging"]; found {
		err = json.Unmarshal(raw, &a.Charging)
		if err != nil {
			return fmt.Errorf("error reading 'charging': %w", err)
		}
		delete(object, "charging")
	}

	if raw, found := object["clusterMembers"]; found {
		err = json.Unmarshal(raw, &a.ClusterMembers)
		if err != nil {
			return fmt.Errorf("error reading 'clusterMembers': %w", err)
		}
		delete(object, "clusterMembers")
	}

	if raw, found := object["deviceAccountId"]; found {
		err = json.Unmarshal(raw, &a.DeviceAccountId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceAccountId': %w", err)
		}
		delete(object, "deviceAccountId")
	}

	if raw, found := object["deviceFamily"]; found {
		err = json.Unmarshal(raw, &a.DeviceFamily)
		if err != nil {
			return fmt.Errorf("error reading 'deviceFamily': %w", err)
		}
		delete(object, "deviceFamily")
	}

	if raw, found := object["deviceOwnerCustomerId"]; found {
		err = json.Unmarshal(raw, &a.DeviceOwnerCustomerId)
		if err != nil {
			return fmt.Errorf("error reading 'deviceOwnerCustomerId': %w", err)
		}
		delete(object, "deviceOwnerCustomerId")
	}

	if raw, found := object["deviceType"]; found {
		err = json.Unmarshal(raw, &a.DeviceType)
		if err != nil {
			return fmt.Errorf("error reading 'deviceType': %w", err)
		}
		delete(object, "deviceType")
	}

	if raw, found := object["deviceTypeFriendlyName"]; found {
		err = json.Unmarshal(raw, &a.DeviceTypeFriendlyName)
		if err != nil {
			return fmt.Errorf("error reading 'deviceTypeFriendlyName': %w", err)
		}
		delete(object, "deviceTypeFriendlyName")
	}

	if raw, found := object["essid"]; found {
		err = json.Unmarshal(raw, &a.Essid)
		if err != nil {
			return fmt.Errorf("error reading 'essid': %w", err)
		}
		delete(object, "essid")
	}

	if raw, found := object["language"]; found {
		err = json.Unmarshal(raw, &a.Language)
		if err != nil {
			return fmt.Errorf("error reading 'language': %w", err)
		}
		delete(object, "language")
	}

	if raw, found := object["macAddress"]; found {
		err = json.Unmarshal(raw, &a.MacAddress)
		if err != nil {
			return fmt.Errorf("error reading 'macAddress': %w", err)
		}
		delete(object, "macAddress")
	}

	if raw, found := object["online"]; found {
		err = json.Unmarshal(raw, &a.Online)
		if err != nil {
			return fmt.Errorf("error reading 'online': %w", err)
		}
		delete(object, "online")
	}

	if raw, found := object["parentClusters"]; found {
		err = json.Unmarshal(raw, &a.ParentClusters)
		if err != nil {
			return fmt.Errorf("error reading 'parentClusters': %w", err)
		}
		delete(object, "parentClusters")
	}

	if raw, found := object["postalCode"]; found {
		err = json.Unmarshal(raw, &a.PostalCode)
		if err != nil {
			return fmt.Errorf("error reading 'postalCode': %w", err)
		}
		delete(object, "postalCode")
	}

	if raw, found := object["registrationId"]; found {
		err = json.Unmarshal(raw, &a.RegistrationId)
		if err != nil {
			return fmt.Errorf("error reading 'registrationId': %w", err)
		}
		delete(object, "registrationId")
	}

	if raw, found := object["remainingBatteryLevel"]; found {
		err = json.Unmarshal(raw, &a.RemainingBatteryLevel)
		if err != nil {
			return fmt.Errorf("error reading 'remainingBatteryLevel': %w", err)
		}
		delete(object, "remainingBatteryLevel")
	}

	if raw, found := object["serialNumber"]; found {
		err = json.Unmarshal(raw, &a.SerialNumber)
		if err != nil {
			return fmt.Errorf("error reading 'serialNumber': %w", err)
		}
		delete(object, "serialNumber")
	}

	if raw, found := object["softwareVersion"]; found {
		err = json.Unmarshal(raw, &a.SoftwareVersion)
		if err != nil {
			return fmt.Errorf("error reading 'softwareVersion': %w", err)
		}
		delete(object, "softwareVersion")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireDeviceV2 to handle AdditionalProperties
func (a WireDeviceV2) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AccountName != nil {
		object["accountName"], err = json.Marshal(a.AccountName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'accountName': %w", err)
		}
	}

	if a.AppDeviceList != nil {
		object["appDeviceList"], err = json.Marshal(a.AppDeviceList)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'appDeviceList': %w", err)
		}
	}

	if a.AssociatedUnitIds != nil {
		object["associatedUnitIds"], err = json.Marshal(a.AssociatedUnitIds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'associatedUnitIds': %w", err)
		}
	}

	if a.Capabilities != nil {
		object["capabilities"], err = json.Marshal(a.Capabilities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'capabilities': %w", err)
		}
	}

	if a.Charging != nil {
		object["charging"], err = json.Marshal(a.Charging)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'charging': %w", err)
		}
	}

	if a.ClusterMembers != nil {
		object["clusterMembers"], err = json.Marshal(a.ClusterMembers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'clusterMembers': %w", err)
		}
	}

	if a.DeviceAccountId != nil {
		object["deviceAccountId"], err = json.Marshal(a.DeviceAccountId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceAccountId': %w", err)
		}
	}

	if a.DeviceFamily != nil {
		object["deviceFamily"], err = json.Marshal(a.DeviceFamily)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceFamily': %w", err)
		}
	}

	if a.DeviceOwnerCustomerId != nil {
		object["deviceOwnerCustomerId"], err = json.Marshal(a.DeviceOwnerCustomerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceOwnerCustomerId': %w", err)
		}
	}

	if a.DeviceType != nil {
		object["deviceType"], err = json.Marshal(a.DeviceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceType': %w", err)
		}
	}

	if a.DeviceTypeFriendlyName != nil {
		object["deviceTypeFriendlyName"], err = json.Marshal(a.DeviceTypeFriendlyName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deviceTypeFriendlyName': %w", err)
		}
	}

	if a.Essid != nil {
		object["essid"], err = json.Marshal(a.Essid)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'essid': %w", err)
		}
	}

	if a.Language != nil {
		object["language"], err = json.Marshal(a.Language)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'language': %w", err)
		}
	}

	if a.MacAddress != nil {
		object["macAddress"], err = json.Marshal(a.MacAddress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'macAddress': %w", err)
		}
	}

	if a.Online != nil {
		object["online"], err = json.Marshal(a.Online)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'online': %w", err)
		}
	}

	if a.ParentClusters != nil {
		object["parentClusters"], err = json.Marshal(a.ParentClusters)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parentClusters': %w", err)
		}
	}

	if a.PostalCode != nil {
		object["postalCode"], err = json.Marshal(a.PostalCode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'postalCode': %w", err)
		}
	}

	if a.RegistrationId != nil {
		object["registrationId"], err = json.Marshal(a.RegistrationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'registrationId': %w", err)
		}
	}

	if a.RemainingBatteryLevel != nil {
		object["remainingBatteryLevel"], err = json.Marshal(a.RemainingBatteryLevel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'remainingBatteryLevel': %w", err)
		}
	}

	if a.SerialNumber != nil {
		object["serialNumber"], err = json.Marshal(a.SerialNumber)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'serialNumber': %w", err)
		}
	}

	if a.SoftwareVersion != nil {
		object["softwareVersion"], err = json.Marshal(a.SoftwareVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'softwareVersion': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireDevicesV2Response. Returns the specified
// element and whether it was found
func (a WireDevicesV2Response) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireDevicesV2Response
func (a *WireDevicesV2Response) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireDevicesV2Response to handle AdditionalProperties
func (a *WireDevicesV2Response) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireDevicesV2Response to handle AdditionalProperties
func (a WireDevicesV2Response) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireEndpointListResponse. Returns the specified
// element and whether it was found
func (a WireEndpointListResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireEndpointListResponse
func (a *WireEndpointListResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireEndpointListResponse to handle AdditionalProperties
func (a *WireEndpointListResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["nextToken"]; found {
		err = json.Unmarshal(raw, &a.NextToken)
		if err != nil {
			return fmt.Errorf("error reading 'nextToken': %w", err)
		}
		delete(object, "nextToken")
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &a.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
		delete(object, "results")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireEndpointListResponse to handle AdditionalProperties
func (a WireEndpointListResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.NextToken != nil {
		object["nextToken"], err = json.Marshal(a.NextToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nextToken': %w", err)
		}
	}

	if a.Results != nil {
		object["results"], err = json.Marshal(a.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireInfoText. Returns the specified
// element and whether it was found
func (a WireInfoText) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireInfoText
func (a *WireInfoText) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireInfoText to handle AdditionalProperties
func (a *WireInfoText) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["header"]; found {
		err = json.Unmarshal(raw, &a.Header)
		if err != nil {
			return fmt.Errorf("error reading 'header': %w", err)
		}
		delete(object, "header")
	}

	if raw, found := object["headerSubtext1"]; found {
		err = json.Unmarshal(raw, &a.HeaderSubtext1)
		if err != nil {
			return fmt.Errorf("error reading 'headerSubtext1': %w", err)
		}
		delete(object, "headerSubtext1")
	}

	if raw, found := object["multiLineMode"]; found {
		err = json.Unmarshal(raw, &a.MultiLineMode)
		if err != nil {
			return fmt.Errorf("error reading 'multiLineMode': %w", err)
		}
		delete(object, "multiLineMode")
	}

	if raw, found := object["subText1"]; found {
		err = json.Unmarshal(raw, &a.SubText1)
		if err != nil {
			return fmt.Errorf("error reading 'subText1': %w", err)
		}
		delete(object, "subText1")
	}

	if raw, found := object["subText2"]; found {
		err = json.Unmarshal(raw, &a.SubText2)
		if err != nil {
			return fmt.Errorf("error reading 'subText2': %w", err)
		}
		delete(object, "subText2")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireInfoText to handle AdditionalProperties
func (a WireInfoText) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Header != nil {
		object["header"], err = json.Marshal(a.Header)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'header': %w", err)
		}
	}

	if a.HeaderSubtext1 != nil {
		object["headerSubtext1"], err = json.Marshal(a.HeaderSubtext1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'headerSubtext1': %w", err)
		}
	}

	if a.MultiLineMode != nil {
		object["multiLineMode"], err = json.Marshal(a.MultiLineMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multiLineMode': %w", err)
		}
	}

	if a.SubText1 != nil {
		object["subText1"], err = json.Marshal(a.SubText1)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subText1': %w", err)
		}
	}

	if a.SubText2 != nil {
		object["subText2"], err = json.Marshal(a.SubText2)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'subText2': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WirePlayerInfo. Returns the specified
// element and whether it was found
func (a WirePlayerInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WirePlayerInfo
func (a *WirePlayerInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WirePlayerInfo to handle AdditionalProperties
func (a *WirePlayerInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["hint"]; found {
		err = json.Unmarshal(raw, &a.Hint)
		if err != nil {
			return fmt.Errorf("error reading 'hint': %w", err)
		}
		delete(object, "hint")
	}

	if raw, found := object["infoText"]; found {
		err = json.Unmarshal(raw, &a.InfoText)
		if err != nil {
			return fmt.Errorf("error reading 'infoText': %w", err)
		}
		delete(object, "infoText")
	}

	if raw, found := object["isPlayingInLemur"]; found {
		err = json.Unmarshal(raw, &a.IsPlayingInLemur)
		if err != nil {
			return fmt.Errorf("error reading 'isPlayingInLemur': %w", err)
		}
		delete(object, "isPlayingInLemur")
	}

	if raw, found := object["lemurVolume"]; found {
		err = json.Unmarshal(raw, &a.LemurVolume)
		if err != nil {
			return fmt.Errorf("error reading 'lemurVolume': %w", err)
		}
		delete(object, "lemurVolume")
	}

	if raw, found := object["lyrics"]; found {
		err = json.Unmarshal(raw, &a.Lyrics)
		if err != nil {
			return fmt.Errorf("error reading 'lyrics': %w", err)
		}
		delete(object, "lyrics")
	}

	if raw, found := object["mainArt"]; found {
		err = json.Unmarshal(raw, &a.MainArt)
		if err != nil {
			return fmt.Errorf("error reading 'mainArt': %w", err)
		}
		delete(object, "mainArt")
	}

	if raw, found := object["mediaId"]; found {
		err = json.Unmarshal(raw, &a.MediaId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaId': %w", err)
		}
		delete(object, "mediaId")
	}

	if raw, found := object["miniArt"]; found {
		err = json.Unmarshal(raw, &a.MiniArt)
		if err != nil {
			return fmt.Errorf("error reading 'miniArt': %w", err)
		}
		delete(object, "miniArt")
	}

	if raw, found := object["miniInfoText"]; found {
		err = json.Unmarshal(raw, &a.MiniInfoText)
		if err != nil {
			return fmt.Errorf("error reading 'miniInfoText': %w", err)
		}
		delete(object, "miniInfoText")
	}

	if raw, found := object["playbackSource"]; found {
		err = json.Unmarshal(raw, &a.PlaybackSource)
		if err != nil {
			return fmt.Errorf("error reading 'playbackSource': %w", err)
		}
		delete(object, "playbackSource")
	}

	if raw, found := object["playingInLemurId"]; found {
		err = json.Unmarshal(raw, &a.PlayingInLemurId)
		if err != nil {
			return fmt.Errorf("error reading 'playingInLemurId': %w", err)
		}
		delete(object, "playingInLemurId")
	}

	if raw, found := object["progress"]; found {
		err = json.Unmarshal(raw, &a.Progress)
		if err != nil {
			return fmt.Errorf("error reading 'progress': %w", err)
		}
		delete(object, "progress")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if raw, found := object["quality"]; found {
		err = json.Unmarshal(raw, &a.Quality)
		if err != nil {
			return fmt.Errorf("error reading 'quality': %w", err)
		}
		delete(object, "quality")
	}

	if raw, found := object["queueId"]; found {
		err = json.Unmarshal(raw, &a.QueueId)
		if err != nil {
			return fmt.Errorf("error reading 'queueId': %w", err)
		}
		delete(object, "queueId")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["template"]; found {
		err = json.Unmarshal(raw, &a.Template)
		if err != nil {
			return fmt.Errorf("error reading 'template': %w", err)
		}
		delete(object, "template")
	}

	if raw, found := object["transport"]; found {
		err = json.Unmarshal(raw, &a.Transport)
		if err != nil {
			return fmt.Errorf("error reading 'transport': %w", err)
		}
		delete(object, "transport")
	}

	if raw, found := object["upNextItems"]; found {
		err = json.Unmarshal(raw, &a.UpNextItems)
		if err != nil {
			return fmt.Errorf("error reading 'upNextItems': %w", err)
		}
		delete(object, "upNextItems")
	}

	if raw, found := object["volume"]; found {
		err = json.Unmarshal(raw, &a.Volume)
		if err != nil {
			return fmt.Errorf("error reading 'volume': %w", err)
		}
		delete(object, "volume")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WirePlayerInfo to handle AdditionalProperties
func (a WirePlayerInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Hint != nil {
		object["hint"], err = json.Marshal(a.Hint)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hint': %w", err)
		}
	}

	if a.InfoText != nil {
		object["infoText"], err = json.Marshal(a.InfoText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'infoText': %w", err)
		}
	}

	if a.IsPlayingInLemur != nil {
		object["isPlayingInLemur"], err = json.Marshal(a.IsPlayingInLemur)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'isPlayingInLemur': %w", err)
		}
	}

	if a.LemurVolume != nil {
		object["lemurVolume"], err = json.Marshal(a.LemurVolume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lemurVolume': %w", err)
		}
	}

	if a.Lyrics != nil {
		object["lyrics"], err = json.Marshal(a.Lyrics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lyrics': %w", err)
		}
	}

	if a.MainArt != nil {
		object["mainArt"], err = json.Marshal(a.MainArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mainArt': %w", err)
		}
	}

	if a.MediaId != nil {
		object["mediaId"], err = json.Marshal(a.MediaId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaId': %w", err)
		}
	}

	if a.MiniArt != nil {
		object["miniArt"], err = json.Marshal(a.MiniArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'miniArt': %w", err)
		}
	}

	if a.MiniInfoText != nil {
		object["miniInfoText"], err = json.Marshal(a.MiniInfoText)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'miniInfoText': %w", err)
		}
	}

	if a.PlaybackSource != nil {
		object["playbackSource"], err = json.Marshal(a.PlaybackSource)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playbackSource': %w", err)
		}
	}

	if a.PlayingInLemurId != nil {
		object["playingInLemurId"], err = json.Marshal(a.PlayingInLemurId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playingInLemurId': %w", err)
		}
	}

	if a.Progress != nil {
		object["progress"], err = json.Marshal(a.Progress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'progress': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Quality != nil {
		object["quality"], err = json.Marshal(a.Quality)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'quality': %w", err)
		}
	}

	if a.QueueId != nil {
		object["queueId"], err = json.Marshal(a.QueueId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'queueId': %w", err)
		}
	}

	if a.State != nil {
		object["state"], err = json.Marshal(a.State)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'state': %w", err)
		}
	}

	if a.Template != nil {
		object["template"], err = json.Marshal(a.Template)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'template': %w", err)
		}
	}

	if a.Transport != nil {
		object["transport"], err = json.Marshal(a.Transport)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'transport': %w", err)
		}
	}

	object["upNextItems"], err = json.Marshal(a.UpNextItems)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'upNextItems': %w", err)
	}

	if a.Volume != nil {
		object["volume"], err = json.Marshal(a.Volume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WirePlayerStateResponse. Returns the specified
// element and whether it was found
func (a WirePlayerStateResponse) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WirePlayerStateResponse
func (a *WirePlayerStateResponse) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WirePlayerStateResponse to handle AdditionalProperties
func (a *WirePlayerStateResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["playerInfo"]; found {
		err = json.Unmarshal(raw, &a.PlayerInfo)
		if err != nil {
			return fmt.Errorf("error reading 'playerInfo': %w", err)
		}
		delete(object, "playerInfo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WirePlayerStateResponse to handle AdditionalProperties
func (a WirePlayerStateResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.PlayerInfo != nil {
		object["playerInfo"], err = json.Marshal(a.PlayerInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playerInfo': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireProgress. Returns the specified
// element and whether it was found
func (a WireProgress) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireProgress
func (a *WireProgress) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireProgress to handle AdditionalProperties
func (a *WireProgress) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["allowScrubbing"]; found {
		err = json.Unmarshal(raw, &a.AllowScrubbing)
		if err != nil {
			return fmt.Errorf("error reading 'allowScrubbing': %w", err)
		}
		delete(object, "allowScrubbing")
	}

	if raw, found := object["locationInfo"]; found {
		err = json.Unmarshal(raw, &a.LocationInfo)
		if err != nil {
			return fmt.Errorf("error reading 'locationInfo': %w", err)
		}
		delete(object, "locationInfo")
	}

	if raw, found := object["mediaLength"]; found {
		err = json.Unmarshal(raw, &a.MediaLength)
		if err != nil {
			return fmt.Errorf("error reading 'mediaLength': %w", err)
		}
		delete(object, "mediaLength")
	}

	if raw, found := object["mediaProgress"]; found {
		err = json.Unmarshal(raw, &a.MediaProgress)
		if err != nil {
			return fmt.Errorf("error reading 'mediaProgress': %w", err)
		}
		delete(object, "mediaProgress")
	}

	if raw, found := object["showTiming"]; found {
		err = json.Unmarshal(raw, &a.ShowTiming)
		if err != nil {
			return fmt.Errorf("error reading 'showTiming': %w", err)
		}
		delete(object, "showTiming")
	}

	if raw, found := object["visible"]; found {
		err = json.Unmarshal(raw, &a.Visible)
		if err != nil {
			return fmt.Errorf("error reading 'visible': %w", err)
		}
		delete(object, "visible")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireProgress to handle AdditionalProperties
func (a WireProgress) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AllowScrubbing != nil {
		object["allowScrubbing"], err = json.Marshal(a.AllowScrubbing)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'allowScrubbing': %w", err)
		}
	}

	if a.LocationInfo != nil {
		object["locationInfo"], err = json.Marshal(a.LocationInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'locationInfo': %w", err)
		}
	}

	if a.MediaLength != nil {
		object["mediaLength"], err = json.Marshal(a.MediaLength)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaLength': %w", err)
		}
	}

	if a.MediaProgress != nil {
		object["mediaProgress"], err = json.Marshal(a.MediaProgress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaProgress': %w", err)
		}
	}

	if a.ShowTiming != nil {
		object["showTiming"], err = json.Marshal(a.ShowTiming)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'showTiming': %w", err)
		}
	}

	if a.Visible != nil {
		object["visible"], err = json.Marshal(a.Visible)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'visible': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireProvider. Returns the specified
// element and whether it was found
func (a WireProvider) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireProvider
func (a *WireProvider) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireProvider to handle AdditionalProperties
func (a *WireProvider) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["artOverlay"]; found {
		err = json.Unmarshal(raw, &a.ArtOverlay)
		if err != nil {
			return fmt.Errorf("error reading 'artOverlay': %w", err)
		}
		delete(object, "artOverlay")
	}

	if raw, found := object["fallbackMainArt"]; found {
		err = json.Unmarshal(raw, &a.FallbackMainArt)
		if err != nil {
			return fmt.Errorf("error reading 'fallbackMainArt': %w", err)
		}
		delete(object, "fallbackMainArt")
	}

	if raw, found := object["providerDisplayName"]; found {
		err = json.Unmarshal(raw, &a.ProviderDisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'providerDisplayName': %w", err)
		}
		delete(object, "providerDisplayName")
	}

	if raw, found := object["providerLogo"]; found {
		err = json.Unmarshal(raw, &a.ProviderLogo)
		if err != nil {
			return fmt.Errorf("error reading 'providerLogo': %w", err)
		}
		delete(object, "providerLogo")
	}

	if raw, found := object["providerName"]; found {
		err = json.Unmarshal(raw, &a.ProviderName)
		if err != nil {
			return fmt.Errorf("error reading 'providerName': %w", err)
		}
		delete(object, "providerName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireProvider to handle AdditionalProperties
func (a WireProvider) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ArtOverlay != nil {
		object["artOverlay"], err = json.Marshal(a.ArtOverlay)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'artOverlay': %w", err)
		}
	}

	if a.FallbackMainArt != nil {
		object["fallbackMainArt"], err = json.Marshal(a.FallbackMainArt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fallbackMainArt': %w", err)
		}
	}

	if a.ProviderDisplayName != nil {
		object["providerDisplayName"], err = json.Marshal(a.ProviderDisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerDisplayName': %w", err)
		}
	}

	if a.ProviderLogo != nil {
		object["providerLogo"], err = json.Marshal(a.ProviderLogo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerLogo': %w", err)
		}
	}

	if a.ProviderName != nil {
		object["providerName"], err = json.Marshal(a.ProviderName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'providerName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireRateContentAction. Returns the specified
// element and whether it was found
func (a WireRateContentAction) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireRateContentAction
func (a *WireRateContentAction) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireRateContentAction to handle AdditionalProperties
func (a *WireRateContentAction) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["mediaOwnerCustomerId"]; found {
		err = json.Unmarshal(raw, &a.MediaOwnerCustomerId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaOwnerCustomerId': %w", err)
		}
		delete(object, "mediaOwnerCustomerId")
	}

	if raw, found := object["rating"]; found {
		err = json.Unmarshal(raw, &a.Rating)
		if err != nil {
			return fmt.Errorf("error reading 'rating': %w", err)
		}
		delete(object, "rating")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireRateContentAction to handle AdditionalProperties
func (a WireRateContentAction) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MediaOwnerCustomerId != nil {
		object["mediaOwnerCustomerId"], err = json.Marshal(a.MediaOwnerCustomerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mediaOwnerCustomerId': %w", err)
		}
	}

	if a.Rating != nil {
		object["rating"], err = json.Marshal(a.Rating)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rating': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireTemplate. Returns the specified
// element and whether it was found
func (a WireTemplate) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireTemplate
func (a *WireTemplate) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireTemplate to handle AdditionalProperties
func (a *WireTemplate) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["art"]; found {
		err = json.Unmarshal(raw, &a.Art)
		if err != nil {
			return fmt.Errorf("error reading 'art': %w", err)
		}
		delete(object, "art")
	}

	if raw, found := object["backgroundImageUrl"]; found {
		err = json.Unmarshal(raw, &a.BackgroundImageUrl)
		if err != nil {
			return fmt.Errorf("error reading 'backgroundImageUrl': %w", err)
		}
		delete(object, "backgroundImageUrl")
	}

	if raw, found := object["templateType"]; found {
		err = json.Unmarshal(raw, &a.TemplateType)
		if err != nil {
			return fmt.Errorf("error reading 'templateType': %w", err)
		}
		delete(object, "templateType")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireTemplate to handle AdditionalProperties
func (a WireTemplate) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Art != nil {
		object["art"], err = json.Marshal(a.Art)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'art': %w", err)
		}
	}

	if a.BackgroundImageUrl != nil {
		object["backgroundImageUrl"], err = json.Marshal(a.BackgroundImageUrl)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'backgroundImageUrl': %w", err)
		}
	}

	if a.TemplateType != nil {
		object["templateType"], err = json.Marshal(a.TemplateType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'templateType': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireTransport. Returns the specified
// element and whether it was found
func (a WireTransport) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireTransport
func (a *WireTransport) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireTransport to handle AdditionalProperties
func (a *WireTransport) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["closedCaptions"]; found {
		err = json.Unmarshal(raw, &a.ClosedCaptions)
		if err != nil {
			return fmt.Errorf("error reading 'closedCaptions': %w", err)
		}
		delete(object, "closedCaptions")
	}

	if raw, found := object["layoutType"]; found {
		err = json.Unmarshal(raw, &a.LayoutType)
		if err != nil {
			return fmt.Errorf("error reading 'layoutType': %w", err)
		}
		delete(object, "layoutType")
	}

	if raw, found := object["lyrics"]; found {
		err = json.Unmarshal(raw, &a.Lyrics)
		if err != nil {
			return fmt.Errorf("error reading 'lyrics': %w", err)
		}
		delete(object, "lyrics")
	}

	if raw, found := object["next"]; found {
		err = json.Unmarshal(raw, &a.Next)
		if err != nil {
			return fmt.Errorf("error reading 'next': %w", err)
		}
		delete(object, "next")
	}

	if raw, found := object["playPause"]; found {
		err = json.Unmarshal(raw, &a.PlayPause)
		if err != nil {
			return fmt.Errorf("error reading 'playPause': %w", err)
		}
		delete(object, "playPause")
	}

	if raw, found := object["previous"]; found {
		err = json.Unmarshal(raw, &a.Previous)
		if err != nil {
			return fmt.Errorf("error reading 'previous': %w", err)
		}
		delete(object, "previous")
	}

	if raw, found := object["rateContentAction"]; found {
		err = json.Unmarshal(raw, &a.RateContentAction)
		if err != nil {
			return fmt.Errorf("error reading 'rateContentAction': %w", err)
		}
		delete(object, "rateContentAction")
	}

	if raw, found := object["thumbsDown"]; found {
		err = json.Unmarshal(raw, &a.ThumbsDown)
		if err != nil {
			return fmt.Errorf("error reading 'thumbsDown': %w", err)
		}
		delete(object, "thumbsDown")
	}

	if raw, found := object["thumbsUp"]; found {
		err = json.Unmarshal(raw, &a.ThumbsUp)
		if err != nil {
			return fmt.Errorf("error reading 'thumbsUp': %w", err)
		}
		delete(object, "thumbsUp")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireTransport to handle AdditionalProperties
func (a WireTransport) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ClosedCaptions != nil {
		object["closedCaptions"], err = json.Marshal(a.ClosedCaptions)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'closedCaptions': %w", err)
		}
	}

	if a.LayoutType != nil {
		object["layoutType"], err = json.Marshal(a.LayoutType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'layoutType': %w", err)
		}
	}

	if a.Lyrics != nil {
		object["lyrics"], err = json.Marshal(a.Lyrics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lyrics': %w", err)
		}
	}

	if a.Next != nil {
		object["next"], err = json.Marshal(a.Next)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'next': %w", err)
		}
	}

	if a.PlayPause != nil {
		object["playPause"], err = json.Marshal(a.PlayPause)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'playPause': %w", err)
		}
	}

	if a.Previous != nil {
		object["previous"], err = json.Marshal(a.Previous)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'previous': %w", err)
		}
	}

	if a.RateContentAction != nil {
		object["rateContentAction"], err = json.Marshal(a.RateContentAction)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rateContentAction': %w", err)
		}
	}

	if a.ThumbsDown != nil {
		object["thumbsDown"], err = json.Marshal(a.ThumbsDown)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'thumbsDown': %w", err)
		}
	}

	if a.ThumbsUp != nil {
		object["thumbsUp"], err = json.Marshal(a.ThumbsUp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'thumbsUp': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireUserInfo. Returns the specified
// element and whether it was found
func (a WireUserInfo) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireUserInfo
func (a *WireUserInfo) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireUserInfo to handle AdditionalProperties
func (a *WireUserInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["countryOfResidence"]; found {
		err = json.Unmarshal(raw, &a.CountryOfResidence)
		if err != nil {
			return fmt.Errorf("error reading 'countryOfResidence': %w", err)
		}
		delete(object, "countryOfResidence")
	}

	if raw, found := object["effectiveMarketPlaceId"]; found {
		err = json.Unmarshal(raw, &a.EffectiveMarketPlaceId)
		if err != nil {
			return fmt.Errorf("error reading 'effectiveMarketPlaceId': %w", err)
		}
		delete(object, "effectiveMarketPlaceId")
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &a.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		delete(object, "email")
	}

	if raw, found := object["eulaAcceptance"]; found {
		err = json.Unmarshal(raw, &a.EulaAcceptance)
		if err != nil {
			return fmt.Errorf("error reading 'eulaAcceptance': %w", err)
		}
		delete(object, "eulaAcceptance")
	}

	if raw, found := object["features"]; found {
		err = json.Unmarshal(raw, &a.Features)
		if err != nil {
			return fmt.Errorf("error reading 'features': %w", err)
		}
		delete(object, "features")
	}

	if raw, found := object["fullName"]; found {
		err = json.Unmarshal(raw, &a.FullName)
		if err != nil {
			return fmt.Errorf("error reading 'fullName': %w", err)
		}
		delete(object, "fullName")
	}

	if raw, found := object["hasActiveDopplers"]; found {
		err = json.Unmarshal(raw, &a.HasActiveDopplers)
		if err != nil {
			return fmt.Errorf("error reading 'hasActiveDopplers': %w", err)
		}
		delete(object, "hasActiveDopplers")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["marketPlaceDomainName"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceDomainName)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceDomainName': %w", err)
		}
		delete(object, "marketPlaceDomainName")
	}

	if raw, found := object["marketPlaceId"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceId)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceId': %w", err)
		}
		delete(object, "marketPlaceId")
	}

	if raw, found := object["marketPlaceLocale"]; found {
		err = json.Unmarshal(raw, &a.MarketPlaceLocale)
		if err != nil {
			return fmt.Errorf("error reading 'marketPlaceLocale': %w", err)
		}
		delete(object, "marketPlaceLocale")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireUserInfo to handle AdditionalProperties
func (a WireUserInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CountryOfResidence != nil {
		object["countryOfResidence"], err = json.Marshal(a.CountryOfResidence)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'countryOfResidence': %w", err)
		}
	}

	if a.EffectiveMarketPlaceId != nil {
		object["effectiveMarketPlaceId"], err = json.Marshal(a.EffectiveMarketPlaceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'effectiveMarketPlaceId': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.EulaAcceptance != nil {
		object["eulaAcceptance"], err = json.Marshal(a.EulaAcceptance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'eulaAcceptance': %w", err)
		}
	}

	if a.Features != nil {
		object["features"], err = json.Marshal(a.Features)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'features': %w", err)
		}
	}

	if a.FullName != nil {
		object["fullName"], err = json.Marshal(a.FullName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fullName': %w", err)
		}
	}

	if a.HasActiveDopplers != nil {
		object["hasActiveDopplers"], err = json.Marshal(a.HasActiveDopplers)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'hasActiveDopplers': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.MarketPlaceDomainName != nil {
		object["marketPlaceDomainName"], err = json.Marshal(a.MarketPlaceDomainName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceDomainName': %w", err)
		}
	}

	if a.MarketPlaceId != nil {
		object["marketPlaceId"], err = json.Marshal(a.MarketPlaceId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceId': %w", err)
		}
	}

	if a.MarketPlaceLocale != nil {
		object["marketPlaceLocale"], err = json.Marshal(a.MarketPlaceLocale)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'marketPlaceLocale': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WireVolume. Returns the specified
// element and whether it was found
func (a WireVolume) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WireVolume
func (a *WireVolume) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WireVolume to handle AdditionalProperties
func (a *WireVolume) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["muted"]; found {
		err = json.Unmarshal(raw, &a.Muted)
		if err != nil {
			return fmt.Errorf("error reading 'muted': %w", err)
		}
		delete(object, "muted")
	}

	if raw, found := object["volume"]; found {
		err = json.Unmarshal(raw, &a.Volume)
		if err != nil {
			return fmt.Errorf("error reading 'volume': %w", err)
		}
		delete(object, "volume")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WireVolume to handle AdditionalProperties
func (a WireVolume) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Muted != nil {
		object["muted"], err = json.Marshal(a.Muted)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'muted': %w", err)
		}
	}

	if a.Volume != nil {
		object["volume"], err = json.Marshal(a.Volume)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'volume': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
